#!/bin/sh
# Samuel Jero <sj323707@ohio.edu>
# Cleanup script

# Kill any lingering ION processes from previous runs
killm 2>/dev/null
sleep 1

IONSENDFILE=./ionsendfile.txt
IONRECEIVEFILE=./ionreceivefile.txt

rm -f "${IONSENDFILE}" "${IONRECEIVEFILE}" configs/ion.log /tmp/ion*.sdrlog
