#!/usr/bin/env bash
#
# Cleanup script for the LTP authentication test.

export ION_NODE_LIST_DIR=$PWD
killm f
echo "Cleaning up old ION..."
rm -f ion_nodes
rm -f 2.ipn.ltp/ion.log 2.ipn.ltp/node2.stdout
rm -f 3.ipn.ltp/ion.log 3.ipn.ltp/node3.stdout
rm -f 3.ipn.ltp/testfile[0-9]* 3.ipn.ltp/ltpblock.*
