#!/bin/bash
#ion start script

#ion--------------------------------------------
ionadmin	amroc.ionrc
ionadmin	global.ionrc &
ionsecadmin	amroc.ionsecrc &
ltpadmin	amroc.ltprc &
bpadmin		amroc.bprc &

#ams--------------------------------------------
amsd mib.amsrc @ amsdemo test "" &

echo "Waiting for AMS cell census (90 seconds left)..."
sleep 30
echo "Waiting for AMS cell census (60 seconds left)..."
sleep 30
echo "Waiting for AMS cell census (30 seconds left)..."
sleep 30

ramsgate amsdemo test &
