/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class gov_nasa_jpl_iondtn_NodeAdministrator */

#ifndef _Included_gov_nasa_jpl_iondtn_NodeAdministrator
#define _Included_gov_nasa_jpl_iondtn_NodeAdministrator
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     gov_nasa_jpl_iondtn_NodeAdministrator
 * Method:    init
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_gov_nasa_jpl_iondtn_NodeAdministrator_init
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
