DNAC = ../dnac
BP = ../../bpv7

# OPT = -O -Dlinux
OPT = -g -Wall -Werror -Dlinux -DSPACE_ORDER=2 -DNDEBUG
CC = gcc $(OPT) -I$(BP)/library -I$(BP)/ipn -I$(ROOT)/include
LDFLAGS = -fPIC -shared -rdynamic
LD = gcc $(LDFLAGS)

TCINCLS = \
	$(DTKA)/dtka.h \
	$(AUTHORITY)/tcaP.h \
	$(CLIENT)/tcc.h \
	$(CLIENT)/tccP.h \
	$(INCL)/tc.h

LBP = -limcfw -lipnfw -ldtn2fw -lbp

RUNTIMES = dnacp dnacc

ALL = $(RUNTIMES)

all:		$(ALL)

clean:
		rm -f *.o
		rm -f $(ALL)
		rm -f ./bin/*

install:
		cp bin/* $(ROOT)/bin

#	-	-	DNAC executables	-	-	-	-

dnacp:		dnacp.o
		$(CC) -o dnacp dnacp.o -L$(ROOT)/lib -ldtka -ltcc -ltccP -ltc $(LBP) -lici -lpthread -lm
		cp dnacp ./bin

dnacc:		dnacc.o
		$(CC) -o dnacc dnacc.o -L$(ROOT)/lib -ldtka -ltcc -ltccP -ltc $(LBP) -lici -lpthread -lm
		cp dnacc ./bin

#	-	-	Object modules	-	-	-	-	-

%.o:		$(DNAC)/%.c
		$(CC) -c $<
