#!/usr/bin/env bash
export ION_NODE_LIST_DIR=$PWD
killm f
rm -f ion_nodes
rm -f 2.ipn.ltp/ion.log 3.ipn.ltp/ion.log
rm -f 2.ipn.ltp/ionexit.report 3.ipn.ltp/ionexit.report
rm -f 3.ipn.ltp/3_delivered.txt
