=head1 NAME

bssStreamingApp - Bundle Streaming Service transmission test program

=head1 SYNOPSIS

B<bssStreamingApp> I<own_endpoint_ID> I<destination_endpoint_ID> [I<class_of_service>]

=head1 DESCRIPTION

B<bssStreamingApp> uses BSS to send streaming data over BP from
I<own_endpoint_ID> to bssrecv listening at I<destination_endpoint_ID>.
I<class_of_service> is as specified for bptrace(1); if omitted, bundles
are sent at BP's standard priority (1).

The bundles issued by B<bssStreamingApp> all have 20866-byte payloads, where
the ASCII representation of a positive integer (increasing monotonically
from 0, by 1, like a sequence number) appears at the start
of each payload. The application meters output by sleeping for
55642 microseconds after issuing each bundle to achieve an
nominal bit rate of 3Mbps, assuming the underlying system can
support that throughput rate.

Use CTRL-C to terminate the program.

=head1 FILES

No configuration files are needed.

=head1 ENVIRONMENT

No environment variables apply.

=head1 BUGS

Report bugs to <https://github.com/nasa-jpl/ION-DTN/issues>

=head1 SEE ALSO

bssrecv(1), bss(3)
