#!/bin/sh
#
# Usage: fec-deadcode-check.sh [--update]
#
# Links the vendored FEC sources against a driver calling the ion_fec entry
# points and compares the sections the linker discards with
# fec-deadcode.manifest.  --update regenerates the manifest.
#
# --gc-sections keeps anything whose address is taken, so the manifest
# under-reports dead code and never over-reports it.

set -e

top=$(dirname "$0")/../..
top=$(cd "$top" && pwd)
manifest="$top/.github/scripts/fec-deadcode.manifest"
work=$(mktemp -d)
trap 'rm -rf "$work"' EXIT

CC=${CC:-cc}

cat > "$work/driver.c" <<'EOF'
/* Root set: the entry points ION calls. */
#include <stdlib.h>
#include <string.h>
#include "ion_fec.h"

int main(void)
{
	const unsigned char *in[4];
	unsigned char *out[1], *blocks[6], *parity[2];
	unsigned int pnums[2], idx[4];
	ion_fec_t *fec;
	int i, rc = 0;

	fec = ion_fec_new(4, 6);
	if (fec == NULL) return 1;
	for (i = 0; i < 6; i++) {
		blocks[i] = malloc(1024);
		memset(blocks[i], i + 1, 1024);
	}
	for (i = 0; i < 2; i++) { parity[i] = blocks[4 + i]; pnums[i] = 4 + i; }
	ion_fec_encode(fec, (const unsigned char *const *) blocks, parity,
			pnums, 2, 1024);

	/* Rebuild block 0 from blocks 1..3 plus one parity block. */
	in[0] = blocks[1]; idx[0] = 1;
	in[1] = blocks[2]; idx[1] = 2;
	in[2] = blocks[3]; idx[2] = 3;
	in[3] = parity[0]; idx[3] = 4;
	out[0] = calloc(1, 1024);
	ion_fec_decode(fec, in, out, idx, 1024);
	if (memcmp(out[0], blocks[0], 1024) != 0) rc = 1;

	free(out[0]);
	for (i = 0; i < 6; i++) free(blocks[i]);
	ion_fec_free(fec);
	return rc;
}
EOF

# Keep in step with libgfcomplete_la_SOURCES / libjerasure_la_SOURCES.
$CC -O2 -w -ffunction-sections -fdata-sections \
	-I"$top/tc/gf-complete/include" \
	-I"$top/tc/jerasure/include" \
	-I"$top/tc/include" \
	"$top/tc/gf-complete/src/gf.c" \
	"$top/tc/gf-complete/src/gf_w4.c" \
	"$top/tc/gf-complete/src/gf_w8.c" \
	"$top/tc/gf-complete/src/gf_w16.c" \
	"$top/tc/gf-complete/src/gf_w32.c" \
	"$top/tc/gf-complete/src/gf_wgen.c" \
	"$top/tc/gf-complete/src/gf_cpu.c" \
	"$top/tc/jerasure/src/jerasure.c" \
	"$top/tc/jerasure/src/reed_sol.c" \
	"$top/tc/jerasure/src/galois.c" \
	"$top/tc/library/ion_fec.c" \
	"$work/driver.c" \
	-Wl,--gc-sections -Wl,--print-gc-sections \
	-o "$work/driver" -lm 2>"$work/gc.log"

if ! "$work/driver"; then
	echo "FAIL: FEC encode/decode round-trip did not reproduce the lost block" >&2
	exit 1
fi

sed -n 's/.*removing unused section .*\.text\.\([A-Za-z_0-9]*\).*/\1/p' \
	"$work/gc.log" | sort -u > "$work/dead.txt"

if [ ! -s "$work/dead.txt" ]; then
	echo "FAIL: linker reported no discarded sections; is --gc-sections supported?" >&2
	exit 1
fi

if [ "$1" = "--update" ]; then
	cat > "$manifest" <<EOF
# Generated by .github/scripts/fec-deadcode-check.sh --update; do not edit.
# Vendored FEC functions no ION path reaches.
EOF
	cat "$work/dead.txt" >> "$manifest"
	echo "updated $manifest ($(wc -l < "$work/dead.txt") functions)"
	exit 0
fi

grep -v '^#' "$manifest" | grep -v '^$' | sort -u > "$work/expected.txt"

if diff -u "$work/expected.txt" "$work/dead.txt" > "$work/diff.txt"; then
	echo "OK: $(wc -l < "$work/dead.txt") unreachable functions, manifest matches"
	exit 0
fi

echo "Reachable surface of the vendored FEC libraries changed." >&2
echo >&2
sed -n 's/^+\([A-Za-z_]\)/  now unreachable (dead): \1/p' "$work/diff.txt" >&2
sed -n 's/^-\([A-Za-z_]\)/  NOW REACHABLE (revived): \1/p' "$work/diff.txt" >&2
echo >&2
echo "A revived function means ION now depends on vendored code it did not" >&2
echo "before.  Review that, then run .github/scripts/fec-deadcode-check.sh --update." >&2
exit 1
