version: 2

python:
  install:
    - method: uv
      command: sync
      path: site-docs/

build:
  os: ubuntu-22.04
  tools:
    python: "3.12"
  apt_packages:
    - perl
    - cpanminus
  jobs:
    pre_create_environment:
      - cpanm --installdeps .
      - cd ./site-docs/docs && ./convert-pod-to-md.sh
    build:
      html:
        - cd ./site-docs && zensical build
    post_build:
      - mkdir -p $READTHEDOCS_OUTPUT/html/
      - cp --recursive site-docs/site/* $READTHEDOCS_OUTPUT/html/
