version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.12"
  apt_packages:
    - perl
    - cpanminus
  jobs:
    pre_create_environment:
      - cpanm Pod::Markdown  # Install the required Perl module
      - chmod +x ./gh-pages/docs/convert-pod-to-md.sh
      - cd ./gh-pages/docs && ./convert-pod-to-md.sh  # Script to convert POD to Markdown

python:
  install:
    - requirements: ./readthedocs-requirements.txt

mkdocs:
  configuration: gh-pages/mkdocs.yml  # Path to the mkdocs.yml in the gh-pages directory
