#!/usr/bin/env bash
# generate-man-lists.sh  <srcdir> <builddir>
# Emits POSIX-make assignments for man-page lists.

set -e
[ $# -eq 2 ] || { echo "Usage: $0 <srcdir> <builddir>" >&2; exit 1; }
srcdir=$1; builddir=$2

# Gather all .1/.3/.5 files, sort them
mapfile -t allmans < <(find "$srcdir" -type f \
    \( -name '*.1' -o -name '*.3' -o -name '*.5' \) \
    | sed "s|^$srcdir/||" \
    | sort)

# Partition by extension
man1=(); man3=(); man5=()
for m in "${allmans[@]}"; do
    case "$m" in
        *.1) man1+=("$m") ;;
        *.3) man3+=("$m") ;;
        *.5) man5+=("$m") ;;
    esac
done

# Build .ps lists
ps1=(); ps3=(); ps5=()
for m in "${man1[@]}"; do ps1+=("${m}.ps"); done
for m in "${man3[@]}"; do ps3+=("${m}.ps"); done
for m in "${man5[@]}"; do ps5+=("${m}.ps"); done

# Combine ps lists in section order
man_ps_sorted=("${ps1[@]}" "${ps3[@]}" "${ps5[@]}")

# Output a makefile fragment
{
    echo "# Generated by generate-man-lists.sh"
    printf "man_sections_1 = %s\n" "${man1[*]}"
    printf "man_sections_3 = %s\n" "${man3[*]}"
    printf "man_sections_5 = %s\n" "${man5[*]}"
    printf "man_ps_sorted = %s\n" "${man_ps_sorted[*]}"
} > "$builddir/man-lists.mk"
