#!/bin/bash

IONPROCESSLIST="acsadmin lt-acsadmin \
	acslist lt-acslist \
	amsbenchr lt-amsbenchr \
	amsbenchs lt-amsbenchs \
	amsd lt-amsd \
	amshello lt-amshello \
	amslog lt-amslog \
	amslogprt lt-amslogprt \
	amsmib lt-amsmib \
	amsshell lt-amsshell \
	amsstop lt-amsstop \
	aoslsi lt-aoslsi \
	aoslso lt-aoslso \
	bibeadmin lt-bibeadmin \
	bibeclo lt-bibeclo \
	bpadmin lt-bpadmin \
	bpcancel lt-bpcancel \
	bpchat lt-bpchat \
	bpclm lt-bpclm \
	bpclock lt-bpclock \
	bpcounter lt-bpcounter \
	bpcp lt-bpcp \
	bpcpd lt-bpcpd \
	bpdriver lt-bpdriver \
	bpecho lt-bpecho \
	bping lt-bping \
	bplist lt-bplist \
	bpnmtest lt-bpnmtest \
	bprecvfile lt-bprecvfile \
	bprecvtest lt-bprecvtest \
	bpsecadmin lt-bpsecadmin \
	bpsendfile lt-bpsendfile \
	bpsendtest lt-bpsendtest \
	bpsink lt-bpsink \
	bpsource lt-bpsource \
	bpstats lt-bpstats \
	bpstats2 lt-bpstats2 \
	bptrace lt-bptrace \
	bptransit lt-bptransit \
	bputa lt-bputa \
	brsccla lt-brsccla \
	brsscla lt-brsscla \
	bsscounter lt-bsscounter \
	bssdriver lt-bssdriver \
	bsspadmin lt-bsspadmin \
	bsspcli lt-bsspcli \
	bsspclo lt-bsspclo \
	bsspclock lt-bsspclock \
	bssrecv lt-bssrecv \
	bssStreamingApp lt-bssStreamingApp \
	cfdpadmin lt-cfdpadmin \
	cfdpclock lt-cfdpclock \
	cfdptest lt-cfdptest \
	cgrfetch lt-cgrfetch \
	cpsd lt-cpsd \
	dccpcli lt-dccpcli \
	dccpclo lt-dccpclo \
	dccplsi lt-dccplsi \
	dccplso lt-dccplso \
	dgr2file lt-dgr2file \
	dgrcli lt-dgrcli \
	dgrclo lt-dgrclo \
	dtka lt-dtka \
	dtkaadmin lt-dtkaadmin \
	dtn2admin lt-dtn2admin \
	dtn2adminep lt-dtn2adminep \
	dtn2fw lt-dtn2fw \
	dtpcadmin lt-dtpcadmin \
	dtpcclock lt-dtpcclock \
	dtpcd lt-dtpcd \
	dtpcreceive lt-dtpcreceive \
	dtpcsend lt-dtpcsend \
	file2dgr lt-file2dgr \
	file2sdr lt-file2sdr \
	file2sm lt-file2sm \
	file2tcp lt-file2tcp \
	file2udp lt-file2udp \
	hmackeys lt-hmackeys \
	imcadmin lt-imcadmin \
	imcadminep lt-imcadminep \
	imcfw lt-imcfw \
	ionadmin lt-ionadmin \
	ionexit lt-ionexit \
	ionrestart lt-ionrestart \
	ionsecadmin lt-ionsecadmin \
	ionunlock lt-ionunlock \
	ionwarn lt-ionwarn \
	ipnadmin lt-ipnadmin \
	ipnadminep lt-ipnadminep \
	ipnd lt-ipnd \
	ipnfw lt-ipnfw \
	lgagent lt-lgagent \
	lgsend lt-lgsend \
	ltpadmin lt-ltpadmin \
	ltpcli lt-ltpcli \
	ltpclo lt-ltpclo \
	ltpclock lt-ltpclock \
	ltpcounter lt-ltpcounter \
	ltpdeliv lt-ltpdeliv \
	ltpdriver lt-ltpdriver \
	ltpmeter lt-ltpmeter \
	ltpsecadmin lt-ltpsecadmin \
	nm_agent lt-nm_agent \
	nm_mgr lt-nm_mgr \
	owltsim lt-owltsim \
	owlttb lt-owlttb \
	psmshell lt-psmshell \
	psmwatch lt-psmwatch \
	ramsgate lt-ramsgate \
	recvfile lt-recvfile \
	rfxclock lt-rfxclock \
	sdatest lt-sdatest \
	sdr2file lt-sdr2file \
	sdrmend lt-sdrmend \
	sdrwatch lt-sdrwatch \
	sendfile lt-sendfile \
	sm2file lt-sm2file \
	smlistsh lt-smlistsh \
	smrbtsh lt-smrbtsh \
	stcpcli lt-stcpcli \
	stcpclo lt-stcpclo \
	tcaadmin lt-tcaadmin \
	tcaboot lt-tcaboot \
	tcacompile lt-tcacompile \
	tcapublish lt-tcapublish \
	tcarecv lt-tcarecv \
	tcc lt-tcc \
	tccadmin lt-tccadmin \
	tcp2file lt-tcp2file \
	tcpbsi lt-tcpbsi \
	tcpbso lt-tcpbso \
	tcpcli lt-tcpcli \
	tcpclo lt-tcpclo \
	tcputa lt-tcputa \
	udp2file lt-udp2file \
	udpbsi lt-udpbsi \
	udpbso lt-udpbso \
	udpcli lt-udpcli \
	udpclo lt-udpclo \
	udplsi lt-udplsi \
	udplso lt-udplso \
	"

