#!/bin/bash
# shell script to remove all of my IPC keys
# Modified by Robert Martin to work on Mac 10.4, due to IPCS requiring sudo to list any 
# shared memory usage, even if you own it; also modified using Jim Wyllie's "kill 
# all related processes" idea
# Simplified by Shawn Ostermann in October, 2023 to remove Enhanced Regular Expressions, "grep -E", and "sed -E"
# to make it more portable (to Solaris in particular).  Also quieted down the output a little.

OS_VERS=""

# Fix for SourceForge Bug #60, killm IPC cleanup fails for long account names
# Since ipcs truncates usernames to 10 characters, we need to match against a
# truncated username so we trim the username to 10 characters.
# NOTE: This may cause conflicts with long usernames with similar beginning
#       characters. We'll look for a more robust solution in the near future.
USERNAME_CUT=$(echo "$USER" | cut -c 1-10)
KILLPROCESSLIST="acsadmin lt-acsadmin \
	acslist lt-acslist \
	amsbenchr lt-amsbenchr \
	amsbenchs lt-amsbenchs \
	amsd lt-amsd \
	amshello lt-amshello \
	amslog lt-amslog \
	amslogprt lt-amslogprt \
	amsmib lt-amsmib \
	amsshell lt-amsshell \
	amsstop lt-amsstop \
	aoslsi lt-aoslsi \
	aoslso lt-aoslso \
	bibeadmin lt-bibeadmin \
	bibeclo lt-bibeclo \
	bpadmin lt-bpadmin \
	bpcancel lt-bpcancel \
	bpchat lt-bpchat \
	bpclm lt-bpclm \
	bpclock lt-bpclock \
	bpcounter lt-bpcounter \
	bpcp lt-bpcp\
	bpcpd lt-bpcpd\
	bpdriver lt-bpdriver \
	bpecho lt-bpecho \
	bping lt-bping \
	bplist lt-bplist \
	bpnmtest lt-bpnmtest \
	bprecvfile lt-bprecvfile \
	bprecvtest lt-bprecvtest \
	bpsecadmin lt-bpsecadmin \
	bpsendfile lt-bpsendfile \
	bpsendtest lt-bpsendtest \
	bpsink lt-bpsink \
	bpsource lt-bpsource \
	bpstats lt-bpstats \
	bpstats2 lt-bpstats2 \
	bptrace lt-bptrace \
	bptransit lt-bptransit \
	bputa lt-bputa \
	brsccla lt-brsccla \
	brsscla lt-brsscla \
	bsscounter lt-bsscounter \
	bssdriver lt-bssdriver \
	bsspadmin lt-bsspadmin \
	bsspcli lt-bsspcli \
	bsspclo lt-bsspclo \
	bsspclock lt-bsspclock \
	bssrecv lt-bssrecv \
	bssStreamingApp lt-bssStreamingApp \
	cfdpadmin lt-cfdpadmin \
	cfdpclock lt-cfdpclock \
	cfdptest lt-cfdptest \
	cgrfetch lt-cgrfetch \
	cpsd lt-cpsd \
	dccpcli lt-dccpcli \
	dccpclo lt-dccpclo \
	dccplsi lt-dccplsi \
	dccplso lt-dccplso \
	dgr2file lt-dgr2file \
	dgrcli lt-dgrcli \
	dgrclo lt-dgrclo \
	dtka lt-dtka \
	dtkaadmin lt-dtkaadmin \
	dtn2admin lt-dtn2admin \
	dtn2adminep lt-dtn2adminep \
	dtn2fw lt-dtn2fw \
	dtpcadmin lt-dtpcadmin \
	dtpcclock lt-dtpcclock \
	dtpcd lt-dtpcd \
	dtpcreceive lt-dtpcreceive \
	dtpcsend lt-dtpcsend \
	file2dgr lt-file2dgr \
	file2sdr lt-file2sdr \
	file2sm lt-file2sm \
	file2tcp lt-file2tcp \
	file2udp lt-file2udp \
	hmackeys lt-hmackeys \
	imcadmin lt-imcadmin \
	imcadminep lt-imcadminep \
	imcfw lt-imcfw \
	ionadmin lt-ionadmin \
	ionexit lt-ionexit \
	ionrestart lt-ionrestart \
	ionsecadmin lt-ionsecadmin \
	ionunlock lt-ionunlock \
	ionwarn lt-ionwarn \
	ipnadmin lt-ipnadmin \
	ipnadminep lt-ipnadminep \
	ipnd lt-ipnd \
	ipnfw lt-ipnfw \
	lgagent lt-lgagent \
	lgsend lt-lgsend \
	ltpadmin lt-ltpadmin \
	ltpcli lt-ltpcli \
	ltpclo lt-ltpclo \
	ltpclock lt-ltpclock \
	ltpcounter lt-ltpcounter \
	ltpdeliv lt-ltpdeliv \
	ltpdriver lt-ltpdriver \
	ltpmeter lt-ltpmeter \
	ltpsecadmin lt-ltpsecadmin \
	nm_agent lt-nm_agent \
	nm_mgr lt-nm_mgr \
	owltsim lt-owltsim \
	owlttb lt-owlttb \
	psmshell lt-psmshell \
	psmwatch lt-psmwatch \
	ramsgate lt-ramsgate \
	recvfile lt-recvfile \
	rfxclock lt-rfxclock \
	sdatest lt-sdatest \
	sdr2file lt-sdr2file \
	sdrmend lt-sdrmend \
	sdrwatch lt-sdrwatch \
	sendfile lt-sendfile \
	sm2file lt-sm2file \
	smlistsh lt-smlistsh \
	smrbtsh lt-smrbtsh \
	stcpcli lt-stcpcli \
	stcpclo lt-stcpclo \
	tcaadmin lt-tcaadmin\
	tcaboot lt-tcaboot\
	tcacompile lt-tcacompile\
	tcapublish lt-tcapublish\
	tcarecv lt-tcarecv\
	tcc lt-tcc\
	tccadmin lt-tccadmin \
	tcp2file lt-tcp2file \
	tcpbsi lt-tcpbsi \
	tcpbso lt-tcpbso \
	tcpcli lt-tcpcli \
	tcpclo lt-tcpclo \
	tcputa lt-tcputa \
	udp2file lt-udp2file \
	udpbsi lt-udpbsi \
	udpbso lt-udpbso \
	udpcli lt-udpcli \
	udpclo lt-udpclo \
	udplsi lt-udplsi \
	udplso lt-udplso \
	"

sw_vers 2> /dev/null > /dev/null

#if sw_vers ran, then we're on a mac system
if [ "$?" -eq 0 ]; then  
	OS_VERS=$(sw_vers | grep 10.4)
fi

OSNAME=`uname`
if [ "$OSNAME" = "SunOS" ]; then
    KILLCMD="pkill"
	PS="/usr/bin/ps"
	PS_ARGS="-fe"
	PROCESS_LIMIT=1
elif [[ "$OSNAME" == "MINGW"* ]]; then
  	KILLCMD="taskkill /f /im"
  	PS="tasklist"
  	PS_ARGS=""
  	PROCESS_LIMIT=64
  	MINGW="true"
else
    KILLCMD="killall"
	PS="ps"
	PS_ARGS="-fe"
	if [ "$(uname -m)" = "x86_64" ]; then
		PROCESS_LIMIT=64
	else
    	PROCESS_LIMIT=32
	fi
fi

if [ "$MINGW" != "true" ]; then
	#echo "Sending TERM to ${KILLPROCESSLIST}..."   # (too noisy)
	echo "Sending TERM to the processes..."
	echo "${KILLPROCESSLIST}" | xargs -n $PROCESS_LIMIT $KILLCMD 2> /dev/null

	sleep 2

	echo "Sending KILL to the processes..."
	echo "${KILLPROCESSLIST}" | xargs -n $PROCESS_LIMIT $KILLCMD -KILL 2> /dev/null

	sleep 2
else
	# note that the TERM signal isn't supported in Windows, so processes are only killed. This also must be done via powershell
	echo "Killing processes using PowerShell..."
    powershell -Command "foreach (\$proc in '${KILLPROCESSLIST}'.Split(' ')) { \$proc = \$proc.Trim(); taskkill /F /IM \"\$proc.exe\" }" 2> /dev/null
fi


echo "Checking if all ION processes ended..."

PSFILE="/tmp/ps.$$"
# grab all running processes
${PS} ${PS_ARGS} > ${PSFILE}
# see if any of those still-running processes belong to ION
for PROC in ${KILLPROCESSLIST}; do
    grep "[^-a-zA-Z]${PROC}$" "${PSFILE}" | grep -v "defunct" | \
        awk '{printf("  *** Unknown error: process %s not killed...try rebooting\n", $NF);}'
done

rm -f ${PSFILE}

echo "Deleting shared memory to remove SDR..."

if [ "$MINGW" == "true" ]; then 
	# for 2024 redesign of Windows MSYS
	powershell remove_win_shmem.ps1 
elif [[ -z "$OS_VERS" ]]; then 
	# For mac >=10.5 and Linux
	for Q in `ipcs -q | grep $USERNAME_CUT | awk '{ print $2 }'`; do ipcrm -q $Q; done
	for M in `ipcs -m | grep $USERNAME_CUT | awk '{ print $2 }'`; do ipcrm -m $M; done
	for S in `ipcs -s | grep $USERNAME_CUT | awk '{ print $2 }'`; do ipcrm -s $S; done
else
	# For mac 10.4, since ipcs on it is weird.
	echo "Since ipcs on Apple OSX 10.4 is weird, this script (killm) needs to use sudo, and will ask for your password"
	for Q in `sudo ipcs -q | grep $USERNAME_CUT | awk '{ print $3 }'`; do ipcrm -Q $Q; done
	for M in `sudo ipcs -m | grep $USERNAME_CUT | awk '{ print $3 }'`; do ipcrm -M $M; done
	for S in `sudo ipcs -s | grep $USERNAME_CUT | awk '{ print $3 }'`; do ipcrm -S $S; done
fi

# remove posix named semaphores if this platform maps them into the file system
# Solaris puts them in /tmp/.SEM*, Linux in /dev/shm/sem.*, MacOS doesn't put them in file system
echo "Deleting Posix Named Semaphores..."
rm -f /dev/shm/sem.ion:GLOBAL* /tmp/.SEM*ion:GLOBAL* || (echo '*** Re-run killm with sudo to remove remaining semaphores: '; find /dev/shm /tmp/ -name 'sem.ion:GLOBAL*' -o -name '/tmp/.SEM*ion:GLOBAL*' 2>/dev/null)

echo "Killm completed."	
exit 0