all:
	gmake -C ici $@
	gmake -C ici install
	gmake -C ltp $@
	gmake -C ltp install
	gmake -C dgr $@
	gmake -C dgr install
	gmake -C bp $@
	gmake -C bp install
	gmake -C ams $@
	gmake -C ams install
	gmake -C cfdp $@
	gmake -C cfdp install
	gmake -C bss $@
	gmake -C bss install

clean:
	gmake -C ici $@
	gmake -C ltp $@
	gmake -C dgr $@
	gmake -C bp $@
	gmake -C ams $@
	gmake -C cfdp $@
	gmake -C bss $@

test:
	cd tests
	./runtests
