BP = bpv7
VNAME = ION-OPEN-SOURCE-4.2.0

# BPSec implementation toggle: set to 1 to use BSL, 0 for original BPSec.
# Default is original BPSec (0).  Override on the command line:
#   gmake -f Makefile.dev all USING_BSL=1
USING_BSL ?= 0

ADD_FLAGS += -DVNAME=\"$(VNAME)\" -DUSING_BSL=$(USING_BSL)

ifeq ($(USING_BSL),1)
BSL_HOME ?= $(CURDIR)/external/BSL/testroot/usr
else
BSL_HOME =
endif

# Installation root directory (can be overridden on command line)
ROOT ?= /usr/local

SCRIPTS= ionstart ionrun ionstop killm ion-diagnostics ionscript ionstart.awk

$(info Development Makefiles actively maintained for only for "bpv7" on platform "x86_64-linux" options)
$(info  - All other options (bpv6 and platforms) are informational only.)
$(info ION ROOT: ADD_FLAGS is $(ADD_FLAGS))


all:	with$(BP)

withbpv6:
	gmake -C ici all ADD_FLAGS="$(ADD_FLAGS)"
	gmake -C ltp all ADD_FLAGS="$(ADD_FLAGS)"
	gmake -C dgr all ADD_FLAGS="$(ADD_FLAGS)"
	gmake -C bssp all ADD_FLAGS="$(ADD_FLAGS)"
	gmake -C $(BP) all ADD_FLAGS="$(ADD_FLAGS)" BSL_HOME="$(BSL_HOME)"
	gmake -C tc all ADD_FLAGS="$(ADD_FLAGS)" BSL_HOME="$(BSL_HOME)"
	gmake -C ams all ADD_FLAGS="$(ADD_FLAGS)" BSL_HOME="$(BSL_HOME)"
	gmake -C cfdp all BP=$(BP) ADD_FLAGS="$(ADD_FLAGS)" BSL_HOME="$(BSL_HOME)"
	gmake -C bss all ADD_FLAGS="$(ADD_FLAGS)" BSL_HOME="$(BSL_HOME)"
	gmake -C dtpc all ADD_FLAGS="$(ADD_FLAGS)" BSL_HOME="$(BSL_HOME)"
	gmake -C nm all BP=$(BP) ADD_FLAGS="$(ADD_FLAGS)" BSL_HOME="$(BSL_HOME)"
	gmake -C restart all BP=$(BP) ADD_FLAGS="$(ADD_FLAGS)" BSL_HOME="$(BSL_HOME)"

withbpv7:
	gmake -C ici all ROOT=$(ROOT) ADD_FLAGS="$(ADD_FLAGS)"
	gmake -C ltp all ROOT=$(ROOT) ADD_FLAGS="$(ADD_FLAGS)"
	gmake -C dgr all ROOT=$(ROOT) ADD_FLAGS="$(ADD_FLAGS)"
	gmake -C bssp all ROOT=$(ROOT) ADD_FLAGS="$(ADD_FLAGS)"
	gmake -C $(BP) all ROOT=$(ROOT) ADD_FLAGS="$(ADD_FLAGS)" BSL_HOME="$(BSL_HOME)"
	gmake -C tc all ROOT=$(ROOT) ADD_FLAGS="$(ADD_FLAGS)" BSL_HOME="$(BSL_HOME)"
	gmake -C ams all ROOT=$(ROOT) ADD_FLAGS="$(ADD_FLAGS)" BSL_HOME="$(BSL_HOME)"
	gmake -C cfdp all ROOT=$(ROOT) ADD_FLAGS="$(ADD_FLAGS)" BSL_HOME="$(BSL_HOME)"
	gmake -C bss all ROOT=$(ROOT) ADD_FLAGS="$(ADD_FLAGS)" BSL_HOME="$(BSL_HOME)"
	gmake -C dtpc all ROOT=$(ROOT) ADD_FLAGS="$(ADD_FLAGS)" BSL_HOME="$(BSL_HOME)"
	gmake -C nm all ROOT=$(ROOT) BP=$(BP) ADD_FLAGS="$(ADD_FLAGS)" BSL_HOME="$(BSL_HOME)"
	gmake -C restart all ROOT=$(ROOT) BP=$(BP) ADD_FLAGS="$(ADD_FLAGS)" BSL_HOME="$(BSL_HOME)"

clean:
	gmake -C ici clean
	gmake -C ltp clean
	gmake -C dgr clean
	gmake -C bssp clean
	gmake -C $(BP) clean
	gmake -C tc clean
	gmake -C ams clean
	gmake -C cfdp clean
	gmake -C bss clean
	gmake -C dtpc clean
	gmake -C nm clean
	gmake -C restart clean

install:
	gmake -C ici install
	gmake -C ltp install
	gmake -C dgr install
	gmake -C bssp install
	gmake -C $(BP) install
	gmake -C tc install
	gmake -C ams install
	gmake -C cfdp install
	gmake -C bss install
	gmake -C dtpc install
	gmake -C nm install BP=$(BP)
	gmake -C restart install
	for file in $(SCRIPTS); \
		do cp ./$(notdir $$file) /usr/local/bin; done
	cp ionprocesses.txt /usr/local/bin/

uninstall:
	gmake -C ici uninstall
	gmake -C ltp uninstall
	gmake -C dgr uninstall
	gmake -C bssp uninstall
	gmake -C $(BP) uninstall
	gmake -C tc uninstall
	gmake -C ams uninstall
	gmake -C cfdp uninstall
	gmake -C bss uninstall
	gmake -C dtpc uninstall
	gmake -C nm uninstall
	gmake -C restart uninstall
	for file in $(SCRIPTS); \
		do rm /usr/local/bin/$(notdir $$file); done
	rm -f /usr/local/bin/ionprocesses.txt

test:
	cd tests && ./runtestset normaltests

test-all:
	cd tests && ./runtestset alltests

test-%:
	cd tests && ./runtestset $*

retest:
	cd tests && ./runtestset retest


vxworks5:
	ldppc -r -o ionModule.o				\
	./ici/arch-vxworks5/icilib.o			\
	./ltp/arch-vxworks5/ltplib.o			\
	./ams/arch-vxworks5/amslib.o			\
	./bp/arch-vxworks5/bplib.o			\
	./dgr/arch-vxworks5/dgrlib.o			\
	./vxworks-utils/arch-vxworks5/vxwutils.o	\
	./vxwork-utils/vxwork-expat/libexpat.obj

	chmod 755 ionModule.o
