#!/usr/bin/env bash
#
# system_up
# Patricia Lindner
# Aug 4, 2014
#
# This program checks whether the entire ION system or individual subsystems are running.

function USAGE {
    echo
    echo "System_Up: Interplanetary Overlay Network system status script"
    echo "USAGE:"
    echo "  system_up [-A] [-W [time]] [-i \"{p|w} [ion]\"] [-b \"{p|w} [bp]\"] [-l \"{p|w} [ltp]\"] [-D \"{p|w} [dtpc]\"] [-c \"{p|w} [cfdp]\"]"
    echo
    echo "  -A                Run all checks without polling"
    echo "  -W [time]         Run all checks with polling and optional timeout (in seconds)"
    echo
    echo "  -i \"{p|w} [ion]\"  Check ion subsystem (p=polling, w=wait, optional timeout)"
    echo "  -b \"{p|w} [bp]\"   Check bp subsystem (p=polling, w=wait, optional timeout)"
    echo "  -l \"{p|w} [ltp]\"  Check ltp subsystem (p=polling, w=wait, optional timeout)"
    echo "  -D \"{p|w} [dtpc]\" Check dtpc subsystem (p=polling, w=wait, optional timeout)"
    echo "  -c \"{p|w} [cfdp]\" Check cfdp subsystem (p=polling, w=wait, optional timeout)"
    echo "  -h                Display this help message"
    exit 1
}

function CHECK_ARGS {
    local optarg="$1"
    local opt="$2"
    # Split OPTARG into mode and optional timeout
    read -r mode timeout <<< "$optarg"
    if [[ ! "$mode" =~ ^(p|w)$ ]]; then
        echo "Error: Invalid mode '$mode' for option -$opt. Must be 'p' or 'w'."
        USAGE
    fi
    if [[ -n "$timeout" && ! "$timeout" =~ ^[0-9]+$ ]]; then
        echo "Error: Invalid timeout '$timeout' for option -$opt. Must be a number."
        USAGE
    fi
}

function CHECK_COMMAND {
    local cmd="$1"
    if ! command -v "$cmd" &>/dev/null; then
        echo "Error: Command '$cmd' not found."
        exit 1
    fi
}

# Initialize return value
ret_val=0

# Track which subsystems are requested
check_ion=false
check_bp=false
check_ltp=false
check_dtpc=false
check_cfdp=false

# First pass: determine which subsystems are requested
while getopts ":AW:i:b:l:D:c:h" opt; do
    case $opt in
        A|W) check_ion=true; check_bp=true; check_ltp=true; check_dtpc=true; check_cfdp=true ;;
        i) check_ion=true ;;
        b) check_bp=true ;;
        l) check_ltp=true ;;
        D) check_dtpc=true ;;
        c) check_cfdp=true ;;
        h) USAGE ;;
        \?) ;;
    esac
done

# Reset getopts for second pass
OPTIND=1

# Verify only the commands that will be used
if [[ "$check_ion" == true ]]; then CHECK_COMMAND "ionadmin"; fi
if [[ "$check_bp" == true ]]; then CHECK_COMMAND "bpadmin"; fi
if [[ "$check_ltp" == true ]]; then CHECK_COMMAND "ltpadmin"; fi
if [[ "$check_dtpc" == true ]]; then CHECK_COMMAND "dtpcadmin"; fi
if [[ "$check_cfdp" == true ]]; then CHECK_COMMAND "cfdpadmin"; fi

# Second pass: execute the checks
while getopts ":AW:i:b:l:D:c:h" options; do
    case $options in
        A)
            echo "Checking ion"
            echo "t w" | ionadmin
            ret_val=$((ret_val + $?))
            echo "Checking bp"
            echo "t w" | bpadmin
            ret_val=$((ret_val + $?))
            echo "Checking ltp"
            echo "t w" | ltpadmin
            ret_val=$((ret_val + $?))
            echo "Checking dtpc"
            echo "t w" | dtpcadmin
            ret_val=$((ret_val + $?))
            echo "Checking cfdp"
            echo "t w" | cfdpadmin
            ret_val=$((ret_val + $?))
            ;;
        W)
            if [[ -n "$OPTARG" && ! "$OPTARG" =~ ^[0-9]+$ ]]; then
                echo "Error: Invalid timeout '$OPTARG' for -W. Must be a number."
                USAGE
            fi
            echo "Checking ion"
            echo "t p ${OPTARG}" | ionadmin
            ret_val=$((ret_val + $?))
            echo "Checking bp"
            echo "t p ${OPTARG}" | bpadmin
            ret_val=$((ret_val + $?))
            echo "Checking ltp"
            echo "t p ${OPTARG}" | ltpadmin
            ret_val=$((ret_val + $?))
            echo "Checking dtpc"
            echo "t p ${OPTARG}" | dtpcadmin
            ret_val=$((ret_val + $?))
            echo "Checking cfdp"
            echo "t p ${OPTARG}" | cfdpadmin
            ret_val=$((ret_val + $?))
            ;;
        i)
            CHECK_ARGS "$OPTARG" "i"
            echo "Checking ion"
            echo "t ${OPTARG}" | ionadmin
            ret_val=$((ret_val + $?))
            ;;
        b)
            CHECK_ARGS "$OPTARG" "b"
            echo "Checking bp"
            echo "t ${OPTARG}" | bpadmin
            ret_val=$((ret_val + $?))
            ;;
        l)
            CHECK_ARGS "$OPTARG" "l"
            echo "Checking ltp"
            echo "t ${OPTARG}" | ltpadmin
            ret_val=$((ret_val + $?))
            ;;
        D)
            CHECK_ARGS "$OPTARG" "D"
            echo "Checking dtpc"
            echo "t ${OPTARG}" | dtpcadmin
            ret_val=$((ret_val + $?))
            ;;
        c)
            CHECK_ARGS "$OPTARG" "c"
            echo "Checking cfdp"
            echo "t ${OPTARG}" | cfdpadmin
            ret_val=$((ret_val + $?))
            ;;
        h)
            USAGE
            ;;
        \?)
            echo "Invalid option: -$OPTARG"
            USAGE
            ;;
    esac
done

echo
echo "ION system status check completed."
exit $ret_val