#!/usr/bin/env bash
#
# Samuel Jero
# Ohio University
# October 2, 2012

echo "Cleaning up old ION files..."

# Kill any lingering ION processes from previous runs
export ION_NODE_LIST_DIR=$PWD
killm f 2>/dev/null
sleep 1

rm -f ion_nodes ion.log bpdriverAduFile
rm -f /tmp/ion1.sdrlog
