#!/usr/bin/env bash
#
# Scott Burleigh
# February 26, 2012

echo "Cleaning up old ION..."
export ION_NODE_LIST_DIR=$PWD
killm f
rm -f ion_nodes 2.bench.tcp/ion.log 2.bench.tcp/bpdriverAduFile 3.bench.tcp/ion.log
