API = ../library
INCL = ../include
AUTHORITY = ../authority
CLIENT = ../client
DTKA = ../dtka
JERASURE = ../jerasure
GF_COMPLETE = ../gf-complete
BP_V = ../../bpv7

# BPSec implementation toggle (inherited from root, overridable locally).
USING_BSL ?= 0

ifeq ($(USING_BSL),1)
BSL_HOME ?= ../../external/BSL/testroot/usr
BSL_SRC = ../../external/BSL/src
BSL_BUILD = ../../external/BSL/build/default/src
BSL_INCL = -I$(BSL_SRC) -I$(BSL_BUILD) -I$(BSL_HOME)/include/bsl -I$(BSL_HOME)/include/bsl/policy_provider -I$(BSL_HOME)/include/bsl/security_context -I$(BSL_HOME)/include/bsl/ION_integration -I$(BSL_HOME)/include/m-lib
BSL_LIBDIR = -L$(BSL_HOME)/lib
else
BSL_HOME =
BSL_SRC =
BSL_BUILD =
BSL_INCL =
BSL_LIBDIR =
endif

# OPT = -O -D__linux__
OPT = -g -Wall -Werror -D__linux__ -fPIC -DSPACE_ORDER=3 -DNDEBUG
CC = gcc $(OPT) -I$(AUTHORITY) -I$(CLIENT) -I$(INCL) -I$(JERASURE)/include -I$(GF_COMPLETE)/include -I$(BP_V)/include -I$(BP_V)/library -I$(BP_V)/bsl $(BSL_INCL) -I../../ici/include -I$(ROOT)/include -L../../ici/x86_64-linux/lib -L../../bpv7/x86_64-linux/lib $(BSL_LIBDIR)
LDFLAGS = -fPIC -shared
LD = gcc $(LDFLAGS)

TCINCLS = \
	$(DTKA)/dtka.h \
	$(AUTHORITY)/tcaP.h \
	$(CLIENT)/tcc.h \
	$(CLIENT)/tccP.h \
	$(INCL)/tc.h

ifeq ($(USING_BSL),1)
LBSL = -lbsl_crypto -lbsl_default_sc -lbsl_dynamic -lbsl_front -lbsl_mock_bpa -lbsl_sample_pp -lqcbor -ljansson
else
LBSL =
endif

LBP = -lbp $(LBSL)

RUNTIMES = tcaboot tcarecv tcacompile tcapublish tcaadmin tcc tccadmin dtka dtkaadmin

ALL = check libtc.so libtcaP.so libtcc.so libtccP.so libdtka.so libjerasure.so libgf_complete.so $(RUNTIMES)

all:		$(ALL)

check:		$(TCINCLS)
		rm -f *.o
		touch check

clean:
		rm -f *.o
		rm -f $(ALL)
		rm -f ./lib/*
		rm -f ./bin/*

install:
		cp ../include/* $(ROOT)/include
		cp lib/* $(ROOT)/lib
		cp bin/* $(ROOT)/bin

#	-	-	Authority executables	-	-	-	-

tcarecv:		tcarecv.o libtcaP.so libjerasure.so libgf_complete.so
		$(CC) -o tcarecv tcarecv.o -L./lib -L$(ROOT)/lib -ltcaP -ltc $(LBP) -lici -ljerasure -lgf_complete -lpthread -lm
		cp tcarecv ./bin

tcacompile:	tcacompile.o libtcaP.so libjerasure.so libgf_complete.so
		$(CC) -o tcacompile tcacompile.o -L./lib -L$(ROOT)/lib -ltcaP -ltc $(LBP) -lici -ljerasure -lgf_complete -lpthread -lm
		cp tcacompile ./bin

tcapublish:	tcapublish.o libtcaP.so libjerasure.so libgf_complete.so
		$(CC) -o tcapublish tcapublish.o -L./lib -L$(ROOT)/lib -ltcaP -ltc $(LBP) -lici -ljerasure -lgf_complete -lpthread -lm
		cp tcapublish ./bin

tcaadmin:	tcaadmin.o libtcaP.so libjerasure.so libgf_complete.so
		$(CC) -o tcaadmin tcaadmin.o -L./lib -L$(ROOT)/lib -ltcaP -ltc $(LBP) -lici -ljerasure -lgf_complete -lpthread -lm
		cp tcaadmin ./bin

tcaboot:	tcaboot.o libtcaP.so libjerasure.so libgf_complete.so
		$(CC) -o tcaboot tcaboot.o -L./lib -L$(ROOT)/lib -ltcaP -ltc $(LBP) -lici -ljerasure -lgf_complete -lpthread -lm
		cp tcaboot ./bin

libtcaP.so:	libtcaP.o
		$(LD) -o libtcaP.so libtcaP.o
		cp libtcaP.so ./lib

#	-	-	Client executables	-	-	-	-

tcc:		tcc.o libtc.so libtcc.so libtccP.so libjerasure.so libgf_complete.so
		$(CC) -o tcc tcc.o -L./lib -L$(ROOT)/lib -ltccP -ltcc -ltc $(LBP) -lici -ljerasure -lgf_complete -lpthread -lm
		cp tcc ./bin

tccadmin:	tccadmin.o libtc.so libtcc.so libtccP.so libjerasure.so libgf_complete.so
		$(CC) -o tccadmin tccadmin.o -L./lib -L$(ROOT)/lib -ltccP -ltcc -ltc $(LBP) -lici -ljerasure -lgf_complete -lpthread -lm
		cp tccadmin ./bin

libtcc.so:	libtcc.o libtccP.so
		$(LD) -o libtcc.so libtcc.o -L./lib -ltccP
		cp libtcc.so ./lib

libtccP.so:	libtccP.o
		$(LD) -o libtccP.so libtccP.o
		cp libtccP.so ./lib

#	-	-	Library	-	-	-	-	-	-

libtc.so:	libtc.o ion_fec.o libjerasure.so libgf_complete.so
		$(LD) -o libtc.so libtc.o ion_fec.o -L./lib -Wl,-rpath-link,./lib -ljerasure -lgf_complete
		cp libtc.so ./lib

#	-	-	jerasure and gf-complete	-	-	-	-	-	-

JERASURE_OBJS = galois.o jerasure.o reed_sol.o cauchy.o liberation.o
GF_COMPLETE_OBJS = gf.o gf_wgen.o gf_w4.o gf_w8.o gf_w16.o gf_w32.o gf_w64.o gf_w128.o gf_rand.o gf_general.o gf_cpu.o gf_method.o

libjerasure.so:	$(JERASURE_OBJS)
		$(LD) -o libjerasure.so $(JERASURE_OBJS)
		cp libjerasure.so ./lib

libgf_complete.so:	$(GF_COMPLETE_OBJS)
		$(LD) -o libgf_complete.so $(GF_COMPLETE_OBJS)
		cp libgf_complete.so ./lib

#	-	-	Application -	-	-	-	-	-

dtka:		dtka.o libdtka.so libtcc.so libjerasure.so libgf_complete.so
		$(CC) -o dtka dtka.o -L./lib -L$(ROOT)/lib -ldtka -ltccP -ltcc -ltc $(LBP) -lici -ljerasure -lgf_complete -lpthread -lm
		cp dtka ./bin

dtkaadmin:	dtkaadmin.o libdtka.so libjerasure.so libgf_complete.so
		$(CC) -o dtkaadmin dtkaadmin.o -L./lib -L$(ROOT)/lib -ldtka -ltccP -ltcc -ltc $(LBP) -lici -ljerasure -lgf_complete -lpthread -lm
		cp dtkaadmin ./bin

libdtka.so:	libdtka.o
		$(LD) -o libdtka.so libdtka.o
		cp libdtka.so ./lib

#	-	-	Object modules	-	-	-	-	-

%.o:		$(API)/%.c
		$(CC) -c $<

%.o:		$(AUTHORITY)/%.c
		$(CC) -c $<

%.o:		$(CLIENT)/%.c
		$(CC) -c $<

%.o:		$(DTKA)/%.c
		$(CC) -c $<

%.o:		$(JERASURE)/src/%.c
		$(CC) -c $<

%.o:		$(GF_COMPLETE)/src/%.c
		$(CC) -c $<
