site_name: ION-DTN Open Source Documentation
site_url: https://ion-dtn.readthedocs.org
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - toc.follow
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotate
    - content.code.copy
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
      primary: blue
      accent: purple
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
      primary: blue
      accent: lime

extra_css:
  - assets/css/custom.css

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.mark
  - attr_list

copyright: Copyright (c) 2002-2011, California Institute of Technology. All rights reserved.

nav:
  - ION Overview:
      - Introduction: index.md
      - Quick Start: quick-start-guide.md
      - ION Deployment Guide: deployment-guide.md
      - ION Design & Operation Manual: design-operations-guide.md
      - Watch Characters: watch-characters.md
      - AMS Programmer's Guide: ams-programmer-guide.md
      - RTEMS 6.1 Port: rtems6-installation.md
      - Use Cases: use-cases.md
      - Publications/Documents: list-of-papers.md
      - Open Source Development & Support: community/opensource-development-support.md
      - ION Test Set: testset-readme.md
      - Regression & Demo Test Matrix: regression-demo-test-matrix.md
      - ION Tutorials: tutorials.md
      - AGENTS file for ION: AGENTS.md
  - Configuration:
      - Configuration Tools Overview: configuration-tools-overview.md
      - ionrun Setup Utility: ionrun.md
      - Basic Configuration Tutorial: basic-configuration-file-tutorial.md
      - CBR/CT (Orange Book) Tutorial: cbr-ct-tutorial.md
      - Configuration Templates: config-file-templates.md
      - BPSec Configuration Example: bpsec-configuration-examples.md
      - BSL Build & Install Guide: bsl-build-install-guide.md
      - Multi-network Configuration: configure-multiple-network-interfaces.md
      - LTP Configuration Tool: using-ltp-config-tool.md
      - ION Launcher Script: ion-launcher.md
  - ION APIs:
      - ION Design & API Overview: design-and-api-overview.md
      - ION Life Cycle Administrative Public API: public-admin-api-guide.md
      - ION Infrastructure API: ici-api.md
      - Writing Applications for ION: writing-applications-for-ion.md
      - ION Application Service Interface: application-services-api.md
      - BP Service API: bp-service-api.md
      - LTP Underlying Communications API: ltp-ucomm-api.md
      - Generic LTP Link Service Template (xlso/xlsi): ltp-generic-link-service-template.md
      - CLA API: cla-api.md
      - Extension Block Interface: extension-block-interface.md
  - Man Pages:
      - Man Pages: man-page-introduction.md
      - Asychronous Messaging System (AMS): man/ams/index.md
      - Bundle Protcool v7 (BPv7): man/bpv7/index.md
      - Bundle Streaming Service (BSS): man/bss/index.md
      - Bundle Streaming Service (Test Utility) Protocol (BSSP): man/bssp/index.md
      - CCSDS File Delivery Protocol (CFDP): man/cfdp/index.md
      - Datagram Retransmission System (DGR): man/dgr/index.md
      - Delay Tolerant Payload Conditioning (DTPC): man/dtpc/index.md
      - Interplanetary Communications Infrastructure (ICI): man/ici/index.md
      - Licklider Transmission Protocol (LTP): man/ltp/index.md
      - Network Management Agent for Asynchronous Management Protocol (AMP): man/nm/index.md
      - ION Node Restart Utility: man/restart/ionrestart.md
      - Delay Tolerant Key Administration: man/tc/index.md
  - Topics:
      - SDR Reversibility: topics/deep-dive-sdr-reversibility.md
      - LTP UDP Multisend & Tuning: topics/ltp-udp-multisend-tuning.md
      - LTP Performance: topics/ltp-performance.md
      - CFDP SW Architecture: cfdp-sw-architecture.md
      - Contact Graph Events and LTP: contact-graph-events-and-ltp.md
      - Contact Discovery with ipnd (Opportunistic Ducts): contact-discovery-with-ipnd.md
      - Bundle Forwarding Disposition (Prospect/Limbo/Abandon): topics/bundle-forwarding-disposition.md
      - Knowledge Base, Issues & Patches: known-issues.md
      - ION Shutdown Guide: shutdown-guide.md
      - Standard Operations Procedure: standard-operating-procedure.md
      - Platform Macros & Error Reporting: platform-macros-error-reporting.md
      - ION Utility Programs: utilities.md
      - ION Monitoring Guide: monitoring-guide.md
      - ION Coding Guide: coding-guide.md
      - SPP, EPP, and File CLA Description: spp-epp-file-cla-description.md
      - IPN Naming Scheme Transition: ipn-naming-scheme-transition.md
      - Archived Software: archive.md
  - Cloud Deployment (Archive):
      - Running 1 ION Node on Cloud VM: community/dtn-gcp-main/ion-one-node-on-cloud-linux-vm.md
      - Running 2 ION Node on Cloud VM: community/dtn-gcp-2nodes/ion-two-node-on-cloud-linux-vms.md
      - ION and IOT: community/dtn-gcp-iot-main/ion-and-iot-on-linux-vms-running-on-cloud-computing.md
      - LTP and TCP on Azure: community/dtn-gcp-ltp-tcp-main/ion-ltp-tcp-on-azure.md
      - Multicast: community/dtn-multicasting-main/multicasting-over-ion.md
      - Video Intelligence: community/dtn-video-intelligence-main/video-intelligence.md
