#!/usr/bin/env bash
# Bring up receiver node 3.

ionadmin    bench.ionrc
sleep 1
ionadmin    ../global.ionrc
sleep 1
ionsecadmin bench.ionsecrc
sleep 1
ltpadmin    bench.ltprc
sleep 1
bpadmin     bench.bprc
