#!/usr/bin/env bash

echo "Cleaning up old ION..."
export ION_NODE_LIST_DIR=$PWD
killm f

HOSTS_FILE="/etc/hosts"
BACKUP_FILE="$PWD/hosts.bak"

if [ -f "$BACKUP_FILE" ]; then
    echo "Restoring original $HOSTS_FILE..."
    sudo cp "$BACKUP_FILE" "$HOSTS_FILE"
    if [ $? -eq 0 ]; then
        echo "Restored $HOSTS_FILE successfully"
        sudo rm "$BACKUP_FILE"
    else
        echo "Error: Failed to restore $HOSTS_FILE from $BACKUP_FILE, must do it manually."
        exit 1
    fi
fi

rm -f ion_nodes 2.bench.udp/ion.log 2.bench.udp/bpdriverAduFile 3.bench.udp/ion.log 3.bench.udp/bpacq*
