#!/bin/bash
# Sends bundles to the local ION node with custody transfer requested,
# and then verifies that ION emits properly-formatted ACS bundles.
#
#	Author: Andrew Jenkins
#				University of Colorado at Boulder
#	Copyright (c) 2008-2011, Regents of the University of Colorado.
#	This work was supported by NASA contracts NNJ05HE10G, NNC06CB40C, and

export PYTHONPATH=`pwd`/..:`pwd`/../../pylib:$PYTHONPATH
echo "Setting PYTHONPATH to $PYTHONPATH"

FAIL=0
DTND="dtnd"

echo "Killing old ION..."
killm
sleep 1

echo "Starting ION..."
srcdir=`pwd`
echo "ionstart -I host1.rc"
"ionstart" -I "host1.rc"

echo "l\nq" | acsadmin

# give ION some time to start up
sleep 1

# start up DTN2.
echo "Starting dtn2..."
rm -r dtn2db dtn2logfile
mkdir -p dtn2db/{db,bundles}
$DTND -t -d -c dtn2.conf -o dtn2logfile -l debug
sleep 1
DTN2PID=$(grep "DTN daemon starting up" dtn2logfile | sed -e "s/.*pid \([0-9]\+\).*/\1/" | tail -n 1)

# Run the test manifest.
../test-acs manifest
FAIL=$?

# shut down ion processes
echo "Stopping ion..."
ionstop

echo "Stopping dtn2..."
kill $DTN2PID

exit $FAIL
