#!/bin/bash
# 
# this test checks the linking cleanliness of the executables
#
# it's a bit icky, because it's not obvious what files are executables
# so we install them all in a throw-away directory, then check the matching files in $IONDIR
#

#set -x

if ! which ldd > /dev/null; then
	echo "This system doesn't have 'ldd'; Skipping"
	exit 2;
fi

RETVAL=0

CURDIR=$PWD

(cd "$IONDIR" && "$CURDIR/make-link-graph.sh" -o "$CURDIR/ionliblinks.dot")
(cd "$IONDIR" && "$CURDIR/make-link-graph.sh" -x -o "$CURDIR/ionexelinks.dot")

bail () {
	exit $RETVAL
}

#Check library links first.
if grep -q 'color=red' ionliblinks.dot; then
	echo "Missing link between libraries:"
	grep 'color=red' ionliblinks.dot | cut -d ' ' -f 1 | sort -u
	echo
	RETVAL=1
fi
if grep -q 'color=purple' ionliblinks.dot; then
	echo "Unused link between libraries:"
	grep 'color=purple' ionliblinks.dot | cut -d ' ' -f 1 | sort -u
	echo
	RETVAL=1
fi

if [ "$RETVAL" != "0" ]; then
	echo "Errors found in libraries."
       	echo "Run 'dot -Tpng -o ionliblinks.png ionliblinks.dot' for details"
	bail
fi

#If no errors, also check executables
if grep -q 'color=red' ionliblinks.dot; then
	echo "Missing link between libraries:"
	grep 'color=red' ionliblinks.dot | cut -d ' ' -f 1 | sort -u
	echo
	RETVAL=1
fi
if grep -q 'color=purple' ionliblinks.dot; then
	echo "Unused link between libraries:"
	grep 'color=purple' ionliblinks.dot | cut -d ' ' -f 1 | sort -u
	echo
	RETVAL=1
fi

if [ "$RETVAL" != "0" ]; then
	echo "Errors found in executables."
       	echo "Run 'dot -Tpng -o ionexelinks.png ionexelinks.dot' for details"
fi

bail

