#!/bin/bash
# Issue 352 - BPCP
# Samuel Jero
# April 15, 2012

echo "Cleaning up old ION..."
rm -f 1.ipn.cfdp.bp.tcp/ion.log 2.ipn.cfdp.bp.tcp/ion.log 3.ipn.cfdp.bp.tcp/ion.log
rm -f 3.ipn.cfdp.bp.tcp/test1 1.ipn.cfdp.bp.tcp/test2 2.ipn.cfdp.bp.tcp/test3
rm -f ion_nodes