=head1 NAME

ionsecrc - ION security database management commands file

=head1 DESCRIPTION

ION security database management commands are passed to B<ionsecadmin>
either in a file of text lines or interactively at B<ionsecadmin>'s command
prompt (:).  Commands are interpreted line-by line, with exactly one command per
line.  The formats and effects of the ION security database management
commands are described below.

=head1 COMMANDS

=over 4

=item B<?>

The B<help> command.  This will display a listing of the commands and their
formats.  It is the same as the B<h> command.

=item B<#>

Comment line.  Lines beginning with B<#> are not interpreted.

=item B<e> { 1 | 0 }

Echo control.  Setting echo to 1 causes all output printed by ionsecadmin to
be logged as well as sent to stdout.  Setting echo to 0 disables this behavior.

=item B<v> 

Version number.  Prints out the version of ION currently installed.  HINT:
combine with B<e 1> command to log the version number at startup.

=item B<1>

The B<initialize> command.  Until this command is executed, the local ION
node has no security database and most I<ionsecadmin> commands will fail.

=item B<a key> I<key_name> I<file_name>

The B<add key> command.  This command adds a named key value to the
security database.  The content of I<file_name> is taken as the
value of the key.  Named keys can be referenced by other elements of the
security database.

=item B<c key> I<key_name> I<file_name>

The B<change key> command.  This command changes the value of the named
key, obtaining the new key value from the content of I<file_name>.

=item B<d key> I<key_name>

The B<delete key> command.  This command deletes the key identified by I<name>.

=item B<i key> I<key_name>

This command will print information about the named key, i.e., the length of
its current value.

=item B<l key>

This command lists all keys in the security database.

=item B<h>

The B<help> command.  This will display a listing of the commands and their
formats.  It is the same as the B<?> command.

=back

=head1 EXAMPLES

=over 4

=item a key BABKEY ./babkey.txt

Adds a new key named "BABKEY" whose value is the content of the file
"./babkey.txt".

=back

=head1 SEE ALSO

ionsecadmin(1)
