#!/usr/bin/env bash
trap 'killm f' EXIT
#
# Scott Burleigh
# January 18, 2021
#

# documentation boilerplate
CONFIGFILES=" \
./1.bench.stcp/bench.bprc \
./1.bench.stcp/bench.ionconfig \
./1.bench.stcp/bench.ionrc \
./1.bench.stcp/bench.ionsecrc \
./1.bench.stcp/bench.ipnrc \
./2.bench.stcp/bench.bprc \
./2.bench.stcp/bench.ionconfig \
./2.bench.stcp/bench.ionrc \
./2.bench.stcp/bench.ionsecrc \
./2.bench.stcp/bench.ipnrc \
./3.bench.stcp/bench.bprc \
./3.bench.stcp/bench.ionconfig \
./3.bench.stcp/bench.ionrc \
./3.bench.stcp/bench.ionsecrc \
./3.bench.stcp/bench.ipnrc \
./4.bench.stcp/bench.bprc \
./4.bench.stcp/bench.ionconfig \
./4.bench.stcp/bench.ionrc \
./4.bench.stcp/bench.ionsecrc \
./4.bench.stcp/bench.ipnrc \
"

echo "########################################"
echo
pwd | sed "s/\/.*\///" | xargs echo "NAME: "
echo
echo "PURPOSE: produce simple throughput benchmark results for performance
    of contact graph routing (SABR) operations.  The test is
    performed using the simplified TCP convergence-layer protocol
    between nodes residing on the same computer.  The nodes are in
    a diamond topology, with source node 1 sending to destination
    node 4 via relay nodes 2 and 3 that are not mutually visible."

echo
echo "CONFIG: 4 node custom:"
echo
for N in $CONFIGFILES
do
    echo "$N:"
    cat "$N"
    echo "# EOF"
    echo
done
echo "OUTPUT: Terminal messages will relay results."
echo
echo "########################################"

./cleanup
sleep 1
echo "Starting ION..."
export ION_NODE_LIST_DIR=$PWD
rm -f ./ion_nodes
RETVAL=0

# Start nodes.
cd 1.bench.stcp
./ionstart
../../../system_up -i "p 30" -b "p 30"
if [ $? -eq 2 ]; then
    echo ""
else
    echo "Node 1 not started: Aborting Test"
    exit 1
fi

cd ../2.bench.stcp
./ionstart
../../../system_up -i "p 30" -b "p 30"
if [ $? -eq 2 ]; then
    echo ""
else
    echo "Node 2 not started: Aborting Test"
    exit 1
fi

cd ../3.bench.stcp
./ionstart
../../../system_up -i "p 30" -b "p 30"
if [ $? -eq 2 ]; then
    echo ""
else
    echo "Node 3 not started: Aborting Test"
    exit 1
fi

cd ../4.bench.stcp
./ionstart
../../../system_up -i "p 30" -b "p 30"
if [ $? -eq 2 ]; then
    echo ""
else
    echo "Node 4 not started: Aborting Test"
    exit 1
fi

sleep 3
echo ""
echo "Sending 10,000 bundles of 1000 bytes each."
cd ../4.bench.stcp
bpcounter ipn:4.1 10000 &
BPCOUNTER_PID=$!
sleep 1

cd ../1.bench.stcp
bpdriver 10000 ipn:1.1 ipn:4.1 -1000 &

# Wait for transmission to finish.
echo "Waiting for transmission to finish..."
RUNNING=1
while [ "$RUNNING" -eq 1 ]
do
    sleep 1
    echo "...receiving..."
    # some ps don't like -p syntax, most do.
    if [ "$1" == "windows" ]
    then
        ps | grep "$BPCOUNTER_PID" >& /dev/null && RETURN_VALUE=1 || RETURN_VALUE=0
    else
        ps $BPCOUNTER_PID >& /dev/null && RETURN_VALUE=1 || ps -p $BPCOUNTER_PID >& /dev/null && RETURN_VALUE=1 || RETURN_VALUE=0
    fi
    if [ "$RETURN_VALUE" -eq 0 ]
    then
        echo "...transmission finished."
        RUNNING=0
    fi
done

cd ../1.bench.stcp
bpstats
cd ../2.bench.stcp
bpstats
cd ../3.bench.stcp
bpstats
cd ../4.bench.stcp
bpstats
sleep 1

echo "Stopping ION..."
killm f
echo "...benchmarking terminated."
exit $RETVAL
