# Component enablement
controller:
  enabled: true

runnerScaleSet:
  enabled: true

runnerScaleSet2:
  enabled: true

runnerScaleSet3:
  enabled: true

runnerScaleSet4:
  enabled: true

runnerScaleSet5:
  enabled: true

runnerScaleSet6:
  enabled: true

gha-runner-scale-set-controller:
  namespaceOverride: arc-systems
  serviceAccount:
    name: arc-gha-rs-controller

gha-runner-scale-set:
  namespaceOverride: arc-runners
  controllerServiceAccount:
    namespace: arc-systems
    name: arc-gha-rs-controller
  githubConfigUrl: "https://github.com/nasa-jpl/ion-ios-dev"
  githubConfigSecret: gha-runner-token-secret
  runnerScaleSetName: arc-runner-set-u22
  template:
    spec:
      containers:
        - name: runner
          image: ghcr.io/actions/actions-runner:latest
          imagePullPolicy: "Always"
          command: ["/home/runner/run.sh"]
      imagePullSecrets:
        - name: kind-cluster-pull-secret

gha-runner-scale-set-2:
  namespaceOverride: arc-runners
  controllerServiceAccount:
    namespace: arc-systems
    name: arc-gha-rs-controller
  githubConfigUrl: "https://github.com/nasa-jpl/ion-ios-dev"
  githubConfigSecret: gha-runner-token-secret
  runnerScaleSetName: arc-runner-set-ol8
  template:
    spec:
      containers:
        - name: runner
          image: ghcr.io/actions/actions-runner:latest
          imagePullPolicy: "Always"
          command: ["/home/runner/run.sh"]
      imagePullSecrets:
        - name: kind-cluster-pull-secret

gha-runner-scale-set-3:
  namespaceOverride: arc-runners
  controllerServiceAccount:
    namespace: arc-systems
    name: arc-gha-rs-controller
  githubConfigUrl: "https://github.com/nasa-jpl/ion-ios-dev"
  githubConfigSecret: gha-runner-token-secret
  runnerScaleSetName: arc-runner-set-ol9
  template:
    spec:
      containers:
        - name: runner
          image: ghcr.io/actions/actions-runner:latest
          imagePullPolicy: "Always"
          command: ["/home/runner/run.sh"]
      imagePullSecrets:
        - name: kind-cluster-pull-secret

gha-runner-scale-set-4:
  namespaceOverride: arc-runners
  controllerServiceAccount:
    namespace: arc-systems
    name: arc-gha-rs-controller
  githubConfigUrl: "https://github.com/nasa-jpl/ion-ios-dev"
  githubConfigSecret: gha-runner-token-secret
  runnerScaleSetName: arc-runner-set-rhel8
  template:
    spec:
      containers:
        - name: runner
          image: ghcr.io/actions/actions-runner:latest
          imagePullPolicy: "Always"
          command: ["/home/runner/run.sh"]
      imagePullSecrets:
        - name: kind-cluster-pull-secret

gha-runner-scale-set-5:
  namespaceOverride: arc-runners
  controllerServiceAccount:
    namespace: arc-systems
    name: arc-gha-rs-controller
  githubConfigUrl: "https://github.com/nasa-jpl/ion-ios-dev"
  githubConfigSecret: gha-runner-token-secret
  runnerScaleSetName: arc-runner-set-rhel9
  template:
    spec:
      containers:
        - name: runner
          image: ghcr.io/actions/actions-runner:latest
          imagePullPolicy: "Always"
          command: ["/home/runner/run.sh"]
      imagePullSecrets:
        - name: kind-cluster-pull-secret

gha-runner-scale-set-6:
  namespaceOverride: arc-runners
  controllerServiceAccount:
    namespace: arc-systems
    name: arc-gha-rs-controller
  githubConfigUrl: "https://github.com/nasa-jpl/ion-ios-dev"
  githubConfigSecret: gha-runner-token-secret
  runnerScaleSetName: arc-runner-set-u20
  template:
    spec:
      containers:
        - name: runner
          image: ghcr.io/actions/actions-runner:latest
          imagePullPolicy: "Always"
          command: ["/home/runner/run.sh"]
      imagePullSecrets:
        - name: kind-cluster-pull-secret
