=head1 NAME

ltpsecadmin - LTP security policy administration interface

=head1 SYNOPSIS

B<ltpsecadmin> [ I<commands_filename> ]

=head1 DESCRIPTION

B<ltpsecadmin> configures and manages LTP security policy on the local computer.

It configures and manages LTP security policy on the local
computer in response to LTP configuration commands found in
I<commands_filename>, if provided; if not, B<ltpsecadmin> prints
a simple prompt (:) so that the user may type commands directly
into standard input.

The format of commands for I<commands_filename> can be queried from
B<ltpsecadmin> by entering the command 'h' or '?' at the prompt.  The
commands are documented in ltpsecrc(5).

=head1 EXIT STATUS

=over 4

=item "0"

Successful completion of LTP security policy administration.

=back

=head1 EXAMPLES

=over 4

=item ltpsecadmin

Enter interactive LTP security policy administration command entry mode.

=item ltpsecadmin host1.ltpsecrc

Execute all configuration commands in I<host1.ltpsecrc>, then terminate
immediately.

=back

=head1 FILES

Status and diagnostic messages from B<ltpsecadmin> and from other software that
utilizes the ION node are nominally written to a log file in the current
working directory within which B<ltpsecadmin> was run.  The log file is
typically named B<ion.log>.

See also ltpsecrc(5).

=head1 ENVIRONMENT

No environment variables apply.

=head1 DIAGNOSTICS

B<Note>: all ION administration utilities expect source file input to be
lines of ASCII text that are NL-delimited.  If you edit the ionrc file on
a Windows machine, be sure to B<use dos2unix to convert it to Unix text format>
before presenting it to B<ltpsecadmin>.  Otherwise B<ltpsecadmin> will detect
syntax errors and will not function satisfactorily.

The following diagnostics may be issued to the log file:

=over 4

=item Can't open command file...

The I<commands_filename> specified in the command line doesn't exist.

=back

Various errors that don't cause B<ltpsecadmin> to fail but are noted in the
log file may be caused by improperly formatted commands given at the prompt
or in the I<commands_filename>.  Please see ltpsecrc(5) for details.

=head1 BUGS

Report bugs to <ion-dtn-support@lists.sourceforge.net>

=head1 SEE ALSO

ltpsecrc(5)
