=head1 NAME

udplsi - UDP-based LTP link service input task

=head1 SYNOPSIS

B<udplsi> {I<local_hostname> | @}[:I<local_port_nbr>]

=head1 DESCRIPTION

B<udplsi> is a background "daemon" task that receives UDP datagrams via a
UDP socket bound to I<local_hostname> and I<local_port_nbr>, extracts LTP
segments from those datagrams, and passes them to the local LTP engine.
Host name "@" signifies that the host name returned by hostname(1) is to
be used as the socket's host name.  If not specified, port number defaults
to 1113.

The link service input task is spawned automatically by B<ltpadmin> in
response to the 's' command that starts operation of the LTP protocol;
the text of the command that is used to spawn the task must be provided
as a parameter to the 's' command.  The link service input task is
terminated by B<ltpadmin> in response to an 'x' (STOP) command.

=head1 EXIT STATUS

=over 4

=item "0"

B<udplsi> terminated normally, for reasons noted in the B<ion.log> file.  If
this termination was not commanded, investigate and solve the problem identified
in the log file and use B<ltpadmin> to restart B<udplsi>.

=item "1"

B<udplsi> terminated abnormally, for reasons noted in the B<ion.log> file.
Investigate and solve the problem identified in the log file, then use
B<ltpadmin> to restart B<udplsi>.

=back

=head1 FILES

No configuration files are needed.

=head1 ENVIRONMENT

No environment variables apply.

=head1 DIAGNOSTICS

The following diagnostics may be issued to the B<ion.log> log file:

=over 4

=item udplsi can't initialize LTP.

B<ltpadmin> has not yet initialized LTP protocol operations.

=item LSI task is already started.

Redundant initiation of B<udplsi>.

=item LSI can't open UDP socket

Operating system error.  Check errtext, correct problem, and restart B<udplsi>.

=item LSI can't initialize socket

Operating system error.  Check errtext, correct problem, and restart B<udplsi>.

=item LSI can't create receiver thread

Operating system error.  Check errtext, correct problem, and restart B<udplsi>.

=back

=head1 BUGS

Report bugs to <ion-dtn-support@lists.sourceforge.net>

=head1 SEE ALSO

ltpadmin(1), udplso(1), owltsim(1)
