#!/bin/bash

echo "Cleaning up old ION..."
rm -f ion_nodes 
rm -f 1.ipn.ltp/ion.log 1.ipn.ltp/node1.stdout 1.ipn.ltp/ltpblock.* 1.ipn.ltp/testfile* 
rm -f 2.ipn.ltp/ion.log 2.ipn.ltp/node2.stdout 2.ipn.ltp/ltpblock.* 2.ipn.ltp/testfile* 
rm -f 3.ipn.ltp/ion.log 3.ipn.ltp/node3.stdout 3.ipn.ltp/ltpblock.* 3.ipn.ltp/testfile* 
rm -f 4.ipn.ltp/ion.log 4.ipn.ltp/node4.stdout 4.ipn.ltp/ltpblock.* 4.ipn.ltp/testfile*
