=head1 NAME

biberc - BIBE configuration commands file

=head1 DESCRIPTION

BIBE configuration commands are passed to B<bibeadmin> either in a file of
text lines or interactively at B<bibeadmin>'s command prompt (:).  Commands
are interpreted line-by line, with exactly one command per line.

BIBE configuration commands establish the parameters governing transmission
of BIBE PDUs to specified B<peer> nodes: anticipated delivery latency in the
forward direction, anticipated delivery latency in the return direction,
TTL for BIBE PDUs, priority for BIBE PDUs, ordinal priority for BIBE PDUs
in the event that priority is Expedited, and (optionally) data label for
BIBE PDUs.  As such, they configure BIBE convergence-layer adapter (B<bcla>)
structures.

The formats and effects of the BIBE configuration commands are described below.

=head1 GENERAL COMMANDS

=over 4

=item B<?>

The B<help> command.  This will display a listing of the commands and their
formats.  It is the same as the B<h> command.

=item B<#>

Comment line.  Lines beginning with B<#> are not interpreted.

=item B<e> { 1 | 0 }

Echo control.  Setting echo to 1 causes all output printed by bibeadmin to be
logged as well as sent to stdout.  Setting echo to 0 disables this behavior.

=item B<w> { 0 | 1 | I<activity_spec> }

The B<watch> command.  This command enables and disables production of a
continuous stream of user-selected Bundle-in-Bundle Encapsulation
custody transfer activity indication characters.  A watch parameter of "1"
selects all BIBE-CT activity indication characters; "0" de-selects all
BIBE-CT activity indication characters; any other I<activity_spec> such
as "mw" selects all activity indicators in the string, de-selecting all
others.  BIBE will print each selected activity indication character to
B<stdout> every time a processing event of the associated type occurs:

B<w>	custody of bundle is accepted

B<m>	custody acceptance is received for one bundle

B<x>	custody of bundle is refused

B<&>	custody refusal is received for one bundle

B<$>	bundle retransmitted due to expired custodial retransmission interval

=item B<h>

The B<help> command.  This will display a listing of the commands and their
formats.  It is the same as the B<?> command.

=back

=head1 BCLA COMMANDS

=over 4

=item B<a> bcla I<peer_EID> I<fwd_latency> I<rtn_latency> I<time_to_live> I<priority> I<ordinal> [I<data label>]

The B<add bcla> command.  This command adds the neighboring node identified
by I<peer_EID> as a BIBE destination of the local node.

=item B<c> bcla I<peer_EID> I<fwd_latency> I<rtn_latency> I<time_to_live> I<priority> I<ordinal> [I<data label>]

The B<change bcla> command.  This command changes the transmission parameters
governing BIBE PDU transmission to the indicated peer node.

=item B<d> bcla I<peer_EID>

The B<delete bcla> command.  This command deletes the B<bcla> identified by
I<peer_EID>.

=item B<i> bcla I<peer_EID>

This command will print information (the transmission parameters) for the
BIBE peer node identified by I<peer_EID>.

=item B<l>

This command lists all of the local node's BIBE peers.

=back

=head1 EXAMPLES

=over 4

=item a bcla ipn:3.2 10 10 60 1 0 16

Declares that ipn:3.2 is a BIBE destination and that BIBE PDUs destined for
this node are to be sent with TTL 60 seconds, priority 1 (standard), and data
label 16; it is expected that BIBE PDUs sent to this node will arrive within
10 seconds and that BIBE PDUs sent from this node will arrive within 10 seconds.

=back

=head1 SEE ALSO

bibeadmin(1), bibeclo(1)
