=head1 NAME

biberc - BIBE configuration commands file

=head1 DESCRIPTION

BIBE configuration commands are passed to B<bibeadmin> either in a file of
text lines or interactively at bibeadmin's command prompt (:).  Commands
are interpreted line-by line, with exactly one command per line.

BIBE configuration commands establish the parameters governing transmission
of BIBE PDUs to specified B<peer> nodes: segmentation threshold,
report-to endpoint, bundle status report request flags, TTL for BIBE PDUs,
priority, ordinal priority in the event that priority is Expedited,
quality-of service flags, and (optionally) data label.  As such, they
configure BIBE convergence-layer adapter (B<bcla>) structures.

The formats and effects of the BIBE configuration commands are described below.

NOTE: in order to cause bundles to be transmitted via BIBE:

=over 4

=item B<Plan>

Remember that BIBE is a convergence-layer protocol; as such, it operates
between two nodes that are topologically adjacent in a BP network (but in
this case the BP network within which the nodes are topologically adjacent
is an overlay on top of the "real" BP network).  Since the sending and
receiving nodes are topologically adjacent, they are neighbors: the sending
node MUST have an egress plan for transmission to the receiving (that is,
peer) node, and there MUST be a BIBE outduct attached to that plan.  The
affected bundles will be encapsulated within BIBE bundles (bundles whose
payloads are BIBE protocol data units, or BPDUs) by the BIBE convergence-layer
output daemon (B<bibeclo>), which will obtain all forwarding parameters from
the bcla for the peer node as established by bibeadmin.

=item B<Routing>

In order to compel a bundle to be forwarded via the BIBE peer node rather
than over some other route computed by CGR, you have to override CGR routing
for that bundle.  This is done in node administration: use ipnadmin to
establish at the BIBE sending node a I<routing override> that coerces all
bundles characterized by specified data label, destination, and/or source
to be sent directly to the peer node by means of the BIBE outduct attached
to that node's egress plan.

=item B<Segmentation and reassembly>

B<bibeclo> operates by acting as a BP application: it passes to the bundle
protocol agent, as application data units, BIBE protocol data units that
encapsulate B<segments> of the serialized bundle that is being forwarded.
Upon reception by the peer node, those segments are reassembled into the
original serialized bundle and that bundle is passed to the bundle protocol
agent in the same way as any other bundle received via any convergence-layer
adapter.

The sizes of the segments into which the original serialized bundle is
divided are determined by the value of the B<segmentation threshold> that
is mandated for BIBE traffic directed to the destination peer node.

If the segmentation threshold is zero, then segmentation is disabled for
BIBE transmission to this peer node.  The entire serialized bundle, regardless
of size, will be passed to the bundle protocol agent in a single BPDU.

Otherwise the size of each segment will be less than or equal to the
applicable segmentation threshold value.

=back

=head1 GENERAL COMMANDS

=over 4

=item B<m> limit I<reassembly time limit>

The B<manage limit> command.  This command is used to set the maximum
length of time (in seconds) within which any single segmented BIBE transfer
must be reassembled before being canceled.  It's provided to defend against
unlimited resource consumption due to bundle reassemblies that don't
complete due to loss of segment BPDUs.  The default value is 600, i.e.,
ten minutes.

The B<help> command.  This will display a listing of the commands and their
formats.  It is the same as the B<h> command.

=item B<i> limit

This command will simply print the BIBE reassembly time limit that is
currently configured for this node.

=item B<?>

The B<help> command.  This will display a listing of the commands and their
formats.  It is the same as the B<h> command.

=item B<#>

Comment line.  Lines beginning with B<#> are not interpreted.

=item B<e> { 1 | 0 }

Echo control.  Setting echo to 1 causes all output printed by bibeadmin to be
logged as well as sent to stdout.  Setting echo to 0 disables this behavior.

=item B<h>

The B<help> command.  This will display a listing of the commands and their
formats.  It is the same as the B<?> command.

=back

=head1 BCLA COMMANDS

=over 4

=item B<a> bcla I<peer_EID> I<segmentation_threshold> I<rptTo> I<bundle_status_report_request_flags> I<time_to_live> I<priority> I<ordinal> I<qosFlags> [I<data label>]

The B<add bcla> command.  This command adds the neighboring node identified
by I<peer_EID> as a BIBE destination of the local node.

=item B<c> bcla I<peer_EID> I<segmentation_threshold> I<rptTo> I<bundle_status_report_request_flags> I<time_to_live> I<priority> I<ordinal> I<qosFlags> [I<data label>]

The B<change bcla> command.  This command changes the transmission parameters
governing BIBE PDU transmission to the indicated peer node.

=item B<d> bcla I<peer_EID>

The B<delete bcla> command.  This command deletes the B<bcla> identified by
I<peer_EID>.

=item B<i> bcla I<peer_EID>

This command will print information (the transmission parameters) for the
BIBE peer node identified by I<peer_EID>.

=item B<l> bcla I<scheme_name>

This command lists all of the local node's BIBE peers whose endpoint IDs are
formed in the URI scheme identified by I<scheme_name>, e.g., B<ipn>.

=back

=head1 EXAMPLES

=over 4

=item a bcla ipn:3.2 8192 dtn:none 0 60 1 0 0 16

Declares that ipn:3.2 is a BIBE peer for which the segmentation threshold is
8192 and that BIBE PDUs destined for this node are to be sent with TTL 60
seconds, priority 1 (standard), and data label 16; no bundle status reporting
is required for these bundles.  Any bundle larger than 8192 octets will be
sent in multiple segments of at most 8192 octets each.

=back

=head1 SEE ALSO

bibeadmin(1), bibeclo(1)
