/**
 * @file entropy_src.c
 * @brief Cross-platform entropy source polling.
 *
 * This file defines an interface for generating cryptographically secure
 * random bytes across different platforms, including Windows, macOS, and
 * Unix-like systems (Linux, BSD, etc.). 
 *
 * # Error Codes
 * The functions in this interface may return specific error codes defined
 * by the `ErrorCode` enum to signal various failure conditions, such as
 * inability to open the entropy source or errors during the read operation.
 *
 * # Platform-Specific Implementations
 * - On Windows, `BCryptGenRandom` is used.
 * - On macOS, `SecRandomCopyBytes` from the Security framework is employed.
 * - On Unix-like systems, the function attempts to read from `/dev/hwrng`,
 *   falling back to `/dev/urandom` and `/dev/random` as needed.
 *
 * # Usage
 * The primary function, `poll_entropy_src`, generates random bytes and fills
 * the provided buffer. The number of generated bytes is returned through an
 * output parameter. In case of an error, a negative error code is returned.
 * Use `getErrorMessage` to retrieve a human-readable description of the error.
 *
 * @note This interface is designed for Unix/Linux, macOS, and Windows systems.
 *
 * @see ErrorCode for descriptions of the error codes.
 * @see poll_entropy_src for generating random bytes.
 * @see open_entropy_source for details on how entropy sources are prioritized 
 * and accessed.
 * @see getErrorMessage for converting error codes to human-readable messages.
 * 
 * @author Sky DeBaun - Jet Propulsion Laboratory
 *
 * Copyright (c) 2024, California Institute of Technology.
 * ALL RIGHTS RESERVED.  U.S. Government Sponsorship acknowledged.
 * 
 */

#include "entropy_src.h"
#include "ion.h"

/*
 * Retrieves a human-readable error message corresponding to ErrorCode.
 *
 * @param code The ErrorCode to translate.
 * @return A constant string containing the description of the error.
 */
const char* getErrorMessage(ErrorCode code) 
{
    switch (code) 
    {
        case INVALID_ARGUMENTS:
            return "Invalid arguments";
        case ERROR_OPENING_ENTROPY_SOURCE_WINDOWS:
            return "Error opening entropy source (Windows)";
        case ERROR_OPENING_ENTROPY_SOURCE_MAC:
            return "Error opening entropy source (MAC)";
        case ERROR_READING_RANDOM_BYTES_MAC:
            return "Error reading random bytes (MAC)";    
        case ERROR_OPENING_ENTROPY_SOURCE_LINUX:
            return "Error opening entropy source (Linux)";
        case ERROR_READING_RANDOM_BYTES_LINUX:
            return "Error reading random bytes (Linux)";        
        default:
            return "Unknown error";
    }

}//end getErrorMessage ---//



/**
 * Generates cryptographically secure random bytes.
 * 
 * This function generates a specified number of cryptographically secure
 * random bytes and writes them into the provided output buffer. The
 * actual number of generated bytes is returned through the olen pointer.
 * 
 * On Windows, this function uses BCryptGenRandom. On macOS, it uses
 * SecRandomCopyBytes. On other Unix-like systems, it tries to read from
 * /dev/hwrng, /dev/urandom, or /dev/random, in that order of preference.
 * 
 * @param output Pointer to the buffer where the random bytes will be stored.
 * @param ilen Number of bytes to generate.
 * @param olen Pointer to a size_t variable where the function will store
 *             the actual number of generated bytes.
 * @return 0 on success, or a negative error code on failure (see error codes
 *           enumeration for return values)
 */
int poll_entropy_src(void *data, unsigned char *output, size_t ilen, size_t *olen)
{
    if (!output || !olen) 
    {
        writeMemo("[!] poll_entropy_src: invalid arguments");
        return -1; //invalid arguments
    }
    *olen = 0;    

    /* WINDOWS------------------------------------------------------------ */
    #if defined(_WIN32) || defined(_WIN64)
    #pragma message("Compiling entropy_src for Windows")
        NTSTATUS status = BCryptGenRandom(NULL, output, (ULONG)ilen, BCRYPT_USE_SYSTEM_PREFERRED_RNG);
        if (status != 0) 
        {
            writeMemo("[!] poll_entropy_src: error generating random bytes ");
            return -2; //error generating random bytes
        }
        *olen = ilen; //true on success..
        return 0; //success

    /* MAC---------------------------------------------------------------- */
    #elif defined(__APPLE__)
    #pragma message("Compiling entropy_src for macOS")
        if (SecRandomCopyBytes(kSecRandomDefault, ilen, output) == errSecSuccess) 
        {
            *olen = ilen;
            return 0; //success
        } 
        else 
        {
            int fd = open_entropy_source();
            if (fd < 0) 
            {
                writeMemo("[!] poll_entropy_src: error opening entropy source");
                return -3; //error opening entropy source
            }

            ssize_t read_bytes = read(fd, output, ilen);
            if (read_bytes < 0) 
            {
                writeMemo("[!] poll_entropy_src: error reading random bytes ");
                close(fd);
                return -4; //error reading random bytes
            }

            *olen = (size_t)read_bytes;
            close(fd);
            return 0; //success
        }

    /* NIX-------------------------------------------------------------- */
    #else
    #pragma message("Compiling entropy_src for Unix/Linux")
        int fd = open_entropy_source();
        if (fd < 0) 
        {
            writeMemo("[!] poll_entropy_src: error opening entropy source");
            return -5; //error opening entropy source
        }

        ssize_t read_bytes = read(fd, output, ilen);
        if (read_bytes < 0) 
        {
            close(fd);
            writeMemo("[!] poll_entropy_src: error reading random bytes ");
            return -6; //error reading random bytes
        }

        *olen = (size_t)read_bytes;
        close(fd);        
        return 0; //success

    #endif

}//end poll_entropy_src ---//



/**
 * Opens the most suitable (strongest) entropy source available (Unix/Linux.. & MAC).
 * 
 * This function attempts to open /dev/hwrng first. If /dev/hwrng is not
 * available, it falls back to /dev/urandom. If neither is available,
 * it attempts to open /dev/random as a last resort.
 * 
 * @return File descriptor of the opened entropy source, or -1 if all attempts fail.
 */
 #if !defined(_WIN32) || !defined(_WIN64)
int open_entropy_source() 
{     
    int fd = -1; //default to error value
    
    /* attempt to read from: /dev/hwrng */
    fd = open("/dev/hwrng", O_RDONLY);
    if (fd >= 0) 
    {
        return fd;
    }

    /* else attempt to read from: /dev/urandom */
    fd = open("/dev/urandom", O_RDONLY);
    if (fd >= 0) 
    {
        return fd;
    }    

    /* else failure */
    writeMemo("[!] poll_entropy_src: error reading from entropy source");
    return fd;

}//end open_entropy_source ---//
#endif
