/**
 * @file entropy_src.c
 * @brief Cryptographic Random Number Source
 *
 * This file provides functions to generate a cryptographic-grade source
 * of random bytes using platform-specific sources. It supports Windows, 
 * macOS, and Unix-like systems by abstracting their respective APIs and 
 * filesystems for entropy generation.
 *
 * @mainpage Cryptographic Random Number Source
 *
 * ## Overview
 * This module offers a cross-platform solution to generate cryptographically
 * secure random numbers. It's designed to be portable and easy to integrate
 * into various software projects requiring high-quality randomness for
 * cryptographic operations, such as key generation, nonces, or salt values.
 *
 * ## Usage
 * To use these functions, include `entropy_src.h` in your project and link
 * against the corresponding system libraries if necessary.
 *
 * ## Supported Platforms
 * - Windows (uses BCryptGenRandom)
 * - macOS (uses SecRandomCopyBytes)
 * - Unix-like systems (tries /dev/hwrng, /dev/urandom, then /dev/random)
 *
 * ## Compilation
 * Use a C compiler that supports C99 or later. For cross-platform projects,
 * conditional compilation might be required to handle platform-specific
 * dependencies and headers.
 *
 * @author Sky DeBaun - Jet Propulsion Laboratory
 *
 * Copyright (c) 2024, California Institute of Technology.
 * ALL RIGHTS RESERVED.  U.S. Government Sponsorship acknowledged.
 *
 */

#include <stdlib.h>

#if defined(_WIN32) || defined(_WIN64)
    #include <Windows.h>
    #include <bcrypt.h>
#elif defined(__APPLE__)
    #include <Security/Security.h>
#else
    #include <unistd.h>
    #include <fcntl.h>
#endif

/**
 * Opens the most suitable entropy source available on the system.
 * 
 * This function attempts to open /dev/hwrng first. If /dev/hwrng is not
 * available, it falls back to /dev/urandom. If neither is available,
 * it attempts to open /dev/random as a last resort.
 * 
 * @return File descriptor of the opened entropy source, or -1 if all attempts fail.
 */
int open_entropy_source() 
{
    int fd = open("/dev/hwrng", O_RDONLY);
    if (fd < 0) 
    {
        fd = open("/dev/urandom", O_RDONLY);
        if (fd < 0) 
        {
            fd = open("/dev/random", O_RDONLY);
        }
    }
    return fd;
}

/**
 * Generates cryptographically secure random bytes.
 * 
 * This function generates a specified number of cryptographically secure
 * random bytes and writes them into the provided output buffer. The
 * actual number of generated bytes is returned through the olen pointer.
 * 
 * On Windows, this function uses BCryptGenRandom. On macOS, it uses
 * SecRandomCopyBytes. On other Unix-like systems, it tries to read from
 * /dev/hwrng, /dev/urandom, or /dev/random, in that order of preference.
 * 
 * @param output Pointer to the buffer where the random bytes will be stored.
 * @param ilen Number of bytes to generate.
 * @param olen Pointer to a size_t variable where the function will store
 *             the actual number of generated bytes.
 * @return 0 on success, or a negative error code on failure.
 *         -1: Invalid arguments.
 *         -2: Error generating random bytes (Windows only).
 *         -3: Error opening the entropy source.
 *         -4: Error reading from the entropy source.
 */
int entropy_src(unsigned char *output, size_t ilen, size_t *olen)
{
    if (!output || !olen) 
    {
        return -1; // Invalid arguments
    }

    *olen = 0; // Initialize output length to zero

    #if defined(_WIN32) || defined(_WIN64)
        NTSTATUS status = BCryptGenRandom(NULL, output, (ULONG)ilen, BCRYPT_USE_SYSTEM_PREFERRED_RNG);
        if (status != 0) 
        {
            return -2; // Error in generating random bytes
        }
        *olen = ilen;
        return 0; // Success
    #elif defined(__APPLE__)
        if (SecRandomCopyBytes(kSecRandomDefault, ilen, output) == errSecSuccess) 
        {
            *olen = ilen;
            return 0; // Success
        } 
        else 
        {
            int fd = open_entropy_source();
            if (fd < 0) 
            {
                return -3; // Error in opening entropy source
            }

            ssize_t read_bytes = read(fd, output, ilen);
            if (read_bytes < 0) 
            {
                close(fd);
                return -4; // Error in reading random bytes
            }

            *olen = (size_t)read_bytes;
            close(fd);
            return 0; // Success
        }
    #else
        int fd = open_entropy_source();
        if (fd < 0) 
        {
            return -3; // Error in opening entropy source
        }

        ssize_t read_bytes = read(fd, output, ilen);
        if (read_bytes < 0) 
        {
            close(fd);
            return -4; // Error in reading random bytes
        }

        *olen = (size_t)read_bytes;
        close(fd);
        return 0; // Success
    #endif
}
