INCL = ../include
ICI_INCL = ../../ici/include
ICI_LIB = ../../ici/x86_64-linux/lib
BP_LIB = ../../bpv7/x86_64-linux/lib

# BPSec implementation toggle (inherited from root, overridable locally).
USING_BSL ?= 0

ifeq ($(USING_BSL),1)
BSL_HOME ?= ../../external/BSL/testroot/usr
BSL_LIB = $(BSL_HOME)/lib
BSL_LIBDIR = -L$(BSL_LIB)
else
BSL_HOME =
BSL_LIB =
BSL_LIBDIR =
endif

API = ../library
TEST = ../test

OPT = -g -Wall -Werror -D__linux__ -fPIC -DSPACE_ORDER=3

CC = gcc $(OPT) $(ADD_FLAGS) -I$(API) -I$(TEST) -I$(INCL) -I$(ROOT)/include -I$(ICI_INCL) -I../../bpv7/include -I../../ici/library -I../../bpv7/library -L$(ICI_LIB) -L$(BP_LIB) $(BSL_LIBDIR)
LDFLAGS = -fPIC -shared
LD = gcc $(LDFLAGS)

LIBBSSOBJS = \
	libbss.o \
	libbssP.o

PUBINCLS = \
	$(INCL)/bss.h

ifeq ($(USING_BSL),1)
LBSL = -lbsl_crypto -lbsl_default_sc -lbsl_dynamic -lbsl_front -lbsl_mock_bpa -lbsl_sample_pp -lqcbor -ljansson
else
LBSL =
endif

LBP = -lbp $(LBSL)

RUNTIMES = bssrecv bssStreamingApp bsscounter bssdriver

ALL = check libbss.so $(RUNTIMES)

all:		$(ALL)

check:		$(PUBINCLS)
		rm -f *.o
		touch check

clean:
		rm -f *.o
		rm -f *.so
		rm -f $(ALL)
		rm -f ./lib/*
		rm -f ./bin/*

install:
		cp ../include/* $(ROOT)/include
		cp lib/* $(ROOT)/lib
		cp bin/* $(ROOT)/bin

uninstall:
		rm $(ROOT)/lib/libbss.so
		for file in $(PUBINCLS); \
			do rm $(ROOT)/include/$(notdir $$file); done
		for file in $(RUNTIMES); \
			do rm $(ROOT)/bin/$(notdir $$file); done

#	-	-	Test executables	-	-	-	-

bssrecv:	bssrecv.o libbss.so
		$(CC) -o bssrecv bssrecv.o -L./lib -L$(ROOT)/lib -lbss $(LBP) -lici -lpthread -lm
		cp bssrecv ./bin

bssStreamingApp:	bssStreamingApp.o libbss.so
		$(CC) -o bssStreamingApp bssStreamingApp.o -L./lib -L$(ROOT)/lib -lbss $(LBP) -lici -lpthread -lm
		cp bssStreamingApp ./bin

bsscounter:	bsscounter.o libbss.so
		$(CC) -o bsscounter bsscounter.o -L./lib -L$(ROOT)/lib -lbss $(LBP) -lici -lpthread -lm
		cp bsscounter ./bin

bssdriver:	bssdriver.o libbss.so
		$(CC) -o bssdriver bssdriver.o -L./lib -L$(ROOT)/lib -lbss $(LBP) -lici -lpthread -lm
		cp bssdriver ./bin

#	-	-	Libraries	-	-	-	-	-

libbss.so:	$(LIBBSSOBJS) $(API)/bssP.h
		$(LD) -o libbss.so $(LIBBSSOBJS)
		cp libbss.so ./lib

#	-	-	Object modules	-	-	-	-	-

%.o:		$(API)/%.c
		$(CC) -c $<

%.o:		$(TEST)/%.c
		$(CC) -c $<
