API = ../library
INCL = ../include
ICI_INCL = ../../ici/include
LTP_INCL = ../../ltp/include
BSSP_INCL = ../../bssp/include
BLOOM_INCL = ../../ici/libbloom-master
ICI_LIB = ../../ici/x86_64-linux/lib
LTP_LIB = ../../ltp/x86_64-linux/lib
DGR_LIB = ../../dgr/x86_64-linux/lib
BSSP_LIB = ../../bssp/x86_64-linux/lib
BLOOM_LIB = ../../ici/libbloom-master/build

# BPSec implementation toggle (inherited from root, overridable locally).
USING_BSL ?= 0

ifeq ($(USING_BSL),1)
BSL_HOME ?= ../../external/BSL/testroot/usr
BSL_SRC = ../../external/BSL/src
BSL_BUILD = ../../external/BSL/build/default/src
BSL_LIB = $(BSL_HOME)/lib
BSL_LIBDIR = -L$(BSL_LIB)
BSL_INCLUDE = $(BSL_HOME)/include/bsl
BSL_INCL = -I$(BSL_SRC) -I$(BSL_BUILD) -I$(BSL_INCLUDE) -I$(BSL_INCLUDE)/policy_provider -I$(BSL_INCLUDE)/security_context -I$(BSL_INCLUDE)/ION_integration -I$(BSL_HOME)/include/m-lib
else
BSL_HOME =
BSL_SRC =
BSL_BUILD =
BSL_LIB =
BSL_LIBDIR =
BSL_INCLUDE =
BSL_INCL =
endif

UTILS = ../utils
TEST = ../test
DAEMON = ../daemon
CGR = ../cgr
IPN = ../ipn
IMC = ../imc
BSSP = ../bssp
DTN2 = ../dtn2
LTP = ../ltp
TCP = ../tcp
STCP = ../stcp
DGR = ../dgr
BRS = ../brs
UDP = ../udp
SPP = ../spp
BIBE = ../bibe
IPND = ../ipnd
SAGA = ../saga
BPSEC = ../bpsec
METADATA = ../metadata
FILE = ../file
BSL = ../bsl
UNIBO_CGR = 0
# UNIBO_CGR = 1

# OPT = -O -D__linux__
OPT = -g -Wall -Werror -D__linux__ -fPIC -DSPACE_ORDER=3 -DENABLE_IMC -DBPSEC -DBP_EXTENDED
# OPT = -g -Wall -Werror -D__linux__ -fPIC -DSPACE_ORDER=3 -DENABLE_IMC -DBPSEC -DUNIBO_CGR -DUNIBO_CGR_ENH_WITHOUT_EXP_EXTENSIONS
CC = gcc $(CPPFLAGS) $(OPT) $(ADD_FLAGS) -I$(METADATA) -I$(IPN) -I$(IMC) -I$(SAGA) -I$(DTN2) -I$(API) -I$(API)/ext -I$(API)/ext/pnb -I$(API)/ext/bpq -I$(API)/ext/meb -I$(API)/ext/bae -I$(API)/ext/hcb -I$(API)/ext/cteb -I$(API)/ext/creb -I$(API)/ext/bpsec -I$(API)/ext/snw -I$(API)/ext/imc -I$(BSL) $(BSL_INCL) -I$(BIBE) -I$(BPSEC)/instr -I$(BPSEC)/policy -I$(BPSEC)/sci -I$(BPSEC)/utils -I$(STCP) -I$(UDP) -I$(INCL) -I$(ROOT)/include -I$(ICI_INCL) -I../../ici/library -I../../ici/crypto -I../../ici/crypto/NULL_SUITES -I$(LTP_INCL) -I../../dgr/include -I$(BSSP_INCL) -I$(BLOOM_INCL) -L$(ICI_LIB) -L$(LTP_LIB) -L$(DGR_LIB) -L$(BSSP_LIB) -L$(BLOOM_LIB) $(BSL_LIBDIR)
LDFLAGS = -fPIC -shared
LD = gcc $(LDFLAGS)

PUBINCLS = \
	$(INCL)/bp.h

BPINCLS = \
	$(API)/bpP.h \
	$(SAGA)/saga.h \
	$(IPN)/ipnfw.h \
	$(IMC)/imcfw.h \
	$(BSSP)/bsspcla.h \
	$(DTN2)/dtn2fw.h \
	$(BRS)/brscla.h \
	$(UDP)/udpcla.h \
	$(STCP)/stcpcla.h \
	$(LTP)/ltpcla.h \
	$(INCL)/eureka.h \
	$(BSL)/bsl.h \
	$(BPSEC)/sci/sci.h \
	$(BPSEC)/sci/ion_test_sc.h \
	$(BPSEC)/sci/bib_hmac_sha2_sc.h \
	$(BPSEC)/sci/bcb_aes_gcm_sc.h \
	$(BPSEC)/sci/rfc9173_utils.h \
	$(BPSEC)/utils/bpsec_util.h \
	$(BPSEC)/utils/bpsec_asb.h \
	$(BPSEC)/instr/bpsec_instr.h \
	$(BPSEC)/policy/bpsec_policy.h \
	$(BPSEC)/policy/bpsec_policy_eventset.h \
	$(BPSEC)/policy/bpsec_policy_event.h \
	$(BPSEC)/policy/bpsec_policy_rule.h
# $(BSL)/bsl.h will be added when USING_BSL=1

BPLIBS = \
	libbp.so \
	libcgr.so \
	libstcpcla.so \
	libudpcla.so \
	libsppcla.so \
	libmetadata.so

BPPOBJS_BASE = libbpP.o libipnfw.o libimcfw.o libdtn2fw.o bibe.o eureka.o saga.o bei.o pnb.o bpq.o meb.o bae.o hcb.o cteb.o creb.o cbr.o snw.o imc.o bpsec_util.o bpsec_asb.o bcb_aes_gcm_sc.o bib_hmac_sha2_sc.o ion_test_sc.o rfc9173_utils.o sc_util.o sc_value.o sci.o sci_valmap.o bpsec_instr.o

ifeq ($(USING_BSL),1)
BPPOBJS = $(BPPOBJS_BASE) bsl.o ionpatch.o
else
BPPOBJS = $(BPPOBJS_BASE) bib.o bcb.o bpsec_policy.o bpsec_policy_event.o bpsec_policy_eventset.o bpsec_policy_rule.o
endif

IPNDOBJS = ipnd.o beacon.o helper.o bpa.o

CGROBJS = libcgr.o
# CGROBJS = libcgr.o interface_cgr_ion.o commonFunctions.o list.o log.o rbt.o scalar.o general_functions_ported_from_ion.o contacts.o ranges.o nodes.o contactPlan.o routes.o phase_one.o phase_two.o phase_three.o cgr.o msr.o msr_utils.o bundles.o time.o

ifeq ($(USING_BSL),1)
LBSL = -lbsl_crypto -lbsl_default_sc -lbsl_dynamic -lbsl_front -lbsl_mock_bpa -lbsl_sample_pp -lqcbor -ljansson
else
LBSL =
endif

LBP = -lbp $(LBSL)

RUNTIMES_BASE = bpadmin bpsink bpsource bpdriver bpecho bpcounter bpsendfile bprecvfile bpsendtest bprecvtest bpclock bptransit bpclm ipnadmin ipnfw ipnadminep dtn2admin dtn2fw dtn2adminep tcpcli tcpclo stcpcli stcpclo brsscla brsccla udpcli udpclo sppcli sppclo dgrcli dgrclo ltpcli ltpclo lgsend lgagent bptrace bpstats bplist bpcancel hmackeys bping bpstats2 bpchat imcfw imcadminep bsspcli bsspclo bibeclo bibeadmin bpnmtest ipnd cgrfetch bpcrash bpcrash_hard bpinspect cpsd sendfile recvfile bptracker bpwatch filecli fileclo

ifeq ($(USING_BSL),1)
RUNTIMES = $(RUNTIMES_BASE)
else
RUNTIMES = $(RUNTIMES_BASE) bpsecadmin
endif

ALL = check $(BPLIBS) $(RUNTIMES)

all:		$(ALL)

check:		$(BPINCLS) $(PUBINCLS)
		rm -f *.o
		touch check
		mkdir -p lib
		mkdir -p bin

clean:
		rm -f *.o
		rm -f *.so
		rm -f $(ALL)
		rm -f ./lib/*
		rm -f ./bin/*

install:
		cp ../include/* $(ROOT)/include
		cp lib/* $(ROOT)/lib
		cp bin/* $(ROOT)/bin

uninstall:
		for file in $(BPLIBS); \
			do rm $(ROOT)/lib/$(notdir $$file); done
		rm $(ROOT)/include/eureka.h
		for file in $(PUBINCLS); \
			do rm $(ROOT)/include/$(notdir $$file); done
		for file in $(RUNTIMES); \
			do rm $(ROOT)/bin/$(notdir $$file); done

#	-	-	Daemon executables	-	-	-	-

bpclock:	bpclock.o $(BPLIBS)
		$(CC) -o bpclock bpclock.o -L./lib -L$(ROOT)/lib $(LBP) -lici -lpthread -lm
		cp bpclock ./bin

bptransit:	bptransit.o $(BPLIBS)
		$(CC) -o bptransit bptransit.o -L./lib -L$(ROOT)/lib $(LBP) -lici -lpthread -lm
		cp bptransit ./bin

bpclm:		bpclm.o $(BPLIBS)
		$(CC) -o bpclm bpclm.o -L./lib -L$(ROOT)/lib $(LBP) -lici -lpthread -lm
		cp bpclm ./bin

cpsd:		cpsd.o $(BPLIBS)
		$(CC) -o cpsd cpsd.o -L./lib -L$(ROOT)/lib $(LBP) -lici -lpthread -lm
		cp cpsd ./bin

#	-	-	Utility executables	-	-	-	-

bpadmin.o: CPPFLAGS += -DCSI_SUITE_NAME="\"NULL Suites"\"

bpadmin:	bpadmin.o $(BPLIBS)
		$(CC) -o bpadmin bpadmin.o -L./lib -L$(ROOT)/lib $(LBP) -lici -lpthread -lm
		cp bpadmin ./bin

bibeadmin:	bibeadmin.o $(BPLIBS)
		$(CC) -o bibeadmin bibeadmin.o -L./lib -L$(ROOT)/lib $(LBP) -lici -lpthread -lm
		cp bibeadmin ./bin

bpsecadmin:	bpsecadmin.o bpsecadmin_config.o jsmn.o $(BPLIBS)
		$(CC) -o bpsecadmin bpsecadmin.o bpsecadmin_config.o jsmn.o -L./lib -L$(ROOT)/lib $(LBP) -lici -lpthread -lm
		cp bpsecadmin ./bin

ipnadmin:	ipnadmin.o $(BPLIBS) libbp.so
		$(CC) -o ipnadmin ipnadmin.o -L./lib -L$(ROOT)/lib $(LBP) -lici -lpthread -lm
		cp ipnadmin ./bin

dtn2admin:	dtn2admin.o $(BPLIBS) libbp.so
		$(CC) -o dtn2admin dtn2admin.o -L./lib -L$(ROOT)/lib $(LBP) -lici -lpthread -lm
		cp dtn2admin ./bin

lgsend:		lgsend.o $(BPLIBS)
		$(CC) -o lgsend lgsend.o -L./lib -L$(ROOT)/lib $(LBP) -lici -lpthread -lm
		cp lgsend ./bin

lgagent:	lgagent.o $(BPLIBS)
		$(CC) -o lgagent lgagent.o -L./lib -L$(ROOT)/lib $(LBP) -lici -lpthread -lm
		cp lgagent ./bin

bptrace:	bptrace.o $(BPLIBS)
		$(CC) -o bptrace bptrace.o -L./lib -L$(ROOT)/lib $(LBP) -lici -lpthread -lm
		cp bptrace ./bin

bpstats:	bpstats.o $(BPLIBS)
		$(CC) -o bpstats bpstats.o -L./lib -L$(ROOT)/lib $(LBP) -lici -lpthread -lm
		cp bpstats ./bin

bpstats2:	bpstats2.o $(BPLIBS)
		$(CC) -o bpstats2 bpstats2.o -L./lib -L$(ROOT)/lib $(LBP) -lici -lpthread -lm
		cp bpstats2 ./bin

bping:		bping.o $(BPLIBS)
		$(CC) -o bping bping.o -L./lib -L$(ROOT)/lib $(LBP) -lici -lpthread -lm
		cp bping ./bin

bpchat:		bpchat.o $(BPLIBS)
		$(CC) -o bpchat bpchat.o -L./lib -L$(ROOT)/lib $(LBP) -lici -lpthread -lm
		cp bpchat ./bin

bplist:		bplist.o $(BPLIBS)
		$(CC) -o bplist bplist.o -L./lib -L$(ROOT)/lib $(LBP) -lici -lpthread -lm
		cp bplist ./bin

bpcancel:	bpcancel.o $(BPLIBS)
		$(CC) -o bpcancel bpcancel.o -L./lib -L$(ROOT)/lib $(LBP) -lici -lpthread -lm
		cp bpcancel ./bin

hmackeys:	hmackeys.o $(BPLIBS)
		$(CC) -o hmackeys hmackeys.o -L$(ROOT)/lib -lici -lpthread -lm
		cp hmackeys ./bin

cgrfetch:	cgrfetch.o $(BPLIBS)
		$(CC) -o cgrfetch cgrfetch.o -L./lib -L$(ROOT)/lib -lcgr $(LBP) -lici -lpthread -lm
		cp cgrfetch ./bin

bpcrash:	bpcrash.o
		$(CC) -o bpcrash bpcrash.o -L./lib -L$(ROOT)/lib $(LBP) -lici -lpthread -lm
		cp bpcrash ./bin

bptracker:	bptracker.o $(BPLIBS)
		$(CC) -o bptracker bptracker.o -L./lib -L$(ROOT)/lib $(LBP) -lici -lpthread -lm
		cp bptracker ./bin

bpwatch:	bpwatch.o $(BPLIBS)
		$(CC) -o bpwatch bpwatch.o -L./lib -L$(ROOT)/lib $(LBP) -lici -lpthread -lm
		cp bpwatch ./bin

bpinspect:	bpinspect.o bpinspect_data.o bpinspect_filter.o bpinspect_ops.o $(BPLIBS)
		$(CC) -o bpinspect bpinspect.o bpinspect_data.o bpinspect_filter.o bpinspect_ops.o -L./lib -L$(ROOT)/lib $(LBP) -lici -lpthread -lm
		cp bpinspect ./bin

bpcrash_hard:	bpcrash_hard.o $(BPLIBS)
		$(CC) -o bpcrash_hard bpcrash_hard.o -L./lib -L$(ROOT)/lib $(LBP) -lici -lpthread -lm
		cp bpcrash_hard ./bin

#	-	-	IPN executables	-	-	-	-	-

ipnfw:		ipnfw.o cbdedup.o $(BPLIBS) libbp.so libcgr.so
		$(CC) -o ipnfw ipnfw.o cbdedup.o -L./lib -L$(ROOT)/lib -lcgr $(LBP) -lici -lpthread -lm
		cp ipnfw ./bin

ipnadminep:	ipnadminep.o $(BPLIBS) libbp.so
		$(CC) -o ipnadminep ipnadminep.o -L./lib -L$(ROOT)/lib $(LBP) -lici -lpthread -lm
		cp ipnadminep ./bin

#	-	-	IMC executables	-	-	-	-	-

imcfw:		imcfw.o $(BPLIBS) libbp.so libcgr.so
		$(CC) -o imcfw imcfw.o -L./lib -L$(ROOT)/lib -lcgr $(LBP) -lici -lpthread -lm
		cp imcfw ./bin

imcadminep:	imcadminep.o $(BPLIBS) libbp.so
		$(CC) -o imcadminep imcadminep.o -L./lib -L$(ROOT)/lib $(LBP) -lici -lpthread -lm
		cp imcadminep ./bin

#	-	-	DTN2 executables	-	-	-	-

dtn2fw:		dtn2fw.o $(BPLIBS) libbp.so
		$(CC) -o dtn2fw dtn2fw.o -L./lib -L$(ROOT)/lib $(LBP) -lici -lpthread -lm
		cp dtn2fw ./bin

dtn2adminep:	dtn2adminep.o $(BPLIBS) libbp.so
		$(CC) -o dtn2adminep dtn2adminep.o -L./lib -L$(ROOT)/lib $(LBP) -lici -lpthread -lm
		cp dtn2adminep ./bin

#	-	-	LTP executables	-	-	-	-	-

ltpcli:		ltpcli.o $(BPLIBS)
		$(CC) -o ltpcli ltpcli.o -L./lib -L$(ROOT)/lib $(LBP) -lltp -lici -lpthread -lm
		cp ltpcli ./bin

ltpclo:		ltpclo.o $(BPLIBS)
		$(CC) -o ltpclo ltpclo.o -L./lib -L$(ROOT)/lib $(LBP) -lltp -lici -lpthread -lm
		cp ltpclo ./bin

#	-	-	TCP executables	-	-	-	-	-

tcpcli:		tcpcli.o $(BPLIBS)
		$(CC) -o tcpcli tcpcli.o -L./lib -L$(ROOT)/lib $(LBP) -lici -lpthread -lm
		cp tcpcli ./bin

tcpclo:		tcpclo.o $(BPLIBS)
		$(CC) -o tcpclo tcpclo.o -L./lib -L$(ROOT)/lib $(LBP) -lici -lpthread -lm
		cp tcpclo ./bin

#	-	-	File CLA executables	-	-	-	-

filecli:	filecli.o libfilecla.o $(BPLIBS)
		$(CC) -o filecli filecli.o libfilecla.o -L./lib -L$(ROOT)/lib $(LBP) -lici -lpthread -lm
		cp filecli ./bin

fileclo:	fileclo.o libfilecla.o $(BPLIBS)
		$(CC) -o fileclo fileclo.o libfilecla.o -L./lib -L$(ROOT)/lib $(LBP) -lici -lpthread -lm
		cp fileclo ./bin

#	-	-	STCP executables	-	-	-	-

stcpcli:	stcpcli.o $(BPLIBS) libstcpcla.so
		$(CC) -o stcpcli stcpcli.o -L./lib -L$(ROOT)/lib -lstcpcla $(LBP) -lici -lpthread -lm
		cp stcpcli ./bin

stcpclo:	stcpclo.o $(BPLIBS) libstcpcla.so
		$(CC) -o stcpclo stcpclo.o -L./lib -L$(ROOT)/lib -lstcpcla $(LBP) -lici -lpthread -lm
		cp stcpclo ./bin

#	-	-	UDP executables	-	-	-	-	-

udpcli:		udpcli.o $(BPLIBS) libudpcla.so
		$(CC) -o udpcli udpcli.o -L./lib -L$(ROOT)/lib -ludpcla $(LBP) -lici -lpthread -lm
		cp udpcli ./bin

udpclo:		udpclo.o $(BPLIBS) libudpcla.so
		$(CC) -o udpclo udpclo.o -L./lib -L$(ROOT)/lib -ludpcla $(LBP) -lici -lpthread -lm
		cp udpclo ./bin

#	-	-	SPP executables	-	-	-	-

sppcli:		sppcli.o $(BPLIBS) libsppcla.so
		$(CC) -o sppcli sppcli.o -L./lib -L$(ROOT)/lib -lsppcla $(LBP) -lici -lpthread -lm
		cp sppcli ./bin

sppclo:		sppclo.o $(BPLIBS) libsppcla.so
		$(CC) -o sppclo sppclo.o -L./lib -L$(ROOT)/lib -lsppcla $(LBP) -lici -lpthread -lm
		cp sppclo ./bin

#	-	-	BSSP executables	-	-	-	-

bsspcli:	bsspcli.o $(BPLIBS)
		$(CC) -o bsspcli bsspcli.o -L./lib -L$(ROOT)/lib $(LBP) -lbssp -lici -lpthread -lm
		cp bsspcli ./bin

bsspclo:	bsspclo.o $(BPLIBS)
		$(CC) -o bsspclo bsspclo.o -L./lib -L$(ROOT)/lib $(LBP) -lbssp -lici -lpthread -lm
		cp bsspclo ./bin


dgrcli:		dgrcli.o $(BPLIBS)
		$(CC) -o dgrcli dgrcli.o -L./lib -L$(ROOT)/lib $(LBP) -ldgr -lici -lpthread -lm
		cp dgrcli ./bin

dgrclo:		dgrclo.o $(BPLIBS)
		$(CC) -o dgrclo dgrclo.o -L./lib -L$(ROOT)/lib $(LBP) -ldgr -lici -lpthread -lm
		cp dgrclo ./bin

#	-	-	BRS executables	-	-	-	-

brsscla:	brsscla.o $(BPLIBS) libstcpcla.so
		$(CC) -o brsscla brsscla.o -L./lib -L$(ROOT)/lib -lstcpcla $(LBP) -lici -lpthread -lm
		cp brsscla ./bin

brsccla:	brsccla.o $(BPLIBS) libstcpcla.so
		$(CC) -o brsccla brsccla.o -L./lib -L$(ROOT)/lib -lstcpcla $(LBP) -lici -lpthread -lm
		cp brsccla ./bin

#	-	-	BIBE executable	-	-	-	-	-

bibeclo:	bibeclo.o $(BPLIBS)
		$(CC) -o bibeclo bibeclo.o -L./lib -L$(ROOT)/lib $(LBP) -lici -lpthread -lm
		cp bibeclo ./bin

#	-	-	IPND executable	-	-	-	-	-

ipnd:		$(IPNDOBJS) $(BPLIBS)
		$(CC) -o ipnd $(IPNDOBJS) -L./lib -L$(ROOT)/lib $(LBP) -lici -lbloom -lpthread -lm
		cp ipnd ./bin

#	-	-	Test executables	-	-	-	-

bpsource:	bpsource.o libbp.so $(BPLIBS)
		$(CC) -o bpsource bpsource.o -L./lib -L$(ROOT)/lib $(LBP) -lici -lpthread -lm
		cp bpsource ./bin

bpsink:		bpsink.o libbp.so $(BPLIBS)
		$(CC) -o bpsink bpsink.o -L./lib -L$(ROOT)/lib $(LBP) -lici -lpthread -lm
		cp bpsink ./bin

bpdriver:	bpdriver.o libbp.so $(BPLIBS)
		$(CC) -o bpdriver bpdriver.o -L./lib -L$(ROOT)/lib $(LBP) -lici -lpthread -lm
		cp bpdriver ./bin

bpecho:		bpecho.o libbp.so $(BPLIBS)
		$(CC) -o bpecho bpecho.o -L./lib -L$(ROOT)/lib $(LBP) -lici -lpthread -lm
		cp bpecho ./bin

bpcounter:	bpcounter.o libbp.so $(BPLIBS)
		$(CC) -o bpcounter bpcounter.o -L./lib -L$(ROOT)/lib $(LBP) -lici -lpthread -lm
		cp bpcounter ./bin

bpsendfile:	bpsendfile.o libbp.so $(BPLIBS)
		$(CC) -o bpsendfile bpsendfile.o -L./lib -L$(ROOT)/lib $(LBP) -lici -lpthread -lm
		cp bpsendfile ./bin

bpsendtest:	bpsendtest.o libbp.so $(BPLIBS)
		$(CC) -o bpsendtest bpsendtest.o -L./lib -L$(ROOT)/lib $(LBP) -lici -lpthread -lm
		cp bpsendtest ./bin

bprecvfile:	bprecvfile.o libbp.so $(BPLIBS)
		$(CC) -o bprecvfile bprecvfile.o -L./lib -L$(ROOT)/lib $(LBP) -lici -lpthread -lm
		cp bprecvfile ./bin

bprecvtest:	bprecvtest.o libbp.so $(BPLIBS)
		$(CC) -o bprecvtest bprecvtest.o -L./lib -L$(ROOT)/lib $(LBP) -lici -lpthread -lm
		cp bprecvtest ./bin

bpnmtest:	bpnmtest.o libbp.so $(BPLIBS)
		$(CC) -o bpnmtest bpnmtest.o -L./lib -L$(ROOT)/lib $(LBP) -lici -lpthread -lm
		cp bpnmtest ./bin

sendfile:	sendfile.o libbp.so $(BPLIBS)
		$(CC) -o sendfile sendfile.o -L./lib -L$(ROOT)/lib $(LBP) -lici -lmetadata -lpthread -lm
		cp sendfile ./bin

recvfile:	recvfile.o libbp.so $(BPLIBS)
		$(CC) -o recvfile recvfile.o -L./lib -L$(ROOT)/lib $(LBP) -lici -lmetadata -lpthread -lm
		cp recvfile ./bin

#	-	-	Libraries	-	-	-	-	-

libbp.so:	libbp.o $(BPPOBJS) libbpnm.o
		$(LD) -o libbp.so libbp.o $(BPPOBJS) libbpnm.o $(BSL_LIBDIR) $(LBSL)
		cp libbp.so ./lib

libcgr.so:	$(CGROBJS)
		$(LD) -o libcgr.so $(CGROBJS)
		cp libcgr.so ./lib

libstcpcla.so:	libstcpcla.o
		$(LD) -o libstcpcla.so libstcpcla.o
		cp libstcpcla.so ./lib

libudpcla.so:	libudpcla.o
		$(LD) -o libudpcla.so libudpcla.o
		cp libudpcla.so ./lib

libsppcla.so:	libsppcla.o
		$(LD) -o libsppcla.so libsppcla.o
		cp libsppcla.so ./lib

libmetadata.so:	metadata.o
		$(LD) -o libmetadata.so metadata.o
		cp libmetadata.so ./lib

#	-	-	Object modules	-	-	-	-	-

%.o:		$(API)/%.c
		$(CC) -c $<

%.o:		$(API)/ext/bpq/%.c
		$(CC) -c $<

%.o:		$(API)/ext/meb/%.c
		$(CC) -c $<

%.o:		$(API)/ext/bae/%.c
		$(CC) -c $<

%.o:		$(API)/ext/hcb/%.c
		$(CC) -c $<

%.o:		$(API)/ext/bpsec/%.c
		$(CC) -c $<

%.o:		$(API)/ext/pnb/%.c
		$(CC) -c $<

%.o:		$(API)/ext/cteb/%.c
		$(CC) -c $<

%.o:		$(API)/ext/creb/%.c
		$(CC) -c $<

%.o:		$(BPSEC)/instr/%.c
		$(CC) -c $<

%.o:		$(BPSEC)/policy/%.c
		$(CC) -c $<

%.o:		$(BPSEC)/sci/%.c
		$(CC) -c $<

%.o:		$(BPSEC)/utils/%.c
		$(CC) -c $<

%.o:		$(TEST)/%.c
		$(CC) -c $<

%.o:		$(UTILS)/%.c
		$(CC) -c $<

%.o:		$(DAEMON)/%.c
		$(CC) -c $<

%.o:		$(CGR)/%.c
		$(CC) -c $<

ifdef UNIBO_CGR
%.o:		$(CGR)/Unibo-CGR/ion_bpv7/interface/%.c
		$(CC) -c $<

%.o:		$(CGR)/Unibo-CGR/ion_bpv7/interface/utility_functions_from_ion/%.c
		$(CC) -c $<

%.o:		$(CGR)/Unibo-CGR/core/library/%.c
		$(CC) -c $<

%.o:		$(CGR)/Unibo-CGR/core/library/list/%.c
		$(CC) -c $<

%.o:		$(CGR)/Unibo-CGR/core/library/log/%.c
		$(CC) -c $<

%.o:		$(CGR)/Unibo-CGR/core/library_from_ion/rbt/%.c
		$(CC) -c $<

%.o:		$(CGR)/Unibo-CGR/core/library_from_ion/scalar/%.c
		$(CC) -c $<

%.o:		$(CGR)/Unibo-CGR/core/contact_plan/%.c
		$(CC) -c $<

%.o:		$(CGR)/Unibo-CGR/core/contact_plan/contacts/%.c
		$(CC) -c $<

%.o:		$(CGR)/Unibo-CGR/core/contact_plan/ranges/%.c
		$(CC) -c $<

%.o:		$(CGR)/Unibo-CGR/core/contact_plan/nodes/%.c
		$(CC) -c $<

%.o:		$(CGR)/Unibo-CGR/core/routes/%.c
		$(CC) -c $<

%.o:		$(CGR)/Unibo-CGR/core/cgr/%.c
		$(CC) -c $<

%.o:		$(CGR)/Unibo-CGR/core/msr/%.c
		$(CC) -c $<

%.o:		$(CGR)/Unibo-CGR/core/bundles/%.c
		$(CC) -c $<

%.o:		$(CGR)/Unibo-CGR/core/time_analysis/%.c
		$(CC) -c $<
endif

%.o:		$(IPN)/%.c
		$(CC) -c $<

%.o:		$(IMC)/%.c
		$(CC) -c $<

%.o:		$(BSSP)/%.c
		$(CC) -c $<

%.o:		$(DTN2)/%.c
		$(CC) -c $<

%.o:		$(LTP)/%.c
		$(CC) -c $<

%.o:		$(STCP)/%.c
		$(CC) -c $<

%.o:		$(TCP)/%.c
		$(CC) -c $<

%.o:		$(UDP)/%.c
		$(CC) -c $<

%.o:		$(SPP)/%.c
		$(CC) -c $<

#		$(CC) -c $<

%.o:		$(BRS)/%.c
		$(CC) -c $<

%.o:		$(DGR)/%.c
		$(CC) -c $<

%.o:		$(BIBE)/%.c
		$(CC) -c $<

%.o:		$(FILE)/%.c
		$(CC) -c $<

%.o:		$(API)/ext/snw/%.c
		$(CC) -c $<

%.o:		$(API)/ext/imc/%.c
		$(CC) -c $<

%.o:		$(IPND)/%.c
		$(CC) -I$(IPND) -c $<

%.o:		$(SAGA)/%.c
		$(CC) -I$(SAGA) -c $<

%.o:		$(METADATA)/%.c
		$(CC) -I$(METADATA) -c $<

%.o:		$(API)/ext/cteb/%.c
		$(CC) -c $<

%.o:		$(API)/ext/creb/%.c
		$(CC) -c $<

%.o:		$(BSL)/%.c
		$(CC) -I$(BSL) -c $<
