/****************************************************************************
 **
 ** File Name: ./mgr/adm_ltpAgent_mgr.c
 **
 ** Description: 
 **
 ** Notes: 
 **
 ** Assumptions: 
 **
 ** Modification History: 
 **  MM/DD/YY  AUTHOR           DESCRIPTION
 **  --------  --------------   ------------------------------------------------
 **  2017-09-24  AUTO           Auto generated c file 
 **
****************************************************************************/
#include "ion.h"
#include "lyst.h"
#include "platform.h"

#include "../shared/adm/adm_LtpAgent.h"
#include "../shared/utils/utils.h"
#include "../shared/primitives/def.h"
#include "../shared/primitives/nn.h"
#include "../shared/primitives/report.h"
#include "../shared/primitives/blob.h"
#include "nm_mgr_names.h"
#include "nm_mgr_ui.h"
#define _HAVE_LTPAGENT_ADM_
#ifdef _HAVE_LTPAGENT_ADM_
void adm_LtpAgent_init()
{
	adm_LtpAgent_init_edd();
	adm_LtpAgent_init_variables();
	adm_LtpAgent_init_controls();
	adm_LtpAgent_init_constants();
	adm_LtpAgent_init_macros();
	adm_LtpAgent_init_metadata();
	adm_LtpAgent_init_ops();
	adm_LtpAgent_init_reports();
}

void adm_LtpAgent_init_edd()
{
	adm_add_edd(ADM_LTPAGENT_EDD_SPANREMOTEENGINENBR_MID, AMP_TYPE_UINT, 0, NULL, NULL, NULL);
	names_add_name("ADM_LTPAGENT_EDD_SPANREMOTEENGINENBR_MID", "The remote engine number of this LTP span.", ADM_LTPAGENT, ADM_LTPAGENT_EDD_SPANREMOTEENGINENBR_MID);
	UI_ADD_PARMSPEC_1(ADM_LTPAGENT_EDD_SPANREMOTEENGINENBR_MID, "spanId", AMP_TYPE_UINT);

	adm_add_edd(ADM_LTPAGENT_EDD_SPANCUREXPTSESS_MID, AMP_TYPE_UINT, 0, NULL, NULL, NULL);
	names_add_name("ADM_LTPAGENT_EDD_SPANCUREXPTSESS_MID", "The remote engine number of this LTP engines.", ADM_LTPAGENT, ADM_LTPAGENT_EDD_SPANCUREXPTSESS_MID);
	UI_ADD_PARMSPEC_1(ADM_LTPAGENT_EDD_SPANCUREXPTSESS_MID, "spanId", AMP_TYPE_UINT);

	adm_add_edd(ADM_LTPAGENT_EDD_SPANCUROUTSEG_MID, AMP_TYPE_UINT, 0, NULL, NULL, NULL);
	names_add_name("ADM_LTPAGENT_EDD_SPANCUROUTSEG_MID", "The current number of outbound segments for this span.", ADM_LTPAGENT, ADM_LTPAGENT_EDD_SPANCUROUTSEG_MID);
	UI_ADD_PARMSPEC_1(ADM_LTPAGENT_EDD_SPANCUROUTSEG_MID, "spanId", AMP_TYPE_UINT);

	adm_add_edd(ADM_LTPAGENT_EDD_SPANCURIMPSESS_MID, AMP_TYPE_UINT, 0, NULL, NULL, NULL);
	names_add_name("ADM_LTPAGENT_EDD_SPANCURIMPSESS_MID", "The current number of import sessions for this span.", ADM_LTPAGENT, ADM_LTPAGENT_EDD_SPANCURIMPSESS_MID);
	UI_ADD_PARMSPEC_1(ADM_LTPAGENT_EDD_SPANCURIMPSESS_MID, "spanId", AMP_TYPE_UINT);

	adm_add_edd(ADM_LTPAGENT_EDD_SPANCURINSEG_MID, AMP_TYPE_UINT, 0, NULL, NULL, NULL);
	names_add_name("ADM_LTPAGENT_EDD_SPANCURINSEG_MID", "The current number of inbound segments for this span.", ADM_LTPAGENT, ADM_LTPAGENT_EDD_SPANCURINSEG_MID);
	UI_ADD_PARMSPEC_1(ADM_LTPAGENT_EDD_SPANCURINSEG_MID, "spanId", AMP_TYPE_UINT);

	adm_add_edd(ADM_LTPAGENT_EDD_SPANRESETTIME_MID, AMP_TYPE_UVAST, 0, NULL, NULL, NULL);
	names_add_name("ADM_LTPAGENT_EDD_SPANRESETTIME_MID", "The last time the span counters were reset.", ADM_LTPAGENT, ADM_LTPAGENT_EDD_SPANRESETTIME_MID);
	UI_ADD_PARMSPEC_1(ADM_LTPAGENT_EDD_SPANRESETTIME_MID, "spanId", AMP_TYPE_UINT);

	adm_add_edd(ADM_LTPAGENT_EDD_SPANOUTSEGQCNT_MID, AMP_TYPE_UINT, 0, NULL, NULL, NULL);
	names_add_name("ADM_LTPAGENT_EDD_SPANOUTSEGQCNT_MID", "The output segment queued count for the span.", ADM_LTPAGENT, ADM_LTPAGENT_EDD_SPANOUTSEGQCNT_MID);
	UI_ADD_PARMSPEC_1(ADM_LTPAGENT_EDD_SPANOUTSEGQCNT_MID, "spanId", AMP_TYPE_UINT);

	adm_add_edd(ADM_LTPAGENT_EDD_SPANOUTSEGQBYTES_MID, AMP_TYPE_UINT, 0, NULL, NULL, NULL);
	names_add_name("ADM_LTPAGENT_EDD_SPANOUTSEGQBYTES_MID", "The output segment queued bytes for the span.", ADM_LTPAGENT, ADM_LTPAGENT_EDD_SPANOUTSEGQBYTES_MID);
	UI_ADD_PARMSPEC_1(ADM_LTPAGENT_EDD_SPANOUTSEGQBYTES_MID, "spanId", AMP_TYPE_UINT);

	adm_add_edd(ADM_LTPAGENT_EDD_SPANOUTSEGPOPCNT_MID, AMP_TYPE_UINT, 0, NULL, NULL, NULL);
	names_add_name("ADM_LTPAGENT_EDD_SPANOUTSEGPOPCNT_MID", "The output segment popped count for the span.", ADM_LTPAGENT, ADM_LTPAGENT_EDD_SPANOUTSEGPOPCNT_MID);
	UI_ADD_PARMSPEC_1(ADM_LTPAGENT_EDD_SPANOUTSEGPOPCNT_MID, "spanId", AMP_TYPE_UINT);

	adm_add_edd(ADM_LTPAGENT_EDD_SPANOUTSEGPOPBYTES_MID, AMP_TYPE_UINT, 0, NULL, NULL, NULL);
	names_add_name("ADM_LTPAGENT_EDD_SPANOUTSEGPOPBYTES_MID", "The output segment popped bytes for the span.", ADM_LTPAGENT, ADM_LTPAGENT_EDD_SPANOUTSEGPOPBYTES_MID);
	UI_ADD_PARMSPEC_1(ADM_LTPAGENT_EDD_SPANOUTSEGPOPBYTES_MID, "spanId", AMP_TYPE_UINT);

	adm_add_edd(ADM_LTPAGENT_EDD_SPANOUTCKPTXMITCNT_MID, AMP_TYPE_UINT, 0, NULL, NULL, NULL);
	names_add_name("ADM_LTPAGENT_EDD_SPANOUTCKPTXMITCNT_MID", "The output checkpoint transmit count for the span.", ADM_LTPAGENT, ADM_LTPAGENT_EDD_SPANOUTCKPTXMITCNT_MID);
	UI_ADD_PARMSPEC_1(ADM_LTPAGENT_EDD_SPANOUTCKPTXMITCNT_MID, "spanId", AMP_TYPE_UINT);

	adm_add_edd(ADM_LTPAGENT_EDD_SPANOUTPOSACKRXCNT_MID, AMP_TYPE_UINT, 0, NULL, NULL, NULL);
	names_add_name("ADM_LTPAGENT_EDD_SPANOUTPOSACKRXCNT_MID", "The output positive acknolwedgement received count for the span.", ADM_LTPAGENT, ADM_LTPAGENT_EDD_SPANOUTPOSACKRXCNT_MID);
	UI_ADD_PARMSPEC_1(ADM_LTPAGENT_EDD_SPANOUTPOSACKRXCNT_MID, "spanId", AMP_TYPE_UINT);

	adm_add_edd(ADM_LTPAGENT_EDD_SPANOUTNEGACKRXCNT_MID, AMP_TYPE_UINT, 0, NULL, NULL, NULL);
	names_add_name("ADM_LTPAGENT_EDD_SPANOUTNEGACKRXCNT_MID", "The output negative acknolwedgement received count for the span.", ADM_LTPAGENT, ADM_LTPAGENT_EDD_SPANOUTNEGACKRXCNT_MID);
	UI_ADD_PARMSPEC_1(ADM_LTPAGENT_EDD_SPANOUTNEGACKRXCNT_MID, "spanId", AMP_TYPE_UINT);

	adm_add_edd(ADM_LTPAGENT_EDD_SPANOUTCANCELRXCNT_MID, AMP_TYPE_UINT, 0, NULL, NULL, NULL);
	names_add_name("ADM_LTPAGENT_EDD_SPANOUTCANCELRXCNT_MID", "The output cancelled received count for the span.", ADM_LTPAGENT, ADM_LTPAGENT_EDD_SPANOUTCANCELRXCNT_MID);
	UI_ADD_PARMSPEC_1(ADM_LTPAGENT_EDD_SPANOUTCANCELRXCNT_MID, "spanId", AMP_TYPE_UINT);

	adm_add_edd(ADM_LTPAGENT_EDD_SPANOUTCKPTREXMITCNT_MID, AMP_TYPE_UINT, 0, NULL, NULL, NULL);
	names_add_name("ADM_LTPAGENT_EDD_SPANOUTCKPTREXMITCNT_MID", "The output checkpoint retransmit count for the span.", ADM_LTPAGENT, ADM_LTPAGENT_EDD_SPANOUTCKPTREXMITCNT_MID);
	UI_ADD_PARMSPEC_1(ADM_LTPAGENT_EDD_SPANOUTCKPTREXMITCNT_MID, "spanId", AMP_TYPE_UINT);

	adm_add_edd(ADM_LTPAGENT_EDD_SPANOUTCANCELXMITCNT_MID, AMP_TYPE_UINT, 0, NULL, NULL, NULL);
	names_add_name("ADM_LTPAGENT_EDD_SPANOUTCANCELXMITCNT_MID", "The output cancel retransmit count for the span.", ADM_LTPAGENT, ADM_LTPAGENT_EDD_SPANOUTCANCELXMITCNT_MID);
	UI_ADD_PARMSPEC_1(ADM_LTPAGENT_EDD_SPANOUTCANCELXMITCNT_MID, "spanId", AMP_TYPE_UINT);

	adm_add_edd(ADM_LTPAGENT_EDD_SPANOUTCOMPLETECNT_MID, AMP_TYPE_UINT, 0, NULL, NULL, NULL);
	names_add_name("ADM_LTPAGENT_EDD_SPANOUTCOMPLETECNT_MID", "The output completed count for the span.", ADM_LTPAGENT, ADM_LTPAGENT_EDD_SPANOUTCOMPLETECNT_MID);
	UI_ADD_PARMSPEC_1(ADM_LTPAGENT_EDD_SPANOUTCOMPLETECNT_MID, "spanId", AMP_TYPE_UINT);

	adm_add_edd(ADM_LTPAGENT_EDD_SPANINSEGRXREDCNT_MID, AMP_TYPE_UINT, 0, NULL, NULL, NULL);
	names_add_name("ADM_LTPAGENT_EDD_SPANINSEGRXREDCNT_MID", "The input segment received red count for the span.", ADM_LTPAGENT, ADM_LTPAGENT_EDD_SPANINSEGRXREDCNT_MID);
	UI_ADD_PARMSPEC_1(ADM_LTPAGENT_EDD_SPANINSEGRXREDCNT_MID, "spanId", AMP_TYPE_UINT);

	adm_add_edd(ADM_LTPAGENT_EDD_SPANINSEGRXREDBYTES_MID, AMP_TYPE_UINT, 0, NULL, NULL, NULL);
	names_add_name("ADM_LTPAGENT_EDD_SPANINSEGRXREDBYTES_MID", "The input segment received red bytes for the span.", ADM_LTPAGENT, ADM_LTPAGENT_EDD_SPANINSEGRXREDBYTES_MID);
	UI_ADD_PARMSPEC_1(ADM_LTPAGENT_EDD_SPANINSEGRXREDBYTES_MID, "spanId", AMP_TYPE_UINT);

	adm_add_edd(ADM_LTPAGENT_EDD_SPANINSEGRXGREENCNT_MID, AMP_TYPE_UINT, 0, NULL, NULL, NULL);
	names_add_name("ADM_LTPAGENT_EDD_SPANINSEGRXGREENCNT_MID", "The input segment received green count for the span.", ADM_LTPAGENT, ADM_LTPAGENT_EDD_SPANINSEGRXGREENCNT_MID);
	UI_ADD_PARMSPEC_1(ADM_LTPAGENT_EDD_SPANINSEGRXGREENCNT_MID, "spanId", AMP_TYPE_UINT);

	adm_add_edd(ADM_LTPAGENT_EDD_SPANINSEGRXGREENBYTES_MID, AMP_TYPE_UINT, 0, NULL, NULL, NULL);
	names_add_name("ADM_LTPAGENT_EDD_SPANINSEGRXGREENBYTES_MID", "The input segment received green bytes for the span.", ADM_LTPAGENT, ADM_LTPAGENT_EDD_SPANINSEGRXGREENBYTES_MID);
	UI_ADD_PARMSPEC_1(ADM_LTPAGENT_EDD_SPANINSEGRXGREENBYTES_MID, "spanId", AMP_TYPE_UINT);

	adm_add_edd(ADM_LTPAGENT_EDD_SPANINSEGRXREDUNDANTCNT_MID, AMP_TYPE_UINT, 0, NULL, NULL, NULL);
	names_add_name("ADM_LTPAGENT_EDD_SPANINSEGRXREDUNDANTCNT_MID", "The input segment received redundant count for the span.", ADM_LTPAGENT, ADM_LTPAGENT_EDD_SPANINSEGRXREDUNDANTCNT_MID);
	UI_ADD_PARMSPEC_1(ADM_LTPAGENT_EDD_SPANINSEGRXREDUNDANTCNT_MID, "spanId", AMP_TYPE_UINT);

	adm_add_edd(ADM_LTPAGENT_EDD_SPANINSEGRXREDUNDANTBYTES_MID, AMP_TYPE_UINT, 0, NULL, NULL, NULL);
	names_add_name("ADM_LTPAGENT_EDD_SPANINSEGRXREDUNDANTBYTES_MID", "The input segment received redundant bytes for the span.", ADM_LTPAGENT, ADM_LTPAGENT_EDD_SPANINSEGRXREDUNDANTBYTES_MID);
	UI_ADD_PARMSPEC_1(ADM_LTPAGENT_EDD_SPANINSEGRXREDUNDANTBYTES_MID, "spanId", AMP_TYPE_UINT);

	adm_add_edd(ADM_LTPAGENT_EDD_SPANINSEGRXMALCNT_MID, AMP_TYPE_UINT, 0, NULL, NULL, NULL);
	names_add_name("ADM_LTPAGENT_EDD_SPANINSEGRXMALCNT_MID", "The input segment malformed count for the span.", ADM_LTPAGENT, ADM_LTPAGENT_EDD_SPANINSEGRXMALCNT_MID);
	UI_ADD_PARMSPEC_1(ADM_LTPAGENT_EDD_SPANINSEGRXMALCNT_MID, "spanId", AMP_TYPE_UINT);

	adm_add_edd(ADM_LTPAGENT_EDD_SPANINSEGRXMALBYTES_MID, AMP_TYPE_UINT, 0, NULL, NULL, NULL);
	names_add_name("ADM_LTPAGENT_EDD_SPANINSEGRXMALBYTES_MID", "The input segment malformed bytes for the span.", ADM_LTPAGENT, ADM_LTPAGENT_EDD_SPANINSEGRXMALBYTES_MID);
	UI_ADD_PARMSPEC_1(ADM_LTPAGENT_EDD_SPANINSEGRXMALBYTES_MID, "spanId", AMP_TYPE_UINT);

	adm_add_edd(ADM_LTPAGENT_EDD_SPANINSEGRXUNKSENDCNT_MID, AMP_TYPE_UINT, 0, NULL, NULL, NULL);
	names_add_name("ADM_LTPAGENT_EDD_SPANINSEGRXUNKSENDCNT_MID", "The input segment unknown sender count for the span.", ADM_LTPAGENT, ADM_LTPAGENT_EDD_SPANINSEGRXUNKSENDCNT_MID);
	UI_ADD_PARMSPEC_1(ADM_LTPAGENT_EDD_SPANINSEGRXUNKSENDCNT_MID, "spanId", AMP_TYPE_UINT);

	adm_add_edd(ADM_LTPAGENT_EDD_SPANINSEGRXUNKSENDBYTES_MID, AMP_TYPE_UINT, 0, NULL, NULL, NULL);
	names_add_name("ADM_LTPAGENT_EDD_SPANINSEGRXUNKSENDBYTES_MID", "The input segment unknown sender bytes for the span.", ADM_LTPAGENT, ADM_LTPAGENT_EDD_SPANINSEGRXUNKSENDBYTES_MID);
	UI_ADD_PARMSPEC_1(ADM_LTPAGENT_EDD_SPANINSEGRXUNKSENDBYTES_MID, "spanId", AMP_TYPE_UINT);

	adm_add_edd(ADM_LTPAGENT_EDD_SPANINSEGRXUNKCLIENTCNT_MID, AMP_TYPE_UINT, 0, NULL, NULL, NULL);
	names_add_name("ADM_LTPAGENT_EDD_SPANINSEGRXUNKCLIENTCNT_MID", "The input segment unknown client count for the span.", ADM_LTPAGENT, ADM_LTPAGENT_EDD_SPANINSEGRXUNKCLIENTCNT_MID);
	UI_ADD_PARMSPEC_1(ADM_LTPAGENT_EDD_SPANINSEGRXUNKCLIENTCNT_MID, "spanId", AMP_TYPE_UINT);

	adm_add_edd(ADM_LTPAGENT_EDD_SPANINSEGRXUNKCLIENTBYTES_MID, AMP_TYPE_UINT, 0, NULL, NULL, NULL);
	names_add_name("ADM_LTPAGENT_EDD_SPANINSEGRXUNKCLIENTBYTES_MID", "The input segment unknown client bytes for the span.", ADM_LTPAGENT, ADM_LTPAGENT_EDD_SPANINSEGRXUNKCLIENTBYTES_MID);
	UI_ADD_PARMSPEC_1(ADM_LTPAGENT_EDD_SPANINSEGRXUNKCLIENTBYTES_MID, "spanId", AMP_TYPE_UINT);

	adm_add_edd(ADM_LTPAGENT_EDD_SPANINSEGSTRAYCNT_MID, AMP_TYPE_UINT, 0, NULL, NULL, NULL);
	names_add_name("ADM_LTPAGENT_EDD_SPANINSEGSTRAYCNT_MID", "The input segment stray count for the span.", ADM_LTPAGENT, ADM_LTPAGENT_EDD_SPANINSEGSTRAYCNT_MID);
	UI_ADD_PARMSPEC_1(ADM_LTPAGENT_EDD_SPANINSEGSTRAYCNT_MID, "spanId", AMP_TYPE_UINT);

	adm_add_edd(ADM_LTPAGENT_EDD_SPANINSEGSTRAYBYTES_MID, AMP_TYPE_UINT, 0, NULL, NULL, NULL);
	names_add_name("ADM_LTPAGENT_EDD_SPANINSEGSTRAYBYTES_MID", "The input segment stray bytes for the span.", ADM_LTPAGENT, ADM_LTPAGENT_EDD_SPANINSEGSTRAYBYTES_MID);
	UI_ADD_PARMSPEC_1(ADM_LTPAGENT_EDD_SPANINSEGSTRAYBYTES_MID, "spanId", AMP_TYPE_UINT);

	adm_add_edd(ADM_LTPAGENT_EDD_SPANINSEGMISCOLORCNT_MID, AMP_TYPE_UINT, 0, NULL, NULL, NULL);
	names_add_name("ADM_LTPAGENT_EDD_SPANINSEGMISCOLORCNT_MID", "The input segment miscolored count for the span.", ADM_LTPAGENT, ADM_LTPAGENT_EDD_SPANINSEGMISCOLORCNT_MID);
	UI_ADD_PARMSPEC_1(ADM_LTPAGENT_EDD_SPANINSEGMISCOLORCNT_MID, "spanId", AMP_TYPE_UINT);

	adm_add_edd(ADM_LTPAGENT_EDD_SPANINSEGMISCOLORBYTES_MID, AMP_TYPE_UINT, 0, NULL, NULL, NULL);
	names_add_name("ADM_LTPAGENT_EDD_SPANINSEGMISCOLORBYTES_MID", "The input segment miscolored bytes for the span.", ADM_LTPAGENT, ADM_LTPAGENT_EDD_SPANINSEGMISCOLORBYTES_MID);
	UI_ADD_PARMSPEC_1(ADM_LTPAGENT_EDD_SPANINSEGMISCOLORBYTES_MID, "spanId", AMP_TYPE_UINT);

	adm_add_edd(ADM_LTPAGENT_EDD_SPANINSEGCLOSEDCNT_MID, AMP_TYPE_UINT, 0, NULL, NULL, NULL);
	names_add_name("ADM_LTPAGENT_EDD_SPANINSEGCLOSEDCNT_MID", "The input segment closed count for the span.", ADM_LTPAGENT, ADM_LTPAGENT_EDD_SPANINSEGCLOSEDCNT_MID);
	UI_ADD_PARMSPEC_1(ADM_LTPAGENT_EDD_SPANINSEGCLOSEDCNT_MID, "spanId", AMP_TYPE_UINT);

	adm_add_edd(ADM_LTPAGENT_EDD_SPANINSEGCLOSEDBYTES_MID, AMP_TYPE_UINT, 0, NULL, NULL, NULL);
	names_add_name("ADM_LTPAGENT_EDD_SPANINSEGCLOSEDBYTES_MID", "The input segment closed bytes for the span.", ADM_LTPAGENT, ADM_LTPAGENT_EDD_SPANINSEGCLOSEDBYTES_MID);
	UI_ADD_PARMSPEC_1(ADM_LTPAGENT_EDD_SPANINSEGCLOSEDBYTES_MID, "spanId", AMP_TYPE_UINT);

	adm_add_edd(ADM_LTPAGENT_EDD_SPANINCKPTRXCNT_MID, AMP_TYPE_UINT, 0, NULL, NULL, NULL);
	names_add_name("ADM_LTPAGENT_EDD_SPANINCKPTRXCNT_MID", "The input checkpoint receive count for the span.", ADM_LTPAGENT, ADM_LTPAGENT_EDD_SPANINCKPTRXCNT_MID);
	UI_ADD_PARMSPEC_1(ADM_LTPAGENT_EDD_SPANINCKPTRXCNT_MID, "spanId", AMP_TYPE_UINT);

	adm_add_edd(ADM_LTPAGENT_EDD_SPANINPOSACKTXCNT_MID, AMP_TYPE_UINT, 0, NULL, NULL, NULL);
	names_add_name("ADM_LTPAGENT_EDD_SPANINPOSACKTXCNT_MID", "The input positive acknolwedgement transmitted count for the span.", ADM_LTPAGENT, ADM_LTPAGENT_EDD_SPANINPOSACKTXCNT_MID);
	UI_ADD_PARMSPEC_1(ADM_LTPAGENT_EDD_SPANINPOSACKTXCNT_MID, "spanId", AMP_TYPE_UINT);

	adm_add_edd(ADM_LTPAGENT_EDD_SPANINNEGACKTXCNT_MID, AMP_TYPE_UINT, 0, NULL, NULL, NULL);
	names_add_name("ADM_LTPAGENT_EDD_SPANINNEGACKTXCNT_MID", "The input negative acknowledgement transmitted count for the span.", ADM_LTPAGENT, ADM_LTPAGENT_EDD_SPANINNEGACKTXCNT_MID);
	UI_ADD_PARMSPEC_1(ADM_LTPAGENT_EDD_SPANINNEGACKTXCNT_MID, "spanId", AMP_TYPE_UINT);

	adm_add_edd(ADM_LTPAGENT_EDD_SPANINCANCELTXCNT_MID, AMP_TYPE_UINT, 0, NULL, NULL, NULL);
	names_add_name("ADM_LTPAGENT_EDD_SPANINCANCELTXCNT_MID", "The input cancel transmited count for the span.", ADM_LTPAGENT, ADM_LTPAGENT_EDD_SPANINCANCELTXCNT_MID);
	UI_ADD_PARMSPEC_1(ADM_LTPAGENT_EDD_SPANINCANCELTXCNT_MID, "spanId", AMP_TYPE_UINT);

	adm_add_edd(ADM_LTPAGENT_EDD_SPANINACKRETXCNT_MID, AMP_TYPE_UINT, 0, NULL, NULL, NULL);
	names_add_name("ADM_LTPAGENT_EDD_SPANINACKRETXCNT_MID", "The input acknolwedgement retransmit count for the span.", ADM_LTPAGENT, ADM_LTPAGENT_EDD_SPANINACKRETXCNT_MID);
	UI_ADD_PARMSPEC_1(ADM_LTPAGENT_EDD_SPANINACKRETXCNT_MID, "spanId", AMP_TYPE_UINT);

	adm_add_edd(ADM_LTPAGENT_EDD_SPANINCANCELRXCNT_MID, AMP_TYPE_UINT, 0, NULL, NULL, NULL);
	names_add_name("ADM_LTPAGENT_EDD_SPANINCANCELRXCNT_MID", "The input cancel receive count for the span.", ADM_LTPAGENT, ADM_LTPAGENT_EDD_SPANINCANCELRXCNT_MID);
	UI_ADD_PARMSPEC_1(ADM_LTPAGENT_EDD_SPANINCANCELRXCNT_MID, "spanId", AMP_TYPE_UINT);

	adm_add_edd(ADM_LTPAGENT_EDD_SPANINCOMPLETECNT_MID, AMP_TYPE_UINT, 0, NULL, NULL, NULL);
	names_add_name("ADM_LTPAGENT_EDD_SPANINCOMPLETECNT_MID", "The input completed count for the span.", ADM_LTPAGENT, ADM_LTPAGENT_EDD_SPANINCOMPLETECNT_MID);
	UI_ADD_PARMSPEC_1(ADM_LTPAGENT_EDD_SPANINCOMPLETECNT_MID, "spanId", AMP_TYPE_UINT);

}

void adm_LtpAgent_init_variables()
{
}

void adm_LtpAgent_init_controls()
{
	adm_add_ctrl(ADM_LTPAGENT_CTRL_RESET_MID, NULL);
	names_add_name("ADM_LTPAGENT_CTRL_RESET_MID", "Resets the counters associated with the engine and updates the last reset time for the span to be the time when this control was run.", ADM_LTPAGENT, ADM_LTPAGENT_CTRL_RESET_MID);
	UI_ADD_PARMSPEC_1(ADM_LTPAGENT_CTRL_RESET_MID, "engine", AMP_TYPE_UINT);

	adm_add_ctrl(ADM_LTPAGENT_CTRL_LISTENGINES_MID, NULL);
	names_add_name("ADM_LTPAGENT_CTRL_LISTENGINES_MID", "Lists all remote engine IDs.", ADM_LTPAGENT, ADM_LTPAGENT_CTRL_LISTENGINES_MID);

}

void adm_LtpAgent_init_constants()
{

}

void adm_LtpAgent_init_macros()
{

}

void adm_LtpAgent_init_metadata()
{
	/* Step 1: Register Nicknames */
	oid_nn_add_parm(LTPAGENT_ADM_META_NN_IDX, LTPAGENT_ADM_META_NN_STR, "LTPAGENT", "2017-08-17");
	oid_nn_add_parm(LTPAGENT_ADM_EDD_NN_IDX, LTPAGENT_ADM_EDD_NN_STR, "LTPAGENT", "2017-08-17");
	oid_nn_add_parm(LTPAGENT_ADM_VAR_NN_IDX, LTPAGENT_ADM_VAR_NN_STR, "LTPAGENT", "2017-08-17");
	oid_nn_add_parm(LTPAGENT_ADM_RPT_NN_IDX, LTPAGENT_ADM_RPT_NN_STR, "LTPAGENT", "2017-08-17");
	oid_nn_add_parm(LTPAGENT_ADM_CTRL_NN_IDX, LTPAGENT_ADM_CTRL_NN_STR, "LTPAGENT", "2017-08-17");
	oid_nn_add_parm(LTPAGENT_ADM_CONST_NN_IDX, LTPAGENT_ADM_CONST_NN_STR, "LTPAGENT", "2017-08-17");
	oid_nn_add_parm(LTPAGENT_ADM_MACRO_NN_IDX, LTPAGENT_ADM_MACRO_NN_STR, "LTPAGENT", "2017-08-17");
	oid_nn_add_parm(LTPAGENT_ADM_OP_NN_IDX, LTPAGENT_ADM_OP_NN_STR, "LTPAGENT", "2017-08-17");
	oid_nn_add_parm(LTPAGENT_ADM_TBL_NN_IDX, LTPAGENT_ADM_TBL_NN_STR, "LTPAGENT", "2017-08-17");
	oid_nn_add_parm(LTPAGENT_ADM_ROOT_NN_IDX, LTPAGENT_ADM_ROOT_NN_STR, "LTPAGENT", "2017-08-17");
	/* Step 2: Register Metadata Information. */
	adm_add_edd(ADM_LTPAGENT_META_NAME_MID, AMP_TYPE_STRING, 0, NULL, adm_print_string, adm_size_string);
	names_add_name("ADM_LTPAGENT_META_NAME_MID", "The human-readable name of the ADM.", ADM_LTPAGENT, ADM_LTPAGENT_META_NAME_MID);
	adm_add_edd(ADM_LTPAGENT_META_NAMESPACE_MID, AMP_TYPE_STRING, 0, NULL, adm_print_string, adm_size_string);
	names_add_name("ADM_LTPAGENT_META_NAMESPACE_MID", "The namespace of the ADM.", ADM_LTPAGENT, ADM_LTPAGENT_META_NAMESPACE_MID);
	adm_add_edd(ADM_LTPAGENT_META_VERSION_MID, AMP_TYPE_STRING, 0, NULL, adm_print_string, adm_size_string);
	names_add_name("ADM_LTPAGENT_META_VERSION_MID", "The version of the ADM.", ADM_LTPAGENT, ADM_LTPAGENT_META_VERSION_MID);
	adm_add_edd(ADM_LTPAGENT_META_ORGANIZATION_MID, AMP_TYPE_STRING, 0, NULL, adm_print_string, adm_size_string);
	names_add_name("ADM_LTPAGENT_META_ORGANIZATION_MID", "The name of the issuing organization of the ADM.", ADM_LTPAGENT, ADM_LTPAGENT_META_ORGANIZATION_MID);

}

void adm_LtpAgent_init_ops()
{

}

void adm_LtpAgent_init_reports()
{
	uint32_t used= 0;

	Lyst rpt = lyst_create();
	lyst_insert_last(rpt,mid_deserialize_str(ADM_LTPAGENT_EDD_SPANREMOTEENGINENBR_MID, ADM_MID_ALLOC, &used));
	lyst_insert_last(rpt,mid_deserialize_str(ADM_LTPAGENT_EDD_SPANCUREXPTSESS_MID, ADM_MID_ALLOC, &used));
	lyst_insert_last(rpt,mid_deserialize_str(ADM_LTPAGENT_EDD_SPANCUROUTSEG_MID, ADM_MID_ALLOC, &used));
	lyst_insert_last(rpt,mid_deserialize_str(ADM_LTPAGENT_EDD_SPANCURIMPSESS_MID, ADM_MID_ALLOC, &used));
	lyst_insert_last(rpt,mid_deserialize_str(ADM_LTPAGENT_EDD_SPANCURINSEG_MID, ADM_MID_ALLOC, &used));
	lyst_insert_last(rpt,mid_deserialize_str(ADM_LTPAGENT_EDD_SPANRESETTIME_MID, ADM_MID_ALLOC, &used));
	lyst_insert_last(rpt,mid_deserialize_str(ADM_LTPAGENT_EDD_SPANOUTSEGQCNT_MID, ADM_MID_ALLOC, &used));
	lyst_insert_last(rpt,mid_deserialize_str(ADM_LTPAGENT_EDD_SPANOUTSEGQBYTES_MID, ADM_MID_ALLOC, &used));
	lyst_insert_last(rpt,mid_deserialize_str(ADM_LTPAGENT_EDD_SPANOUTSEGPOPCNT_MID, ADM_MID_ALLOC, &used));
	lyst_insert_last(rpt,mid_deserialize_str(ADM_LTPAGENT_EDD_SPANOUTSEGPOPBYTES_MID, ADM_MID_ALLOC, &used));
	lyst_insert_last(rpt,mid_deserialize_str(ADM_LTPAGENT_EDD_SPANOUTCKPTXMITCNT_MID, ADM_MID_ALLOC, &used));
	lyst_insert_last(rpt,mid_deserialize_str(ADM_LTPAGENT_EDD_SPANOUTPOSACKRXCNT_MID, ADM_MID_ALLOC, &used));
	lyst_insert_last(rpt,mid_deserialize_str(ADM_LTPAGENT_EDD_SPANOUTNEGACKRXCNT_MID, ADM_MID_ALLOC, &used));
	lyst_insert_last(rpt,mid_deserialize_str(ADM_LTPAGENT_EDD_SPANOUTCANCELRXCNT_MID, ADM_MID_ALLOC, &used));
	lyst_insert_last(rpt,mid_deserialize_str(ADM_LTPAGENT_EDD_SPANOUTCKPTREXMITCNT_MID, ADM_MID_ALLOC, &used));
	lyst_insert_last(rpt,mid_deserialize_str(ADM_LTPAGENT_EDD_SPANOUTCANCELXMITCNT_MID, ADM_MID_ALLOC, &used));
	lyst_insert_last(rpt,mid_deserialize_str(ADM_LTPAGENT_EDD_SPANOUTCOMPLETECNT_MID, ADM_MID_ALLOC, &used));
	lyst_insert_last(rpt,mid_deserialize_str(ADM_LTPAGENT_EDD_SPANINSEGRXREDCNT_MID, ADM_MID_ALLOC, &used));
	lyst_insert_last(rpt,mid_deserialize_str(ADM_LTPAGENT_EDD_SPANINSEGRXREDBYTES_MID, ADM_MID_ALLOC, &used));
	lyst_insert_last(rpt,mid_deserialize_str(ADM_LTPAGENT_EDD_SPANINSEGRXGREENBYTES_MID, ADM_MID_ALLOC, &used));
	lyst_insert_last(rpt,mid_deserialize_str(ADM_LTPAGENT_EDD_SPANINSEGRXREDUNDANTCNT_MID, ADM_MID_ALLOC, &used));
	lyst_insert_last(rpt,mid_deserialize_str(ADM_LTPAGENT_EDD_SPANINSEGRXREDUNDANTBYTES_MID, ADM_MID_ALLOC, &used));
	lyst_insert_last(rpt,mid_deserialize_str(ADM_LTPAGENT_EDD_SPANINSEGRXMALCNT_MID, ADM_MID_ALLOC, &used));
	lyst_insert_last(rpt,mid_deserialize_str(ADM_LTPAGENT_EDD_SPANINSEGRXMALBYTES_MID, ADM_MID_ALLOC, &used));
	lyst_insert_last(rpt,mid_deserialize_str(ADM_LTPAGENT_EDD_SPANINSEGRXUNKSENDCNT_MID, ADM_MID_ALLOC, &used));
	lyst_insert_last(rpt,mid_deserialize_str(ADM_LTPAGENT_EDD_SPANINSEGRXUNKSENDBYTES_MID, ADM_MID_ALLOC, &used));
	lyst_insert_last(rpt,mid_deserialize_str(ADM_LTPAGENT_EDD_SPANINSEGRXUNKCLIENTCNT_MID, ADM_MID_ALLOC, &used));
	lyst_insert_last(rpt,mid_deserialize_str(ADM_LTPAGENT_EDD_SPANINSEGRXUNKCLIENTBYTES_MID, ADM_MID_ALLOC, &used));
	lyst_insert_last(rpt,mid_deserialize_str(ADM_LTPAGENT_EDD_SPANINSEGSTRAYCNT_MID, ADM_MID_ALLOC, &used));
	lyst_insert_last(rpt,mid_deserialize_str(ADM_LTPAGENT_EDD_SPANINSEGSTRAYBYTES_MID, ADM_MID_ALLOC, &used));
	lyst_insert_last(rpt,mid_deserialize_str(ADM_LTPAGENT_EDD_SPANINSEGMISCOLORCNT_MID, ADM_MID_ALLOC, &used));
	lyst_insert_last(rpt,mid_deserialize_str(ADM_LTPAGENT_EDD_SPANINSEGMISCOLORBYTES_MID, ADM_MID_ALLOC, &used));
	lyst_insert_last(rpt,mid_deserialize_str(ADM_LTPAGENT_EDD_SPANINSEGCLOSEDCNT_MID, ADM_MID_ALLOC, &used));
	lyst_insert_last(rpt,mid_deserialize_str(ADM_LTPAGENT_EDD_SPANINSEGCLOSEDBYTES_MID, ADM_MID_ALLOC, &used));
	lyst_insert_last(rpt,mid_deserialize_str(ADM_LTPAGENT_EDD_SPANINCKPTRXCNT_MID, ADM_MID_ALLOC, &used));
	lyst_insert_last(rpt,mid_deserialize_str(ADM_LTPAGENT_EDD_SPANINPOSACKTXCNT_MID, ADM_MID_ALLOC, &used));
	lyst_insert_last(rpt,mid_deserialize_str(ADM_LTPAGENT_EDD_SPANINNEGACKTXCNT_MID, ADM_MID_ALLOC, &used));
	lyst_insert_last(rpt,mid_deserialize_str(ADM_LTPAGENT_EDD_SPANINCANCELTXCNT_MID, ADM_MID_ALLOC, &used));
	lyst_insert_last(rpt,mid_deserialize_str(ADM_LTPAGENT_EDD_SPANINACKRETXCNT_MID, ADM_MID_ALLOC, &used));
	lyst_insert_last(rpt,mid_deserialize_str(ADM_LTPAGENT_EDD_SPANINCANCELRXCNT_MID, ADM_MID_ALLOC, &used));
	lyst_insert_last(rpt,mid_deserialize_str(ADM_LTPAGENT_EDD_SPANINCOMPLETECNT_MID, ADM_MID_ALLOC, &used));

	adm_add_rpt(ADM_LTPAGENT_RPT_FULLSPANREPORT_MID, rpt);

	midcol_destroy(&rpt);

}

#endif // _HAVE_LTPAGENT_ADM_
