#!/bin/bash
#
# Sotirios-Angelos Lenas
# October 3, 2011

echo "Cleaning up old ION..."
rm -f ion_nodes 1.ipn.bss/ion.log 1.ipn.bss/node1.stdout 1.ipn.bss/ltpblock.* 1.ipn.bss/bpacq.* 2.ipn.bss/ion.log 2.ipn.bss/node2.stdout 2.ipn.bss/ltpblock.* 2.ipn.bss/bpacq.* 2.ipn.bss/bsscounter.output bssDB*
killm
