#!/usr/bin/env bash
## ION startup script for CRS aggregation test - Node 1 (source)

ionadmin	node.ionrc
sleep 1
ionadmin	../global.ionrc
sleep 1
ionsecadmin	node.ionsecrc
sleep 1
bpadmin		node.bprc
