#!/usr/bin/env bash
#
# Scott Burleigh
# August 9, 2012

echo "Cleaning up old ION..."
export ION_NODE_LIST_DIR=$PWD
killm f
rm -f ion_nodes 2.bench.dgr/ion.log 2.bench.dgr/bpdriverAduFile 3.bench.dgr/ion.log
