=head1 NAME

imcfw - bundle route computation task for the IMC scheme

=head1 SYNOPSIS

B<imcfw>

=head1 DESCRIPTION

B<imcfw> is a background "daemon" task that pops bundles from the queue of
bundle destined for IMC-scheme (Interplanetary Multicast) endpoints, determines
which "relatives" on the IMC multicast tree to forward the bundles to,
and appends those bundles to the appropriate queues of bundles pending
transmission to those proximate destinations.

For each possible proximate destination (that is, neighboring node) there is
a separate queue for each possible level of bundle priority: 0, 1, 2.  Each
outbound bundle is appended to the queue matching the bundle's designated
priority.

Proximate destination computation is determined by multicast group membership
as resulting from nodes' registration in multicast endpoints, governed by
multicast tree structure as configured by imcadmin(1).

B<imcfw> is spawned automatically by B<bpadmin> in response to the
's' (START) command that starts operation of Bundle Protocol on the local
ION node, and it is terminated by B<bpadmin> in response to an 'x' (STOP)
command.  B<imcfw> can also be spawned and terminated in response to
START and STOP commands that pertain specifically to the IMC scheme.

=head1 EXIT STATUS

=over 4

=item "0"

B<imcfw> terminated, for reasons noted in the B<ion.log> log file.  If this
termination was not commanded, investigate and solve the problem identified
in the log file and use B<bpadmin> to restart B<imcfw>.

=item "1"

B<imcfw> could not commence operations, for reasons noted in the B<ion.log>
log file.  Investigate and solve the problem identified in the log file, then
use B<bpadmin> to restart B<imcfw>.

=back

=head1 FILES

No configuration files are needed.

=head1 ENVIRONMENT

No environment variables apply.

=head1 DIAGNOSTICS

The following diagnostics may be issued to the B<ion.log> log file:

=over 4

=item imcfw can't attach to BP.

B<bpadmin> has not yet initialized BP operations.

=item imcfw can't load routing database.

B<ipnadmin> has not yet initialized the IPN scheme.

=item Can't create lists for route computation.

An unrecoverable database error was encountered.  B<imcfw> terminates.

=item 'imc' scheme is unknown.

The IMC scheme was not added when B<bpadmin> initialized BP operations.  Use
B<bpadmin> to add and start the scheme.

=item Can't take forwarder semaphore.

ION system error.  B<imcfw> terminates.

=item Can't exclude sender from routes.

An unrecoverable database error was encountered.  B<imcfw> terminates.

=item Can't enqueue bundle.

An unrecoverable database error was encountered.  B<imcfw> terminates.

=back

=head1 BUGS

Report bugs to <ion-dtn-support@lists.sourceforge.net>

=head1 SEE ALSO

bpadmin(1), imcadmin(1), bprc(5), imcrc(5)
