#!/bin/bash
# shell script to get node running
ionadmin	config.ionrc
sleep 1
ionsecadmin	config.ionsecrc
sleep 1
ltpadmin	config.ltprc
sleep 1
bpadmin		config.bprc
sleep 1
ipnadmin	config.ipnrc
sleep 1
cfdpadmin	config.cfdprc
