#!/usr/bin/env bash

echo "Cleaning up old ION..."
export ION_NODE_LIST_DIR=$PWD
killm f
rm -f 2.ipn.ltp/ion.log 3.ipn.ltp/ion.log

rm -f expected.txt
rm -f ion_nodes
rm -f 3.ipn.ltp/3_receive_file.txt
rm -f 3.ipn.ltp/3_results.txt
