#
# Hello World Program Waf script
# Adopted for ION BPv7 port to RTEMS 6.1 (ARM64 aarch64/a53_lp64_qemu)
#
from __future__ import print_function

rtems_version = "6"

try:
    import rtems_waf.rtems as rtems
except:
    print('error: no rtems_waf git submodule')
    import sys
    sys.exit(1)

def init(ctx):
    rtems.init(ctx, version = rtems_version, long_commands = True)

def bsp_configure(conf, arch_bsp):
    # Add BSP specific configuration checks
    pass

def options(opt):
    rtems.options(opt)

def configure(conf):
    rtems.configure(conf, bsp_configure = bsp_configure)

def build(bld):
    # Excluding CFDP by seting open source = 0
    ION_OPEN_SOURCE=0

    # Excluding DGR and BSSP for minimal RTEMS configuration
    # Set to 1 to enable these convergence layers
    ENABLE_DGR = 0
    ENABLE_BSSP = 0

    iondefines=[
        'RTEMS',
        'BP_EXTENDED',
        'CRYPTO',
        'ENABLE_IMC',
        'GDSSYMTAB',
        'GDSLOGGER',
        'USING_SDR_POINTERS',
        'NO_SDR_TRACE',
        'NO_PSM_TRACE',
        'NO_PROXY',
        'NO_DIRLIST',
        'NOEXPAT',
        'UDPTS',
        'TCPTS',
        'DGRTS',
        'SPACE_ORDER=3',
        'LONG_LONG_OKAY=1',
        'PRIVATE_SYMTAB',
        'USING_RTEMS_LIBBSD',
        'MAX_SPAWNS=32'
    ]

    # Check for inclusion of CFDP
    #   Currently CFDP is not included (ION_OPEN_SOURCE=0)
    #   When ION_OPEN_SOURCE=0, NASA_PROTECTED_FLIGHT_CODE is defined
    #   which excludes CFDP code from compilation

    if ION_OPEN_SOURCE == 0:
        iondefines+=['NASA_PROTECTED_FLIGHT_CODE']

    # Add conditional defines for DGR and BSSP
    if ENABLE_DGR == 1:
        iondefines+=['ENABLE_DGR']

    if ENABLE_BSSP == 1:
        iondefines+=['ENABLE_BSSP']

    # Not including the following
    # -DION_NO_DNS
    # Not building with nm
    # -DAGENT_ROLE
    # Not buidling with CFDP
    # -DNASA_PROTECTED_FLIGHT_CODE

    ionflags='-g -Wall -Werror -Wno-unused-variable'

    icisources = [
        'rfxclock.c',
        'ionadmin.c',
        'sdrmend.c',
        'ionunlock.c',
        'ionxnowner.c',
        'ionlog.c',
        'ionsecadmin.c',
        'crypto.c',
        'csi.c',
        'ionwarn.c',
        'ionrestart.c',
        'ionexit.c',
        'bpadmin.c',
        'bpsecadmin.c',
        'rtems_stubs.c'   # RTEMS pthread_kill and pause stubs
    ]

    iciinclude=[
        '../ici/include',
        '../ici/library',
        '../ici/crypto',
        '../bpv7/library',
        '../ltp/library',
        '../ici/test',
        '../ici/sdr',
        '../ici/libbloom-master',
        '../ici/libbloom-master/murmur2'
    ]

    icilibsources=[
        'bulk.c',
        'cbor.c',
        'crc.c',
        'ion.c',
        'ion_admin.c',
        'ion_network.c',
        'ionsec.c',
        'libicinm.c',
        'llcv.c',
        'lyst.c',
        'memmgr.c',
        'platform.c',
        'platform_sm.c',
        'psm.c',
        'radix.c',
        'rfx.c',
        'smlist.c',
        'smrbt.c',
        'sptrace.c',
        'zco.c',
        'sdrcatlg.c',
        'sdrhash.c',
        'sdrxn.c',
        'sdrmgt.c',
        'sdrstring.c',
        'sdrlist.c',
        'sdrtable.c'
    ]

    ltpsource=[
	    'ltpclock.c',
	    'ltpdeliv.c',
	    'ltpmeter.c',
	    'udplsi.c',
	    'udplso.c',
	    'ltpadmin.c',
	    'ltpsecadmin.c'
    ]

    ltpinclude=[
        '../ltp/include',
        '../ltp/library',
        '../ltp/library/ext'
    ]

    ltplibsources=[
        'libltp.c',
        'libltpnm.c',
        'libltpP.c',
        'ltpei.c',
        'ltpsec.c',
        'libsda.c',
        'libudplsa.c'
    ]

    # not included in port
    ltpudplsasources=[

    ]

    bpsources=[
	    'bpclock.c',
	    'bptransit.c',
        'bpclm.c',
        'bpstats.c',
        'bptrace.c',
        'bplist.c',
        'cpsd.c',
        'lgagent.c',
        'ipnadmin.c',
        'ipnfw.c',
        'ipnadminep.c',
        'ltpcli.c',
        'ltpclo.c',
        'bibeadmin.c',
        'bibeclo.c',
        'imcadminep.c',
        'imcfw.c'
    ]

    # Conditionally add DGR convergence layer sources
    if ENABLE_DGR == 1:
        bpsources += ['dgrcli.c', 'dgrclo.c']

    # Conditionally add BSSP convergence layer sources
    if ENABLE_BSSP == 1:
        bpsources += ['bsspcli.c', 'bsspclo.c']

    bplibsources=[
        'bpsec_instr.c',
        'bpsec_policy.c' ,
        'bpsec_policy_eventset.c',
        'bpsec_policy_event.c' ,
        'bpsec_policy_rule.c' ,
        'ion_test_sc.c' ,
        'bib_hmac_sha2_sc.c' ,
        'bcb_aes_gcm_sc.c' ,
        'rfc9173_utils.c' ,
        'sc_util.c' ,
        'sci.c' ,
        'sci_valmap.c' ,
        'sc_value.c' ,
        'bpsec_util.c' ,
        'bpsec_asb.c' ,
        'bibe.c' ,
        'libbp.c' ,
        'libbpP.c' ,
        'libbpnm.c' ,
        'libimcfw.c',
        'imc.c',
        'eureka.c' ,
        'bei.c' ,
        'bae.c' ,
        'bpq.c' ,
        'bcb.c' ,
        'bib.c' ,
        'hcb.c',
        'meb.c' ,
        'pnb.c' ,
        'snw.c' ,
        'libipnfw.c' ,
        'saga.c' ,
        'bloom.c' ,
        'MurmurHash2.c',
        'libcgr.c'
    ]

    bpinclude=[
        './',
        '../bpv7/include',
        '../bpv7/bpsec/sci',
        '../bpv7/bpsec/utils',
        '../bpv7/bpsec/instr',
        '../bpv7/bpsec/policy',
        '../bpv7/library',
        '../bpv7/library/ext',
        '../bpv7/library/ext/meb',
        '../bpv7/library/ext/bae',
        '../bpv7/ipn',
        '../bpv7/ipnd',
        '../bpv7/library/crypto',
        '../bpv7/tcp',
        '../bpv7/udp',
        '../bpv7/library/ext/snw',
        '../bpv7/bibe',
        '../bpv7/imc',
        '../bpv7/saga',
        '../bpv7/dtn2',
        '../bpv7/library/ext/bpsec',
        '../bpv7/library/ext/hcb',
        '../bpv7/library/ext/pnb',
        '../bpv7/library/ext/bpq',
        '../bpv7/library/ext/imc',
        '../bpv7/utils'
    ]

    # nm and adm are not used, list not vetted
    nmsource=[
        'adm.c',
        'adm_agent.c',
        'adm_bp.c',
        'adm_sbsp.c',
        'adm_ltp.c',
        'expr.c',
        'blob.c',
        'report.c',
        'rules.c',
        'ctrl.c',
        'table.c',
        'ion_if.c',
        'utils.c',
        'db.c',
        'nm_types.c',
        'ingest.c',
        'instr.c',
        'lcc.c',
        'ldc.c',
        'rda.c',
        'msg.c',
        'agent_db.c',
        'adm_ion_priv.c',
        'adm_ltp_priv.c',
        'adm_agent_impl.c',
        'adm_bp_impl.c',
        'adm_sbsp_impl.c',
        'nmagent.c'
    ]

    bsssources=[
        'bsscounter.c',
        'bssdriver.c'
    ]

    bsslibsources=[
        'libbss.c',
        'libbssP.c'
    ]

    bssinclude=[
        './',
        '../bss/include'
    ]

    bsspsources=[
        'bsspclock.c',
        'bsspadmin.c',
        'udpbsi.c',
        'udpbso.c',
        'libtcpbsa.c',
        'tcpbsi.c',
        'tcpbso.c'
    ]

    bsspinclude=[
        './',
        '../bssp/include',
        '../bssp/library'
    ]

    bssplibsources=[
        'libbssp.c',
	    'libbsspP.c'
    ]

    cfdpsources=[
        'bputa.c',
        'cfdpclock.c',
        'cfdpadmin.c',
        'bpcp.c',
        'bpcpd.c'
    ]

    cfdplibsources=[
        'libcfdp.c',
        'libcfdpP.c',
        'libcfdpops.c'
    ]

    cfdpinclude=[
        './',
        '../cfdp/include',
        '../cfdp/library',
        '../cfdp/utils'
    ]

    amssources=[
        'amsd.c',
        'librams.c',
        'ramscommon.c',
        'ramsgate.c',
        'amsshell.c',
        'amslog.c',
        'amslogprt.c',
        'amsmib.c',
        'amsstop.c'
    ]
    # marshal.c is part of libams.c

    amslibsources=[
        'amscommon.c',
        'crypt.c',
        'dgrts.c',
        'libams.c',
        'loadmib.c',
        'tcpts.c',
        'udpts.c'
    ]

    amsinclude=[
        './',
        '../ams/include',
        '../ams/rams'
    ]

    dgrlibsources=[
        'libdgr.c'
    ]

    dgrinclude=[
        './',
        '../dgr/include'
    ]

    testsources=[
        'bpsource.c',
        'bpsink.c',
        'bpcrash.c'
    ]

    # Minimal BP/LTP port - excluding AMS, BSS
    # DGR and BSSP conditionally included based on ENABLE_DGR and ENABLE_BSSP flags
    csrcs = ['ionrtems.c'] + icisources + ltpsource \
    + bpsources + testsources

    # Conditionally add BSSP daemon and admin sources
    if ENABLE_BSSP == 1:
        csrcs += bsspsources

    if ION_OPEN_SOURCE == 1:
        csrcs += cfdpsources

    # cfdpsources - not compiled into final executable,
    #      building CFDP library was okay but have issue
    #      building the final executable with WAF in RTEMS 5.1
    #      complain of unknown type in header files.
    #      To be fixed in future release. Current demo does
    #      require NM and CFDP functionalities

    # Minimal BP/LTP port - excluding AMS, BSS
    # DGR and BSSP conditionally included based on flags
    includes = ['./'] + iciinclude + ltpinclude + bpinclude

    # Conditionally add DGR include paths
    if ENABLE_DGR == 1:
        includes += dgrinclude

    # Conditionally add BSSP include paths
    if ENABLE_BSSP == 1:
        includes += bsspinclude

    if ION_OPEN_SOURCE == 1:
        includes += cfdpinclude

    rtems.build(bld)
    bld.stlib(
        target='ici',
        cflags=ionflags,
        source=icilibsources,
        includes=iciinclude,
        defines=iondefines,
        use=['m']
    )

    bld.stlib(
        target='ltp',
        cflags= ionflags,
        source=ltplibsources,
        includes=ltpinclude+iciinclude,
        defines=iondefines,
        use=['ici','m']
    )

    # Not building libudplsa.la, not used for this port

    # Conditionally build DGR library
    if ENABLE_DGR == 1:
        bld.stlib(
            target='dgr',
            cflags= ionflags,
            source=dgrlibsources,
            includes=dgrinclude+iciinclude,
            defines=iondefines,
            use=['ici','m']
        )

    # Conditionally build BSSP library
    if ENABLE_BSSP == 1:
        bld.stlib(
            target='bssp',
            cflags= ionflags,
            source=bssplibsources,
            includes=bsspinclude+iciinclude,
            defines=iondefines,
            use=['ici','m']
        )

    # Build BP library with conditional DGR and BSSP dependencies
    bp_includes = bpinclude + ltpinclude + iciinclude
    bp_use = ['ici', 'ltp', 'm']

    if ENABLE_DGR == 1:
        bp_includes += dgrinclude
        bp_use.insert(-1, 'dgr')  # Insert before 'm'

    if ENABLE_BSSP == 1:
        bp_includes += bsspinclude
        bp_use.insert(-1, 'bssp')  # Insert before 'm'

    bld.stlib(
        target='bp',
        cflags= ionflags,
        source=bplibsources,
        includes=bp_includes,
        defines=iondefines,
        use=bp_use
    )

    # AMS and BSS libraries excluded for minimal port

    if ION_OPEN_SOURCE == 1:
        bld.stlib(
            target='cfdp',
            cflags= ionflags,
            source=cfdplibsources,
            includes=iciinclude+bpinclude+cfdpinclude,
            defines=iondefines,
            use=['ici','bp','m']
        )

    # Minimal BP/LTP port - only required libraries
    libuse = ['ici', 'bp', 'ltp', 'm']

    # Conditionally add DGR and BSSP to linked libraries
    if ENABLE_DGR == 1:
        libuse.insert(-1, 'dgr')  # Insert before 'm'

    if ENABLE_BSSP == 1:
        libuse.insert(-1, 'bssp')  # Insert before 'm'

    if ION_OPEN_SOURCE == 1:
        libuse.insert(-1, 'cfdp')  # Insert before 'm'

    # Note: RTEMS pthread functions are in rtemscpu library

    bld(features = 'c cprogram',
        target = 'ion.exe',
        cflags = ionflags,
        source = csrcs,
        includes = includes,
        defines = iondefines,
        use=libuse,
        lib=['rtemscpu', 'rtemsbsp', 'bsd', 'm']  # RTEMS core, BSD networking, and Math libraries (order matters)
    )
