#  FILE:      bench-ams-graph.cg
#  CONTENT:   ION contact graph commands file
#  FOR:       ionadmin
#  BUILDER:   ION Configuration Editor
#  NETWORK:   bench-ams-ion    [ION ]
#  DATE:      2024-11-20 20:12
#
#  CONTACT_REL_REL_TIME
#  [1]                relative start time : 0 (secs) 
#  [2]                 relative stop time : 50000000 (secs) 
#  [3]                        source node : 2  
#  [4]                   destination node : 3  
#  [5]             transmission data rate : 2500000 (bytes per sec) 
#  [6]                 contact confidence : 1 (fraction) 
a contact +0  +50000000  2  3  2500000  1
#
#  CONTACT_REL_REL_TIME
#  [1]                relative start time : 0 (secs) 
#  [2]                 relative stop time : 50000000 (secs) 
#  [3]                        source node : 3  
#  [4]                   destination node : 2  
#  [5]             transmission data rate : 2500000 (bytes per sec) 
#  [6]                 contact confidence : 1 (fraction) 
a contact +0  +50000000  3  2  2500000  1
#
#  RANGE_REL_REL_TIME
#  [1]                relative start time : 0 (secs) 
#  [2]                 relative stop time : 50000000 (secs) 
#  [3]                           one node : 2  
#  [4]                         other node : 3  
#  [5]              transmission distance : 1 (light secs) 
a range +0  +50000000  2  3  1
#
#  RANGE_REL_REL_TIME
#  [1]                relative start time : 0 (secs) 
#  [2]                 relative stop time : 50000000 (secs) 
#  [3]                           one node : 3  
#  [4]                         other node : 2  
#  [5]              transmission distance : 1 (light secs) 
a range +0  +50000000  3  2  1
