#!/usr/bin/env bash
source "$(dirname "$0")/../bench_helpers"

echo > ion.log
echo -e "\nStarting ION Node 2 on localhost"

#normally you wouldn't do this on every startup
cp init.petition.log 9.petition.log

ionadmin	bench.ionrc
sleep 1
ionadmin	../global.ionrc
sleep 1
ionsecadmin	bench.ionsecrc
sleep 1
bpadmin		bench.bprc

#start ams daemon as config server and registrar
amsd mib.amsrc 127.0.0.1:2502 amsdemo test "" &

#wait for registrar cell census to complete
wait_for_log_event ion.log "cell census completed" 30 "AMS cell census"

#start ramsgate daemon
ramsgate amsdemo test 300 &
sleep 3
