API = ../library
INCL = ../include
ICI_INCL = ../../ici/include
UTILS = ../utils
DAEMON = ../daemon
UDP = ../udp
TCP = ../tcp
ICI_LIB = ../../ici/x86_64-linux/lib

# OPT = -O -D__linux__
OPT = -g -Wall -Werror -D__linux__ -fPIC -DSPACE_ORDER=3
CC = gcc $(OPT) $(ADD_FLAGS) -I$(API) -I$(INCL) -I$(UDP) -I$(TCP) -I$(ROOT)/include -I$(ICI_INCL) -I../../ici/library -L$(ICI_LIB)
LDFLAGS = -fPIC -shared
LD = gcc $(LDFLAGS)

PUBINCLS = \
	$(INCL)/bssp.h

LTPINCLS = \
	$(API)/bsspP.h \
	$(UDP)/udpbsa.h \
	$(TCP)/tcpbsa.h

RUNTIMES = bsspadmin bsspclock udpbso udpbsi tcpbso tcpbsi

ALL = check libbssp.so libtcpbsa.so $(RUNTIMES)

all:		$(ALL)

check:		$(LTPINCLS) $(PUBINCLS)
		rm -f *.o
		touch check

clean:
		rm -f *.o
		rm -f *.so
		rm -f $(ALL)
		rm -f ./lib/*
		rm -f ./bin/*

install:
		cp ../include/* $(ROOT)/include
		cp lib/* $(ROOT)/lib
		cp bin/* $(ROOT)/bin

uninstall:
		rm $(ROOT)/lib/libbssp.so
		rm $(ROOT)/lib/libtcpbsa.so
		for file in $(PUBINCLS); \
			do rm $(ROOT)/include/$(notdir $$file); done
		for file in $(RUNTIMES); \
			do rm $(ROOT)/bin/$(notdir $$file); done

#	-	-	Daemon executables	-	-	-	-

bsspclock:	bsspclock.o libbssp.so
		$(CC) -o bsspclock bsspclock.o -L./lib -L$(ROOT)/lib -lbssp -lici -lpthread -lm
		cp bsspclock ./bin

#	-	-	Utility executables	-	-	-	-

bsspadmin:	bsspadmin.o libbssp.so
		$(CC) -o bsspadmin bsspadmin.o -L./lib -L$(ROOT)/lib -lbssp -lici -lpthread -lm
		cp bsspadmin ./bin

#	-	-	UDP executables	-	-	-	-	-

udpbsi:		udpbsi.o libbssp.so
		$(CC) -o udpbsi udpbsi.o -L./lib -L$(ROOT)/lib -lbssp -lici -lpthread -lm
		cp udpbsi ./bin

udpbso:		udpbso.o libbssp.so
		$(CC) -o udpbso udpbso.o -L./lib -L$(ROOT)/lib -lbssp -lici -lpthread -lm
		cp udpbso ./bin

#	-	-	TCP executables-	-	-	-	-
tcpbsi:		tcpbsi.o libbssp.so
		$(CC) -o tcpbsi tcpbsi.o -L./lib -L$(ROOT)/lib -ltcpbsa -lbssp -lici -lpthread -lm
		cp tcpbsi ./bin

tcpbso:		tcpbso.o libbssp.so
		$(CC) -o tcpbso tcpbso.o -L./lib -L$(ROOT)/lib -ltcpbsa -lbssp -lici -lpthread -lm
		cp tcpbso ./bin

#	-	-	Libraries	-	-	-	-	-

libbssp.so:	libbssp.o libbsspP.o
		$(LD) -o libbssp.so libbssp.o libbsspP.o
		cp libbssp.so ./lib

libtcpbsa.so:	libtcpbsa.o
		$(LD) -o libtcpbsa.so libtcpbsa.o
		cp libtcpbsa.so ./lib

#	-	-	Object modules	-	-	-	-	-

%.o:		$(API)/%.c
		$(CC) -c $<

%.o:		$(UTILS)/%.c
		$(CC) -c $<

%.o:		$(DAEMON)/%.c
		$(CC) -c $<

%.o:		$(UDP)/%.c
		$(CC) -c $<

%.o:		$(TCP)/%.c
		$(CC) -c $<
