#!/usr/bin/env bash
#
# Nate Richard
# JPL
# April 1, 2026

echo "Cleaning up old ION..."
export ION_NODE_LIST_DIR=$PWD
killm f
rm -f ion_nodes 1.ipn.bp.udp/ion.log 1.ipn.bp.udp/node.stdout 1.ipn.bp.udp/bpdriverAduFile
