#!/bin/bash

echo "Cleaning up old ION files..."
rm -f ion_nodes 
rm -f 1.ipn.ltp/ion.log 1.ipn.ltp/node1*stdout 1.ipn.ltp/ltpblock.* 1.ipn.ltp/receivedFile 
rm -f 2.ipn.ltp/ion.log 2.ipn.ltp/node2*stdout 2.ipn.ltp/ltpblock.* 2.ipn.ltp/receivedFile
