=head1 NAME

bibeclo - BP convergence layer output task using bundle-in-bundle encapsulation

=head1 SYNOPSIS

B<bibeclo> I<peer_node_eid> I<destination_node_eid>

=head1 DESCRIPTION

B<bibeclo> is a background "daemon" task that extracts bundles from the
queues of bundles ready for transmission to I<destination_node_eid> via
bundle-in-bundle encapsulation (BIBE), encapsulates them in BP administrative
records of (non-standard) record type 7 (BP_ENCAPSULATED_BUNDLE), and sends
those administrative records to the DTN node identified by I<peer_node_eid>.
The receiving node is expected to process these received administrative
records by simply dispatching the encapsulated bundles as if they had been
received from neighboring nodes in the normal course of operations.

B<bibeclo> is spawned automatically by B<bpadmin> in response to the 's' (START)
command that starts operation of the Bundle Protocol, and it is terminated by
B<bpadmin> in response to an 'x' (STOP) command.  B<bibeclo> can also be
spawned and terminated in response to START and STOP commands that pertain
specifically to the BIBE convergence layer protocol.

=head1 EXIT STATUS

=over 4

=item "0"

B<bibeclo> terminated normally, for reasons noted in the B<ion.log> file.  If
this termination was not commanded, investigate and solve the problem identified
in the log file and use B<bpadmin> to restart B<bibeclo>.

=item "1"

B<bibeclo> terminated abnormally, for reasons noted in the B<ion.log> file.
Investigate and solve the problem identified in the log file, then use
B<bpadmin> to restart B<bibeclo>.

=back

=head1 FILES

No configuration files are needed.

=head1 ENVIRONMENT

No environment variables apply.

=head1 DIAGNOSTICS

The following diagnostics may be issued to the B<ion.log> log file:

=over 4

=item bibeclo can't attach to BP.

B<bpadmin> has not yet initialized Bundle Protocol operations.

=item No such bibe duct.

No BIBE outduct with duct name I<destination_node_eid> has been added to the BP
database.  Use B<bpadmin> to stop the BIBE convergence-layer protocol, add
the outduct, and then restart the BIBE protocol.

=item No such bcla.

No BIBE convergence layer adapter named I<peer_node_eid> has been added to
the BIBE database.  Use B<bibeadmin> to add the BCLA.

=item CLO task is already started for this duct.

Redundant initiation of B<bibeclo>.

=item Can't prepend header; CLO stopping.

This is a system error.  Check ION log, correct problem, and restart BIBE.

=item Can't send encapsulated bundle; CLO stopping.

This is a system error.  Check ION log, correct problem, and restart BIBE.

=item [!] Encapsulated bundle not sent.

Malformed bundle issuance request, which might be a software error.  Contact
technical support.

=back

=head1 BUGS

Report bugs to <ion-dtn-support@lists.sourceforge.net>

=head1 SEE ALSO

bibeadmin(1), bp(3), biberc(5)
