=head1 NAME

dtn2fw - bundle route computation task for the "dtn" scheme

=head1 SYNOPSIS

B<dtn2fw>

=head1 DESCRIPTION

B<dtn2fw> is a background "daemon" task that pops bundles from the queue of
bundle destined for "dtn"-scheme endpoints, computes proximate destinations
for those bundles, and appends those bundles to the appropriate queues of
bundles pending transmission to those computed proximate destinations.

For each possible proximate destination (that is, neighboring node) there is
a separate queue for each possible level of bundle priority: 0, 1, 2.  Each
outbound bundle is appended to the queue matching the bundle's designated
priority.

Proximate destination computation is affected by static routes as configured
by dtn2admin(1).

B<dtn2fw> is spawned automatically by B<bpadmin> in response to the
's' (START) command that starts operation of Bundle Protocol on the local
ION node, and it is terminated by B<bpadmin> in response to an 'x' (STOP)
command.  B<dtn2fw> can also be spawned and terminated in response to
START and STOP commands that pertain specifically to the "dtn" scheme.

=head1 EXIT STATUS

=over 4

=item "0"

B<dtn2fw> terminated, for reasons noted in the B<ion.log> log file.  If this
termination was not commanded, investigate and solve the problem identified
in the log file and use B<bpadmin> to restart B<dtn2fw>.

=item "1"

B<dtn2fw> could not commence operations, for reasons noted in the B<ion.log>
log file.  Investigate and solve the problem identified in the log file, then
use B<bpadmin> to restart B<dtn2fw>.

=back

=head1 FILES

No configuration files are needed.

=head1 ENVIRONMENT

No environment variables apply.

=head1 DIAGNOSTICS

The following diagnostics may be issued to the B<ion.log> log file:

=over 4

=item dtn2fw can't attach to BP.

B<bpadmin> has not yet initialized BP operations.

=item dtn2fw can't load routing database.

B<dtn2admin> has not yet initialized the "dtn" scheme.

=item Can't create lists for route computation.

An unrecoverable database error was encountered.  B<dtn2fw> terminates.

=item 'dtn' scheme is unknown.

The "dtn" scheme was not added when B<bpadmin> initialized BP operations.  Use
B<bpadmin> to add and start the scheme.

=item Can't take forwarder semaphore.

ION system error.  B<dtn2fw> terminates.

=item Can't enqueue bundle.

An unrecoverable database error was encountered.  B<dtn2fw> terminates.

=back

=head1 BUGS

Report bugs to <ion-dtn-support@lists.sourceforge.net>

=head1 SEE ALSO

bpadmin(1), dtn2admin(1), bprc(5), dtn2rc(5).
