#!/usr/bin/env bash
#
# Cleanup script for issue-37-blknum-overflow test

echo "Cleaning up old ION..."
export ION_NODE_LIST_DIR=$PWD
killm f
rm -f ion_nodes 2.ipn.udp/ion.log 3.ipn.udp/ion.log
rm -rf __pycache__
