/*
 * entropy_test.c
 * 
 * A utility program to generate random bytes using an entropy source and write them to stdout.
 * This program is designed to generate a specific amount of random data in binary format.
 * 
 * Compilation:
 * Use the following command to compile the program:
 * gcc -o entropy_test entropy_test.c -lici
 * 
 * - This program depends on the `entropy_src` object, which is part of the ICI library (`libici`).
 * - The required `entropy_src.h` is located in the ION source tree (`ion/ici/crypto/entropy_src.h`).
 * - The ICI library, including `entropy_src`, is built and installed as part of the ION package.
 * - Ensure that ION is properly built and installed to satisfy this dependency.
 * 
 * Execution:
 * While this program can be executed directly, it is designed to integrate with the provided `dotest` script
 * for comprehensive randomness testing. The recommended execution method is:
 * 
 * ./dotest
 * 
 * The `dotest` script will invoke this program to generate random bytes, run statistical randomness
 * tests (e.g., `dieharder`, `rngtest`), and summarize the results in a detailed and user-friendly manner.
 * 
 * Direct execution example:
 * ./entropy_test > random_data.bin
 * This generates approximately 10 MB of random data (1 KB * 10,000 iterations) and writes it to the
 * file `random_data.bin` in binary format.
 * 
 * Parameters:
 * - BUFFERSIZE: The size of the buffer used to store random bytes (1 KB).
 * - ITERATIONS: The number of iterations to poll the entropy source (~10 MB total output).
 */


#include <stdio.h>                      /* For standard I/O functions */
#include <unistd.h>                     /* For the write and close system calls */
#include <string.h>                     /* For memset */
#include "../../crypto/entropy_src.h"   /* Custom header for entropy source */

#define BUFFERSIZE 1024                 /* 1 KB buffer size for each read */
#define ITERATIONS 10000                /* Generate ~10 MB of random data (1 KB * 10,000 iterations) */

/*
 * Main function to generate random bytes and output them to stdout.
 * 
 * - Allocates a buffer to hold entropy bytes.
 * - Polls the entropy source for random bytes in each iteration.
 * - Writes the generated bytes to stdout in binary format.
 */
int main(void) 
{
    unsigned char entropy_buffer[BUFFERSIZE] = {0}; /* Buffer to hold random bytes */
    size_t output_size = 0;                         /* Number of bytes generated in each iteration */
    int poll_result = 0;                            /* Return value from `poll_entropy_src` */

    /*
     * Loop to generate random bytes.
     * - Calls `poll_entropy_src` to fetch entropy into the buffer.
     * - Writes the fetched entropy to stdout.
     * - Clears the buffer after each iteration.
     */
    for (size_t counter = 0; counter < ITERATIONS; ++counter) 
    {
        /* Poll the entropy source to fill the buffer */
        poll_result = poll_entropy_src(NULL, entropy_buffer, BUFFERSIZE, &output_size);
        if (poll_result < 0) 
        {
            /* Handle errors from the entropy source */
            fprintf(stderr, "Error: %s\n", getErrorMessage(poll_result));
            return poll_result;
        } else 
        {
            /* Write the entropy bytes to stdout in binary format */
            fwrite(entropy_buffer, 1, output_size, stdout);
        }
        /* Clear the buffer to avoid residual data */
        memset(entropy_buffer, 0, BUFFERSIZE);
    }

    return 0; /* Successful execution */
}
