/*****************************************************************************
 **
 ** File Name: entropy_test.c
 **
 ** Description: A utility program to generate random bytes using the
 ** entropy_src library and write them to stdout. This
 ** program is designed for randomness quality testing.
 **
 ** Notes:
 ** - This program depends on the `entropy_src` object, which is part of
 ** the ION/ICI library (`libici`).
 ** - It is designed to be invoked by the `dotest` script for
 ** comprehensive analysis.
 **
 ** Assumptions:
 ** - The ION development environment is set up and `libici` has been
 ** built and is available to the linker.
 **
 ** Compilation:
 ** gcc -o entropy_test entropy_test.c -lici -I/path/to/ion/ici/crypto
 **
 **
 ** Modification History:
 ** MM/DD/YY  AUTHOR         DESCRIPTION
 ** --------  ------------   ---------------------------------------------
 ** 12/11/24  S. DeBaun      Initial implementation for testing poll_entropy_src
 ** 06/05/25  S. DeBaun      Updated for improved efficiency and safer fwrite
 *****************************************************************************/


#include <stdio.h>                      /* For standard I/O functions       */
#include <unistd.h>                     /* For write and close system calls */
#include "../../crypto/entropy_src.h"   /* Custom header for entropy source */
#include <platform.h>

#define BUFFERSIZE 1024                 /* 1 KB buffer size for each read  */
#define ITERATIONS 10000                /* Generate ~10 MB of random data  */


/*===========================================================================
 * Main function to generate random bytes and output them to stdout.
 *
 * - Allocates a buffer to hold entropy bytes.
 * - Polls the entropy source for random bytes in each iteration.
 * - Writes the generated bytes to stdout in binary format.
 *==========================================================================*/
int main(void)
{
	unsigned char entropy_buffer[BUFFERSIZE];
	size_t output_size = 0;
	int poll_result = 0;

	for (size_t counter = 0; counter < ITERATIONS; ++counter)
	{
		poll_result = poll_entropy_src(NULL, entropy_buffer, BUFFERSIZE, &output_size);
		if (poll_result < 0)
		{
			fprintf(stderr, "Error: %s\n", get_error_message(poll_result));
			return poll_result;
		}

		if (output_size > 0)
		{
			/*
			 * A single fwrite call is not guaranteed to write all bytes, loop
			 * until it's all written.
			 */
			size_t total_written = 0;
			while (total_written < output_size)
			{
				size_t written_now = fwrite(entropy_buffer + total_written, 1, output_size - total_written, stdout);
				if (written_now == 0)
				{
					/* If we can't write, we must exit to avoid an infinite loop. */
					fprintf(stderr, "Error: Failed to write to stdout.\n");
					return 1;
				}
				total_written += written_now;
			}
		}
	}

	return 0;
}
