#!/usr/bin/env bash
# Issue 352 - BPCP
# Samuel Jero
# April 15, 2012

echo "Cleaning up old ION..."
killm
rm -f 1.ipn.cfdp.bp.ltp/ion.log 2.ipn.cfdp.bp.ltp/ion.log 3.ipn.cfdp.bp.ltp/ion.log
rm -f 3.ipn.cfdp.bp.ltp/test1 1.ipn.cfdp.bp.ltp/test2 2.ipn.cfdp.bp.ltp/test3
rm -f ion_nodes
