#!/usr/bin/env bash
## ION startup script for heterogeneous test - Node 3 (CBR enabled)

ionadmin	node.ionrc
sleep 1
ionadmin	../global.ionrc
sleep 1
ionsecadmin	node.ionsecrc
sleep 1
bpadmin		node.bprc
