#!/usr/bin/env bash

echo "Cleaning up old ION..."
export ION_NODE_LIST_DIR=$PWD
killm f
rm -f 2.ipn.ltp/ion.log 3.ipn.ltp/ion.log 5.ipn.ltp/ion.log
rm -f 5.ipn.ltp/case1_out.txt 5.ipn.ltp/case2_out.txt 5.ipn.ltp/case3_out.txt
rm -f 5.ipn.ltp/testfile1
rm -f 5.ipn.ltp/testfile2
rm -f 5.ipn.ltp/testfile3
rm -f 5.ipn.ltp/testfile4
rm -f 5.ipn.ltp/testfile5
