UTILS = ../utils

# OPT = -O -Dlinux
OPT = -g -Wall -Werror -Dlinux -fPIC -DSPACE_ORDER=3
CC = gcc $(OPT) $(ADD_FLAGS) -I../.. -I../../ici/include -I../../ici/sdr -I../../ltp/include -I../../$(BP)/include -I../../bssp/include -I../../cfdp/include -I../../ltp/library -I../../bpv7/library -I../../cfdp/library -L../../ici/x86_64-linux/lib -L../../bpv7/x86_64-linux/lib -L../../bssp/x86_64-linux/lib -L../../ltp/x86_64-linux/lib -L../../cfdp/x86_64-linux/lib
LDFLAGS = -fPIC -shared
LD = gcc $(LDFLAGS)

LBP = -lbp

UTILITIES = ionrestart ionexit

ALL = $(UTILITIES)

all:		$(ALL)

clean:
		rm -f *.o
		rm -f $(ALL)
		rm -f ./bin/*

install:
		cp bin/* $(ROOT)/bin

uninstall:
		for file in $(UTILITIES); \
			do rm $(ROOT)/bin/$(notdir $$file); done

#	-	-	Utility executables	-	-	-	-

ionrestart:	ionrestart.o
		$(CC) -o ionrestart ionrestart.o -L./lib -L../../ici/x86_64-linux/lib -L../../ltp/x86_64-linux/lib -L../../$(BP)/x86_64-linux/lib -L../../cfdp/x86_64-linux/lib -lcfdp -lcgr $(LBP) -lltp -lici -lpthread -lm
		cp ionrestart ./bin

ionexit:	ionexit.o
		$(CC) -o ionexit ionexit.o -L./lib -L../../ici/x86_64-linux/lib -L../../ltp/x86_64-linux/lib -L../../$(BP)/x86_64-linux/lib -L../../bssp/x86_64-linux/lib -L../../cfdp/x86_64-linux/lib -lcfdp -lbssp -lbsspP $(LBP) -lltp -lici -lpthread -lm
		cp ionexit ./bin

#	-	-	Object modules	-	-	-	-	-

%.o:		$(UTILS)/%.c
		$(CC) -c $<
