#!/bin/bash
#
# Scott Burleigh
# August 9, 2012

echo "Cleaning up old ION..."
killm
rm -f ion_nodes 2.bench.bibe/ion.log 2.bench.bibe/bpdriverAduFile 2.bench.bibe/sdrwatch.log 3.bench.bibe/ion.log 3.bench.bibe/sdrwatch.log 4.bench.bibe/ion.log
