#!/usr/bin/env bash
#
# Cleanup script for ltp-config-split test
#

# Kill any remaining owltsim processes
export ION_NODE_LIST_DIR=$PWD
killm f
pkill -9 owltsim 2>/dev/null

# Remove output files
rm -f ion_nodes
rm -f 2.ipn.ltp/*.stdout
rm -f 3.ipn.ltp/*.stdout
rm -f 2.ipn.ltp/*.txt
rm -f 3.ipn.ltp/*.txt
rm -f 2.ipn.ltp/ion.log
rm -f 3.ipn.ltp/ion.log
rm -f 2.ipn.ltp/ltpblock.*
rm -f 3.ipn.ltp/ltpblock.*

echo "Cleanup complete."
