#!/usr/bin/env bash
#
# Scott Burleigh
# March 8, 2017

echo "Cleaning up old ION..."
export ION_NODE_LIST_DIR=$PWD
killm f
rm -f ion_nodes 2.bench.stcp/ion.log 2.bench.stcp/bpdriverAduFile 3.bench.stcp/ion.log bpcounter_test*.txt
