#!/bin/bash
#Sky DeBaun Mar 2024


shutdown_process() {
    local process_name=$1
    echo "Stopping $process_name..."
    local pids=$(ps | awk '/'"$process_name"'/ {print $1}')
    for pid in $pids; do
        if [[ -n $pid ]]; then
            kill $pid
            # Wait for the process to exit with a timeout
            local count=0
            local timeout=30 # 30 seconds timeout
            while kill -0 $pid 2>/dev/null; do
                sleep 1
                ((count++))
                if ((count >= timeout)); then
                    echo "Timeout reached, forcefully killing $process_name..."
                    kill -9 $pid
                    break
                fi
            done
        fi
    done
}

echo "Shutting down AMS..."
shutdown_process "ramsgate"
shutdown_process "amsbenchs"
shutdown_process "amsbenchr"
shutdown_process "amsd"

echo "Shutting down ION..."
sleep 1
./cleanup
./kill_udplis