name: Run All Best Effort Test and Report (BETR) Supported Platforms Manually

permissions:
  contents: read
  statuses: write
  pull-requests: read

on:
  workflow_dispatch:  # Manual trigger only
    inputs:
      tests_to_run:
        description: 'Space-separated list of tests to run (e.g., "test1 test2"). Leave blank to run all.'
        required: false
        type: string
        default: ''
      env_vars:
        description: 'Space-separated list of environment variables (e.g., "KEY1=VALUE1 KEY2=VALUE2").'
        required: false
        type: string
        default: ''

jobs:
  debianbookworm:
    uses: ./.github/workflows/ci-workflow-debianbookworm.yml
    with:
      tests_to_run: ${{ inputs.tests_to_run }}
      env_vars: ${{ inputs.env_vars }}

  freeBSD14:
    uses: ./.github/workflows/ci-workflow-freeBSD14.yml
    with:
      tests_to_run: ${{ inputs.tests_to_run }}

  macos_14_7_arm64:
    uses: ./.github/workflows/ci-workflow-macos_arm64.yml
    with:
      tests_to_run: ${{ inputs.tests_to_run }}
      env_vars: ${{ inputs.env_vars }}

  rpios:
    uses: ./.github/workflows/ci-workflow-rpios.yml
    with:
      tests_to_run: ${{ inputs.tests_to_run }}
      env_vars: ${{ inputs.env_vars }}

  fedora42:
    uses: ./.github/workflows/ci-workflow-fedora42.yml
    with:
      tests_to_run: ${{ inputs.tests_to_run }}
      env_vars: ${{ inputs.env_vars }}
