name: Regression Tests for ION on Debian Bookworm

on:
#  pull_request:
#    branches:
#      - integration
  workflow_call:
  workflow_dispatch:
    inputs:
      tests_to_run:
        description: 'Space-separated list of tests to run (e.g., "test1 test2"). Leave blank to run all.'
        required: false
        default: ''
      env_vars:
        description: 'Space-separated list of environment variables (e.g., "KEY1=VALUE1 KEY2=VALUE2").'
        required: false
        type: string
        default: ''

jobs:
  build-and-test:
    runs-on: [self-hosted, linux, x64, debianpodman]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Display OS and Arch
        run: |
          cat /etc/os-release
          echo "Arch:"
          uname -m
          echo "User ID:"
          id

      - name: Generate timestamp for file names
        id: timestamp
        run: echo "TIMESTAMP=$(date +'%Y%m%d-%H%M%S')" >> $GITHUB_ENV

      - name: Build ION and run tests
        run: |
          {
            echo "Starting build and tests at $(date)"
            export USER=$(whoami)
            echo "USER is set to: $USER"
            export ION_RUN_EXPERT="yes"
            export LD_LIBRARY_PATH=/usr/local/lib:$LD_LIBRARY_PATH
            autoreconf -fi
            ./configure --enable-crypto-mbedtls --enable-bpsec-debugging
            make -j4
            sudo make install
            make buildcheck
            sudo ldconfig
            cd tests
            # Set environment variables if provided
            if [ -n "${{ github.event.inputs.env_vars }}" ]; then
              echo "Setting environment variables: ${{ github.event.inputs.env_vars }}"
              for env_var in ${{ github.event.inputs.env_vars }}; do
                export "$env_var"
              done
            fi
            if [ "${{ github.event_name }}" = "workflow_dispatch" ] && [ -n "${{ github.event.inputs.tests_to_run }}" ]; then
              echo "Running specific tests: ${{ github.event.inputs.tests_to_run }}"
              ./runtests ${{ github.event.inputs.tests_to_run }}
            else
              echo "Running all tests"
              ./runtests
            fi
          } > build-and-test.log 2>&1

      - name: Display Progress
        if: ${{ always() }}
        run: |
          cat ./tests/progress | grep "FAILED" || { printf "No failed tests.\n"; exit 0; }

      - name: Upload full build and test log
        if: ${{ always() }}
        uses: actions/upload-artifact@v4
        with:
          name: build-and-test-log-debian-${{ env.TIMESTAMP }}
          path: build-and-test.log

      - name: Upload progress file
        if: ${{ always() }}
        uses: actions/upload-artifact@v4
        with:
          name: test-progress-debian-${{ env.TIMESTAMP }}
          path: ./tests/progress

      - name: Clean up ION build
        if: ${{ always() }}
        run: |
          sudo make uninstall
          make clean
          rm -rf $GITHUB_WORKSPACE/*