name: Compiling for ION on MacOS self-hosted 14.7 X64

on:
  pull_request:
    branches:
      - integration

  workflow_dispatch:

  push:
    branches:
      - update-4.1.4-ci-workflow

jobs:
  build-and-test:
    runs-on: [self-hosted, macOS, X64, 14.7] 

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4  # Checkout the code from the repository

#      - name: Set up dependencies
#        run: |
#          brew update
#          brew install autoconf automake libtool bash python3 gcc make

      - name: Generate timestamp for file names
        id: timestamp
        run: echo "TIMESTAMP=$(date +'%Y%m%d-%H%M%S')" >> $GITHUB_ENV

      - name: Run build and tests, capture stdout
        run: |
          {
            echo "Starting build and tests at $(date)"
            export ION_RUN_EXPERT="yes"
            autoreconf -fi
            ./configure --enable-crypto-mbedtls --enable-bpsec-debugging
            make
            sudo make install
            make test
            cd tests
            ./runtests
          } > build-and-test.log 2>&1

      - name: Display Progress
        if: ${{ always() }}  # Display progress even if tests were interrupted
        run: | 
          cat ./tests/progress

      - name: Upload full build and test log
        if: ${{ always() }}  # Capture log even if the previous step fails
        uses: actions/upload-artifact@v4
        with:
          name: build-and-test-log-${{ env.TIMESTAMP }}
          path: build-and-test.log  # Upload the entire stdout and stderr as an artifact

      - name: Upload progress file as artifact
        if: ${{ always() }}  # Capture progress even if the previous step fails
        uses: actions/upload-artifact@v4
        with:
          name: test-progress-${{ env.TIMESTAMP }}
          path: ./tests/progress  # Upload the 'progress' file for later review

      - name: Clean up ION build
        if: ${{ always() }}  # Clean up even if previous steps fails
        run: |
          sudo make uninstall
          make clean
          make distclean