name: Regression Tests for ION on RHEL9

on:
  pull_request:
    branches:
      - integration

  workflow_dispatch:

#  push:
#    branches:
#      - update-4.1.4-freebsd-update

jobs:
  build-and-test:
    runs-on: [self-hosted, linux, x64, rhel9podman]

#    container:  
#      image: registry.access.redhat.com/ubi9/ubi
#      options: --init      # Enable built-in init system

    steps:
      - name: Clean up workspace
        run: |
          rm -rf $GITHUB_WORKSPACE/*
          
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Display OS and Arch
        run: |
          cat /etc/os-release
          echo "Arch:"
          uname -m
          echo "User ID:"
          id
          echo "LD_LIBRARY_PATH=$LD_LIBRARY_PATH"
      
#      - name: Set up dependencies
#        run: |
#            yum --disableplugin=subscription-manager update -y 
#            yum --disableplugin=subscription-manager install -y gcc make automake autoconf libtool bash python3 psmisc procps diffutils
  
      - name: Generate timestamp for file names
        id: timestamp
        run: echo "TIMESTAMP=$(date +'%Y%m%d-%H%M%S')" >> $GITHUB_ENV

      - name: Run build and tests, capture stdout
        run: | 
          {
            echo "Starting build and tests at $(date)"
            export USER=$(whoami)  # Set USER to the current username
            echo "USER is set to: $USER"
            export ION_RUN_EXPERT="yes"
            export LD_LIBRARY_PATH=/usr/local/lib:$LD_LIBRARY_PATH
            autoreconf -fi
            ./configure --enable-crypto-mbedtls --enable-bpsec-debugging            
            make -j4
            sudo make install
            make buildcheck
            sudo ldconfig
            cd tests
            ./runtests
          } > build-and-test.log 2>&1

      - name: Display Progress
        if: ${{ always() }}  # Display progress even if tests were interrupted
        run: | 
          cat ./tests/progress | grep "FAILED" || { printf "No failed tests. \n"; exit 0; }

      - name: Upload full build and test log
        if: ${{ always() }}  # Capture log even if the previous step fails
        uses: actions/upload-artifact@v4
        with:
          name: build-and-test-log-${{ env.TIMESTAMP }}
          path: build-and-test.log  # Upload the entire stdout and stderr as an artifact

      - name: Upload progress file as artifact
        if: ${{ always() }}  # Capture progress even if the previous step fails
        uses: actions/upload-artifact@v4
        with:
          name: test-progress-${{ env.TIMESTAMP }}
          path: ./tests/progress  # Upload the 'progress' file for later review

      - name: Clean up ION build
        if: ${{ always() }}  # Clean up even if previous steps fails
        run: |
          sudo make uninstall
          make clean
          make distclean
          rm -rf $GITHUB_WORKSPACE/*