name: Create Release

on:
  push:
    tags:
      - 'ion-open-source-[0-9]+.[0-9]+.[0-9]+*'
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag to build (e.g., ion-open-source-1.2.3)'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.tag || github.ref }}
      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y autoconf automake libtool
      - name: Generate configure script
        run: |
          aclocal
          libtoolize --copy --force
          autoheader
          autoconf
          automake --add-missing
      - name: Backup Makefile.am  # This is needed when removing Unibo-CGR which modifies Makefile.am
        run: |
          cp Makefile.am Makefile.am.bak
          echo "EXTRA_DIST += Makefile.am.bak" >> Makefile.am
      - name: Create distribution tarball
        run: |
          ./configure
          make dist
      - name: Verify tarball contents
        run: |
          tar -tzf *.tar.gz | grep configure || (echo "Error: configure script not found in tarball" && exit 1)
      - name: Upload release artifact
        uses: softprops/action-gh-release@v1
        with:
          files: "*.tar.gz"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}