name: Compiling Testing for ION on MacOS - no regression test

on:
  workflow_dispatch:
  push:
    branches:
      - update-4.1.4-ci-workflow

jobs:
  build-and-test:
    runs-on: macos-latest  # Use Ubuntu. Or macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3  # Checkout the code from the repository

      - name: Set up dependencies
        run: |
          brew update
          brew install autoconf automake libtool bash python3 gcc make

      - name: Generate timestamp for file names
        id: timestamp
        run: echo "TIMESTAMP=$(date +'%Y%m%d-%H%M%S')" >> $GITHUB_ENV

      - name: Run build and tests, capture stdout
        run: | # For now run only test starting with "b", redirect stdout and stderr to a log
          {
            echo "Starting build and tests at $(date)"
            autoreconf -fi
            ./configure --disable-sysctl-check    # Cannot change kernel parameters; test build only
            make
            sudo make install
            sudo ldconfig
            cd tests
            ./runtests bptrace_terminal_test  # Run the test
          } > build-and-test.log 2>&1

      - name: Display Progress
        if: ${{ always() }}  # Display progress even if tests were interrupted
        run: | 
          cat ./tests/progress

      - name: Upload full build and test log
        if: ${{ always() }}  # Capture log even if the previous step fails
        uses: actions/upload-artifact@v4
        with:
          name: build-and-test-log-${{ env.TIMESTAMP }}
          path: build-and-test.log  # Upload the entire stdout and stderr as an artifact

      - name: Upload progress file as artifact
        if: ${{ always() }}  # Capture progress even if the previous step fails
        uses: actions/upload-artifact@v4
        with:
          name: test-progress-${{ env.TIMESTAMP }}
          path: ./tests/progress  # Upload the 'progress' file for later review
