name: Push to another repository

on:
  push:
    branches:
      - ION-documentation  # Or any branch you want to trigger the action

jobs:
  push_to_another_repo:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v3

    - name: Set up Git
      run: |
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"

    - name: Add the second repository as a remote
      run: |
        git remote add second-repo https://iondev33:${{ secrets.ION_DTN_PUSH_TOKEN }}@github.com/nasa-jpl/ION-DTN.git
        git fetch second-repo

    - name: Push to the second repository
      run: |
        git push second-repo ION-documentation

