#!/bin/bash
# shell script to get node running

ionadmin	node.ionrc
sleep 1
ionadmin	../global.ionrc
sleep 1
ionsecadmin	node.ionsecrc
sleep 1
ltpadmin    node.ltprc
sleep 1
bpadmin		node.bprc.1
sleep 1

